### ISSUE TITLE
Change static IP and flash to old IP via OTA

### ISSUE THREAD

**Issue by tubalainen** [esphome/feature-requests#100]
**Describe the problem you have/What new integration you would like**
When the numbers of instances starts to grow and you realize that you did not think ahead on the ip range to be used and want to re-arrange the IPs of all your instances it would be super great if a feature would allow to change the static ip in the yaml file and then recompile but with an option to flash OTA to any manually set IP (such as the prior IP before recompiling).

Possible solution 1.)
This could be an extra option under the `ota:` section in the yaml code. Such as `ota_ip:` in the yaml file

Possible solution 2.)
Be prompted when pushing the "upload" link if the ip address has changed to optionally fill in the "old IP for OTA update"

Many thanks in advance! <3

**Please describe your use case for this integration and alternatives you've tried:**

One can of course USB flash each device with the new firmware accordingly... But OTA would be super great and a breeze in comparison hence some of my personal devices are hidden in junction boxes, behind switches or light sockets....

**Additional context**

**Comment by OttoWinter** [comment]
See `use_address`
