### ISSUE TITLE
Max Current option for Light component

### ISSUE THREAD

**Issue by to4ko** [esphome/feature-requests#1007]
**Describe the problem you have/What new integration you would like**

It would be very useful to have max_current option for light component. The idea - to have limiting factor by specifying power supply data. 

**Please describe your use case for this integration and alternatives you've tried:**

Connecting long "heavy" led strip to power supply with low current specs and turning n the strip to full brightness. Could lead to dangerous situation.
**Additional context**

**Comment by nagyrobi** [comment]
Duplicate of https://github.com/esphome/feature-requests/issues/712
