### ISSUE TITLE
YAML Comments in Lambda

### ISSUE THREAD

**Issue by DeanoXX** [esphome/feature-requests#101]
**Describe the problem you have/What new integration you would like**
YAML Comments within Lambdas cause compilation failures as they are treated as C++ rather than removed/ignored.

**Please describe your use case for this integration and alternatives you've tried:**
Large Lambda sections require C++ comments "//" that then do not get  highlighted by common IDE looking at the file as pure YAML. Could we use "#" comments within Lambda sections for consistency that are then removed during validation/compilation as they are elsewhere in the YAML.

**Additional context**
N/A

**Comment by OttoWinter** [comment]
No, lambdas will always be pure C++ (with the tiny added `id()` helper function)

I do not want to open the can of worms of doing anything else than copying the lambda directly. For example, `#define` is valid C/C++ and used quite often. So treating hashtags differently could break things.

Syntax highlighting is a problem in the IDE, not so much ESPHome.
However, I think it would be possible ti create an esphome  plugin for some IDEs (i'm not going to do that though).
