### ISSUE TITLE
setting fan speed as a percentage value

### ISSUE THREAD

**Issue by gibman** [esphome/feature-requests#1015]
**Describe the problem you have/What new integration you would like**

I want to be able to use esphome to set a custom integer between 1-100 for setting the fan speed.
This does currently not seem to be supported.
There's only the 3 known presets (LOW, MEDIUM, HIGH).

**Please describe your use case for this integration and alternatives you've tried:**

In home assistant I have a custom coded impl. of a MQTT enabled fan on an esp8266.
Its interfaced with using this MQTT template within home assistant.

`
fan:
  - platform: mqtt  
    name: "fan AVR"  
    state_topic: "enkegaard/firstfloor/avr/fan/on/status"
    command_topic: "enkegaard/firstfloor/avr/fan/on/set"    
    payload_off: "0"
    payload_on: "1"
    speed_state_topic: "enkegaard/firstfloor/avr/fan/speed/status"
    speed_command_topic: "enkegaard/firstfloor/avr/fan/speed/set"    
    payload_low_speed: "20"
    payload_medium_speed: "50"
    payload_high_speed: "100"        
    qos: 2
    speeds:      
      - low
      - medium
      - high
`

This works perfectly when I set the speed as an integer value.
eg. using "developer tools>services"
fan.set_speed
entity_id: fan.avr_fan
speed: 68

this is then published to the MQTT broker, which in turn tells the esp device to set the fan speed to a specific percentage.
works splendid.

**Additional context**

My current esphome yaml is:
`output:
  - platform: esp8266_pwm
    pin: D4
    frequency: 1000 Hz
    id: avr_fan_pwm

fan:
  - platform: speed
    output: avr_fan_pwm
    name: "AVR Fan"
`

**Comment by DrBlokmeister** [comment]
Especially with the new version of Home Assistant, this would be a good thing to add.
