### ISSUE TITLE
Read Values and text from Nextion to ESPHOME: I am building a smart sprinkler system and would like the system to be able to operate stand alone, I want to adjust time for sprinkler zone from nextion to ESP8266

### ISSUE THREAD

**Issue by 288Pige0n** [esphome/feature-requests#1028]
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by lwqcz** [comment]
Please follow required template in order to properly place a valid feature request, thank you.

**Comment by SenexCrenshaw** [comment]
Have a look at the following PR: esphome/esphome#1464
This PR adds a lot of functionality!
