### ISSUE TITLE
Support for mcp4725 - 3.3v 12 bit i2c dac with EEPROM

### ISSUE THREAD

**Issue by fdepalo** [esphome/feature-requests#1031]
Hello, we are about to release a new i/o board that includes among all other chips already supported by Tasmota mcp4725 for dual or quad 0-10v output ( mainly for valves, dimmers, fan with 0-10v input )

It is possible to add support to tasmota? 

If dev requires so, we can ship him a board prototype for tests and development/integration.

Thank You

[MCP4725.pdf](https://github.com/esphome/feature-requests/files/5642608/MCP4725.pdf)

**Comment by JJK801** [comment]
@fdepalo ☝️  Merry christmas 🎄

**Comment by mlavelle42** [comment]
> > Hello, we are about to release a new i/o board that includes among all other chips already supported by Tasmota mcp4725 for dual or quad 0-10v output ( mainly for valves, dimmers, fan with 0-10v input )
> > It is possible to add support to tasmota?
> > If dev requires so, we can ship him a board prototype for tests and development/integration.
> > Thank You
> > [MCP4725.pdf](https://github.com/esphome/feature-requests/files/5642608/MCP4725.pdf)
> 
> Hi fdepalo, i can do it... but i would need some chips of them

Did anything come of this? I'm interested in a 0-10VDC output too.

**Comment by glmnet** [comment]
Mcp4725 is available in dev and beta
