### ISSUE TITLE
Ikea Idasek Desk Control

### ISSUE THREAD

**Issue by struthio** [esphome/feature-requests#1035]
**Describe the problem you have/What new integration you would like**

Integrate Ikea Idasen Desk control to ESPHome, so it can relay Desk Control (over BTLE) to Home Assistant.

**Please describe your use case for this integration and alternatives you've tried:**

Control Desk position from Home Assistant:
* Define favorite positions and allow desk to move directly to them by 'button'.
* Freely control desk position from Home Assistant.

**Additional context**

**Comment by bahlo** [comment]
See https://github.com/j5lien/esphome-idasen-desk-controller for a third-party-implementation
