### ISSUE TITLE
Set icon for light component

### ISSUE THREAD

**Issue by tatunts** [esphome/feature-requests#104]
**Describe the problem you have/What new integration you would like**
Hello.

It would be nice if we could set the icon for the light component/entity just like it is possible with many others (switch, text sensor for example), so it shows up on HA interface without having to do it later on customize.

**Please describe your use case for this integration and alternatives you've tried:**
Helping on get the most done by customizing the firmware and flashing to the device.

**Additional context**
Thanks a lot for all the effort on making ESPHome the go-to firmware for us, home automation and DIY lovers.

**Comment by claprepi** [comment]
+1

**Comment by OttoWinter** [comment]
Closing as this is more of a HA issue - the icon properties for sensor etc are already exceptions but there it's much more useful.
