### ISSUE TITLE
Exclude Cache/Data folder from snapshots

### ISSUE THREAD

**Issue by Marlor** [esphome/feature-requests#1059]
**Describe the problem you have/What new integration you would like**

Right now the Cache files are saved in a snapshot resulting in an 91mb big Snapshot (with 9 nodes)
vs 10**k**b big Snapshot if you manualy select "Clean Build Files" for every node.

**Please describe your use case for this integration and alternatives you've tried:**

Would be nice to have the Build Files excluded from snapshots or one button to delete the Cache from all nodes

**Additional context**

**Comment by ssieb** [comment]
This has been fixed now.  The build directory has been moved from `.esphome` to the container's `/data`.
