### ISSUE TITLE
Add support for receiving the battery level for Xiaomi LYWSD02

### ISSUE THREAD

**Issue by xanderdekok** [esphome/feature-requests#1067]
**Describe the problem you have/What new integration you would like**

The LYWSD02 has support for receiving the Temperature and the Humidity, but reading the battery level is missing. Most other Xiaomi devices have the support for receiving the battery level.

The LYWSD02 does broadcast the battery level. I can see it in the logging of the ESP32:
[16:48:22][D][xiaomi_ble:300]: Got Xiaomi LYWSD02 (E7:2E:00:D1:A4:85):
[16:48:22][D][xiaomi_ble:309]:   Battery Level: 29%

Please add the support for receiving the battery level. 

I need this, because I use a LYWSD02 as my temperature sensor for my central heating system. If the battery dies, it get's really cold in my house. ;) I would like to build an alert to replace the battery, before it runs out.

Thanks!

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by nikito7** [comment]
Use last dev

**Comment by ChefkeGremmen** [comment]
I guess this ticket can be closed right? It is already working in version 1.16.0 in my setup.

**Comment by xanderdekok** [comment]
It works for me also.
