### ISSUE TITLE
Climate IR

### ISSUE THREAD

**Issue by AGalfra** [esphome/feature-requests#1071]
**Describe the problem you have/What new integration you would like**

Quisiera poder agregar equipos de aire acondicionado para los cuales aun no hay soporte.
la idea es de poder utilizar la librería climate_ir como un dispositivo personalizado, y por ejemplo solo necesitaría incluir mi librería y sobre escribir la función transmit_state().

**Please describe your use case for this integration and alternatives you've tried:**

Si ya hay alguna forma de poder hacerlo por favor me lo indican, ya que no logro poder compilarlo de manera correcta.

**Additional context**

**Comment by glmnet** [comment]
Claro, hay varios, https://esphome.io/components/climate/ir_climate.html ahi estan todos, cada uno es un conjunto de 3 archivos, py, h y cpp que estan en la misma carpeta, deberias crear una carpeta nueva con el nombre que te interese y ESPHome deberia reconocer tu nuevo componente. Exitos!
