### ISSUE TITLE
Add a description or note field for each configuration on the dashboard

### ISSUE THREAD

**Issue by ttaggart4** [esphome/feature-requests#1073]
**Describe the problem you have/What new integration you would like**

Configuration names can be cryptic. A description would be helpful.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by glmnet** [comment]
https://esphome.io/components/esphome.html#configuration-variables

see the `comment:` option, is for dashboard .

If this is not what you're looking for, be more specific

**Comment by ttaggart4** [comment]
The comment is only visible when you edit the node. I would like to see something on the main dashboard - a description (could be the same as comment) under or next to the node name. It currently shows the node name and file name, which are the same by default. Adding a description would allow for reminding the user where the node is physically in the house at a glance, and easily changed if the device is moved. I'm just learning ESPHome, there is a lot I don't know about it yet! Thanks :)

**Comment by glmnet** [comment]
Ibb be guess you need to compile for the comment to show in the ui

**Comment by ttaggart4** [comment]
Yes that works.
