### ISSUE TITLE
Thermostat on webserver 

### ISSUE THREAD

**Issue by Monacoslo** [esphome/feature-requests#1086]
Thermostat is great component for heating, but especially due it is used for heating, needs to be always accessible.
ESPhome has perfect ability that if the network falls down, it can create hot spot and then you can connect directly to its webserver. But the issue is there is no thermostat. You can not even change the mode (off, heat). Can you please add the possibility to change at least basic things on webserver?

**Comment by rradar** [comment]
https://github.com/esphome/feature-requests/issues/714
