### ISSUE TITLE
Add support for MLX90614/GY-906 Remote IR Temperature Sensor

### ISSUE THREAD

**Issue by inforsgit** [esphome/feature-requests#109]
**Describe the problem you have/What new integration you would like**

Add support for the MLX90614/GY-906 Remote IR Temperature Sensor. The device is a non-contact infrared thermometer that connects via I2C using address 0x5a and gives two values - the ambient temperature and the temperature derived from the non-contact IR sensor which can be used to measure the temperature of a remote object.

**Please describe your use case for this integration and alternatives you've tried:**

Readout of this sensor is already available in ESPEasy but so far that is the only place I've seen it integrated. There is plenty of information on Sparkfun on how to use the sensor (see below).

**Additional context**

[Sensor description](https://www.melexis.com/en/product/MLX90614/Digital-Plug-Play-Infrared-Thermometer-TO-Can)
[Sparkfun usage guide](https://learn.sparkfun.com/tutorials/mlx90614-ir-thermometer-hookup-guide)

**Comment by lwqcz** [comment]
Maybe an Arduino library could help :-) https://www.arduinolibraries.info/libraries/mlx90614
I would appreciate the support of this HW too 👍

**Comment by lwqcz** [comment]
@OttoWinter any change to have support for these sensors? Like anytime soon? :-)

**Comment by tiaanv** [comment]
it's a year later, but I came across this thread searching for a solution.  Ended up implementing my own.  Please feel free to use it.  It may also be improved upon and integrated into esphome natively if you please. @OttoWinter 

[Github source here](https://github.com/tiaanv/esphome_gy906)

**Comment by minsuke** [comment]
> it's a year later, but I came across this thread searching for a solution. Ended up implementing my own. Please feel free to use it. It may also be improved upon and integrated into esphome natively if you please. @OttoWinter
> 
> [Github source here](https://github.com/tiaanv/esphome_gy906)

thx for your great code, but I have i2c gy906 device. can you recommend uart gy906 sensor ?

**Comment by 3gyptian** [comment]
@minsuke .. in case you're still looking for this I got custom sensor built for gy906 i2c and it's working pretty well ..

https://github.com/3gyptian/esphome-mlx90614-i2c_IR_temp_sensor

**Comment by roger-** [comment]
Another custom sensor [here](https://github.com/exxamalte/esphome-customisations/tree/master/mlx90614) (untested).

**Comment by duojianghuji** [comment]
> @minsuke .. in case you're still looking for this I got custom sensor built for gy906 i2c and it's working pretty well ..
> 
> https://github.com/3gyptian/esphome-mlx90614-i2c_IR_temp_sensor

It did not work for me. I'm using the ESPHome version(2021.11.4), could u please help?

![image](https://user-images.githubusercontent.com/66355796/145512464-d463652b-7053-41f7-a4b4-fb912b93b200.png)

**Comment by tsgoff** [comment]
> > @minsuke .. in case you're still looking for this I got custom sensor built for gy906 i2c and it's working pretty well ..
> > https://github.com/3gyptian/esphome-mlx90614-i2c_IR_temp_sensor
> 
> It did not work for me. I'm using the ESPHome version(2021.11.4), could u please help?
> 

add the following libraries in this order:
```
  libraries:
    - SPI
    - Wire
    - adafruit/Adafruit BusIO @ 1.9.6
    - "Adafruit SI1145 Library"
    - "Adafruit MLX90614 Library"
```

**Comment by duojianghuji** [comment]
> > > @minsuke .. in case you're still looking for this I got custom sensor built for gy906 i2c and it's working pretty well ..
> > > https://github.com/3gyptian/esphome-mlx90614-i2c_IR_temp_sensor
> > 
> > 
> > It did not work for me. I'm using the ESPHome version(2021.11.4), could u please help?
> 
> add the following libraries in this order:
> 
> ```
>   libraries:
>     - SPI
>     - Wire
>     - adafruit/Adafruit BusIO @ 1.9.6
>     - "Adafruit SI1145 Library"
>     - "Adafruit MLX90614 Library"
> ```

Thanks. Works well

**Comment by lwqcz** [comment]
Adafruit library is great source of inspiration, is there any plan to add support for this IR sensor? It would by great to sense PV panel temperature for instance.
