### ISSUE TITLE
Hide a sensor/switch in Home Assistant while using HA API

### ISSUE THREAD

**Issue by chaolue** [esphome/feature-requests#110]
**Describe the problem you have/What new integration you would like**

Add the ability to hide a sensor/switch in Home Assistant while using HA API

**Please describe your use case for this integration and alternatives you've tried:**

When I use the Home Assistant Binary/Text/Sensor sensors that pull sensor data from the Home Assistant using the API, these are then displayed as duplicate sensors back in Home Assistant. 

**Additional context**

Being able to hide any sensor/switch, not just the Home Assistant API based sensors, in Home Assistant may have a wider usage as well.

**Comment by OttoWinter** [comment]
See internal
