### ISSUE TITLE
Support for Waveshare ILI9486/XPT2046

### ISSUE THREAD

**Issue by EpicLPer** [esphome/feature-requests#1102]
**EDIT:** I wrongfully called the Waveshare display I wanted to be added here an ILI9341 at first, however completely overlooked the fact that even the Waveshare library itself said it‘s a ILI9486, not the other one. I‘ve since corrected my Request here and am sorry for the first wrong infos in here!

**Describe the problem you have/What new integration you would like**
In the Dev version of ESPHome support for standard 320x240 ILI9341 based displays has recently been added, see #51. A big thanks to the devs for this already :)  
Waveshare has a 3.5" (480x320) and 4" (800×480) version based on the same controller (and/or XPT2046? Not entirely sure where the difference lays here) which sadly does not work with this.

**Please describe your use case for this integration and alternatives you've tried:**
I tried the standard ILI9486 M5stack and TFT_2.4 options already but got no usable output, however the display does seem to read SPI data since, on M5stack, it constantly tries to refresh the display but seems to fail and on TFT_2.4 it very slightly flickers the whole screen. In both cases it never draws anything on screen tho.

**Additional context**
Waveshare offers their Arduino libraries for both TFT versions here: https://github.com/ImpulseAdventure/Waveshare_ILI9486  
I also found another library by „GoodTFT“ which also seems to offer one here: https://github.com/goodtft/LCD-show  
  
Thanks already for considering to adding this ❤

**Comment by danyboy666** [comment]
+1
