### ISSUE TITLE
Let the "partition" light combine single lights

### ISSUE THREAD

**Issue by HACKER-3000** [esphome/feature-requests#1107]
**Describe the problem you have/What new integration you would like**

The partition light should be able to combine single lights, so you can attach a few LEDs to your ESP and have them all as one Light that can still have adressable effects and such.

**Please describe your use case for this integration and alternatives you've tried:**

I connect 3 RGB LEDs and combine them into an 3 pixel/led ""strip""

**Additional context**

i hope tis is not too hard to implement

**Comment by paulmonigatti** [comment]
This feature has just been merged into dev (esphome/esphome#2256).
This PR should also implement #734, #910, and #966

**Comment by jesserockz** [comment]
Closed by esphome/esphome#2256
