### ISSUE TITLE
Add support for HA attributes

### ISSUE THREAD

**Issue by mikosoft83** [esphome/feature-requests#1112]
**Describe the problem you have/What new integration you would like**
Instead of using template sensors to extraxt attributes, add ability to read attributes directly in ESPHome.

**Please describe your use case for this integration and alternatives you've tried:**
It makes sharing reusable code (like my own flexible menu system) much easier, since there is no need to handle two configs (ESPH and HA).

**Additional context**

**Comment by ioios-io** [comment]
Seconded. The ability to share ESPHome software without having to add template sensors into the user's HA config makes sharing our ESPHome-based software so much easier for casual users. I'm praying for this one. Thanks devs for all you do.

**Comment by IainPHay** [comment]
If possible this would be great. ESPHone is absolutely wonderful but my skills are not up to the level yet where I can use this kind of described project without a great deal of head scratching!

**Comment by frenck** [comment]
Last night I've been playing a bit with this:

![2021-05-11 03 07 29](https://user-images.githubusercontent.com/195327/117794461-8cd61b80-b24d-11eb-9812-276bce9cdc61.gif)

ESPHome configuration is visible in the top right.

This change/addition does require changes to Home Assistant itself as well. So this will take some time in order for everything to update and process the changes.

I'll start opening up PRs for code reviewing slowly.

**Comment by rradar** [comment]
@mikosoft83 support for attributes is now present
