### ISSUE TITLE
H-Bridge Light Color Tone/Temperature

### ISSUE THREAD

**Issue by OvCa77** [esphome/feature-requests#1113]
**Describe the problem you have/What new integration you would like**

H-Bridge Light Color Tone/Temperature
**Please describe your use case for this integration and alternatives you've tried:**

I would like to propose new integration/modification of existing module, which will allow to change color temperature, for light such as Arilux ceiling light, which uses two channels, one to control brightness, other to set temperature of white light. https://esphome.io/components/light/hbridge.html
**Additional context**

**Comment by jesserockz** [comment]
https://github.com/ssieb/custom_components/tree/master/cwww2

**Comment by nagyrobi** [comment]
Implemented https://esphome.io/components/light/cwww.html
