### ISSUE TITLE
expect ModbusDevice support specified uart_id

### ISSUE THREAD

**Issue by bestlong** [esphome/feature-requests#1117]
**Describe the problem you have/What new integration you would like**

when multiple uart, ModbusDevice config can manually specify uart_id.

**Please describe your use case for this integration and alternatives you've tried:**

use ESP32 and two or three PZEM004Tv3.0 device.

PZEM004Tv3.0 use TTL RS232, Modbus-RTU

pzem004t component not support PZEM004Tv3.0 device, use pzemac component is work. But only one device can be connected.

**Additional context**

**Comment by Gio-dot** [comment]
> **Describe the problem you have/What new integration you would like**
> 
> when multiple uart, ModbusDevice config can manually specify uart_id.
> 
> **Please describe your use case for this integration and alternatives you've tried:**
> 
> use ESP32 and two or three PZEM004Tv3.0 device.
> 
> PZEM004Tv3.0 use TTL RS232, Modbus-RTU
> 
> pzem004t component not support PZEM004Tv3.0 device, use pzemac component is work. But only one device can be connected.
> 
> **Additional context**

It is already supported. Here an example: 
https://community.home-assistant.io/t/how-to-use-pzem004t-energy-monitor-with-esphome/107083/54?u=gt4020

**Comment by bestlong** [comment]
Thank @Gio-dot 

https://community.home-assistant.io/t/how-to-use-pzem004t-energy-monitor-with-esphome/107083/106

I see this part

```
modbus:
  id: mbus
  uart_id: ubus
  
...
sensor:
  - platform: pzemac
    address: 1
    modbus_id: mbus
...
```
