### ISSUE TITLE
ESP32 CAN peripheral support

### ISSUE THREAD

**Issue by rene-dev** [esphome/feature-requests#1121]
**Describe the problem you have/What new integration you would like**

esphome has can bus support, but currently only using the MCP2515.
https://esphome.io/components/canbus.html
but the esp32 has an internal **CAN** Controller, I cant imagine it would be hard to support.
esp32 can documentation:
https://docs.espressif.com/projects/esp-idf/en/v4.1/api-reference/peripherals/can.html

**Please describe your use case for this integration and alternatives you've tried:**

Bosch gas heaters use a can bus for comunication. workaround is to use the MCP2515.

**Additional context**

**Comment by mrbubble62** [comment]
this may help 
https://github.com/ThomasBarth/ESP32-CAN-Driver

**Comment by mckay6842** [comment]
+1
