### ISSUE TITLE
Custom effects for addressable LEDs

### ISSUE THREAD

**Issue by jansauer** [esphome/feature-requests#1124]
**Describe the problem you have/What new integration you would like**
I would like to be able to write custom light effects that control individual addressable LEDs of a FastLED Light component. 

**Please describe your use case for this integration and alternatives you've tried:**
I am trying to build a LED GyverLamp with a 16x16 Matrix inside. For this a want to write a GyverLamp like effect that operates on individual LEDs of the FastLED Light.

My first impression was that this should be possible via a [lambda effect](https://esphome.io/components/light/index.html#lambda-effect). But it looks like the `light.addressable_set` action can not be used in lambdas (No note in the docs on how the action can be expressed in lambdas). And i did not find any other way to address individual LEDs in a lambda.

I also looked into how the current effects are implemented in the hope that it may be possible to include custom c file (`esphome: includes: my_effect.h`). But [effects.py](https://github.com/esphome/esphome/blob/dev/esphome/components/light/effects.py) is written in python and it is unclear to me how `@register_addressable_effect` can be called from c code.

**Additional context**

**Comment by jesserockz** [comment]
You missed seeing the [addressable lambda effect](https://esphome.io/components/light/index.html#addressable-lambda-effect)
