### ISSUE TITLE
Docker container: add "vi" editor

### ISSUE THREAD

**Issue by chemelli74** [esphome/feature-requests#1137]
**Describe the problem you have/What new integration you would like**

Consider adding `vi` to docker image. 
Will not take much space and would be handy to edit yaml file directly there.

**Please describe your use case for this integration and alternatives you've tried:**

Edit the file on the host and share the folder with the container

**Comment by SenexCrenshaw** [comment]
I agree!

**Comment by dougle03** [comment]
Vi or Nano pls

**Comment by legomind** [comment]
If you want to use vi in docker, I would suggest using a shared volume and the vim docker image. 

Otherwise, mount a host folder inside the esphome image, and use vim on your host machine directly.

**Comment by chemelli74** [comment]
Why not considering including it by default in esphome container ?

Simone

**Comment by legomind** [comment]
Because not only does it go against the container philosophy, there are some of us who do not wish to download larger images with each update.

**Comment by chemelli74** [comment]
It's a pity but I got your point.

Closing
