### ISSUE TITLE
Webserver log display should display the time the message was received

### ISSUE THREAD

**Issue by klaernie** [esphome/feature-requests#1140]
**Describe the problem you have/What new integration you would like**

It would be nice, if the debug log on the integrated webserver would show the date and time when each log message was received.

**Please describe your use case for this integration and alternatives you've tried:**

I am debugging problems with my wifi, trying to find out what the problems are.
The debug log nicely works, while the esp is still connected to the wifi, and for example shows me that the connection was lost to the mqtt server.
Now to correlate this in the mqtt server logs and anywhere else I need to see at which time the problem occured.
The  `esphome foo.yaml logs` (which run via mqtt) adds a timestamp, so it can be used for all problems where the connection to mqtt is not lost. But in my case the connection to mqtt might be the problem, so the issues never get logged using the cli.

**Additional context**

I considered to implement this in [esphome-docs/_static/webserver-v1.js](https://github.com/esphome/esphome-docs/blob/current/_static/webserver-v1.js), but I am unsure if using moment.js would be appropriate and how to regenerate the minified version.

**Comment by glmnet** [comment]
There is not a project setup to generate the minified 

You can use just online minifier
