### ISSUE TITLE
Using decrypt_xiaomi_payload on ESP32 

### ISSUE THREAD

**Issue by tonypascal** [esphome/feature-requests#1148]
**Describe the problem you have/What new integration you would like**

I try to read data of CGG1 temperature and humidity sensors with a ESP32 using arduino programming IDE. I cannot decrypt the encrypted data.

**Please describe your use case for this integration and alternatives you've tried:**

I would like to use the esphome decrypting function on ESP32 / Arduino IDE to decrypt the CGG1 dataflow so that I can send the data to a data storage

I guess this it the decrypt_xiaomi_payload function, but I can't make it work...

**Additional context**

I already got the bindkey from the Android app method and I receive data using esp32 board through Bluetooth, printing them on serial port

**Comment by nagyrobi** [comment]
Done: https://esphome.io/components/sensor/xiaomi_ble.html#cgg1
