### ISSUE TITLE
Update the PCA9685-Arduino

### ISSUE THREAD

**Issue by GraafG** [esphome/feature-requests#1150]
**Describe the problem you have/What new integration you would like**
I would like the updated code from:
https://github.com/NachtRaveVL/PCA9685-Arduino
Be udpated in ESPHome

**Please describe your use case for this integration and alternatives you've tried:**
Some small bugfixes in the repo

**Additional context**

**Comment by nagyrobi** [comment]
Please check if this is still an issue. If it is, file an issue instead, not a feature request. Thank you.
