### ISSUE TITLE
Getting response from http_request

### ISSUE THREAD

**Issue by karolzlot** [esphome/feature-requests#1157]
**Describe the problem you have/What new integration you would like**

I have button and LED.
When button is clicked, http_request is made.

I want to have feedback if this action is successful. When this request is successful, the LED should turn on for 1 sec.

So I need to be able to write (pseudocode):

```
If ( request_response == "finished successfully")
then:  ...

```
or version with checking just http status code:

```
If ( request_status_code == 200)
then:  ...
```

Any of those versions would satisfy me needs. I just need to have feedback to instantly know that action was successful.

AFAIK it is not possible to be done currently.

**Please describe your use case for this integration and alternatives you've tried:**

Included above.

**Additional context**

**Comment by andreashergert1984** [comment]
HI, there is already something like that im implemented (just not documented). 
there is an "on_response" option where the response code gets in as a parameter.

**Comment by glmnet** [comment]
here are the docs, it's beta and dev https://beta.esphome.io/components/http_request.html#on-response-trigger

**Comment by f403** [comment]
Obtaining a response body would be also nice

**Comment by nagyrobi** [comment]
See https://github.com/esphome/esphome-docs/pull/1914
