### ISSUE TITLE
New 2.13 inch epaper model type: b74 (GDEM0213B74)

### ISSUE THREAD

**Issue by matikij** [esphome/feature-requests#1167]
**Describe the problem you have/What new integration you would like**

There is a new model basting 4-level grayscale https://www.good-display.com/product/375.html
there are some code samples here:

https://www.good-display.com/companyfile/555.html
https://www.good-display.com/companyfile/556.html

Nothing in GxEPD2 library repo yet https://github.com/ZinggJM/GxEPD2/tree/master/src/epd .

Would be cool if this would be supported at some point.

Didn't delete any bolierplate text from this issue.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by nikito7** [comment]
https://github.com/lewisxhe/GxEPD/tree/master/src/GxGDEM0213B74

**Comment by nikito7** [comment]
It's a new type. No lut.

It will not be easy...

Advanced coder needed

**Comment by osresearch** [comment]
![image](https://user-images.githubusercontent.com/3068843/121320904-dfb6f780-c90d-11eb-8953-d38a42306ba6.png)

Preliminary support for using the b74 in monochrome: https://github.com/esphome/esphome/pull/1869

**Comment by nikito7** [comment]
Board is new too: 2.3.1

**Comment by OttoWinter** [comment]
Closed via https://github.com/esphome/esphome/pull/1869
