### ISSUE TITLE
Add Heltec Wifi Kit 32 V2

### ISSUE THREAD

**Issue by Noxmiles** [esphome/feature-requests#1173]
**Describe the problem you have/What new integration you would like**
Since 2019 there is Version 2 of the Heltec Wifi Kit 32. This new Version has some differences, which should be updated in ESPHome:
- 4MB (32M-bits) FLASH upgrade to 8MB (64M-bits) FLASH
- Different Pinout: See https://heltec-automation-docs.readthedocs.io/en/latest/esp32+arduino/wifi_kit_32/hardware_update_log.html for the differences

**Please describe your use case for this integration and alternatives you've tried:**
Especially with 8MB the limit for the firmware size is doubled.

**Additional context**
There is also V2.1, but the chances does not affect ESPHome

**Comment by richardklingler** [comment]
The changes in the pinout doesn't matter to ESPHome as you specify the GPIOs to use...

Also for ESP32 flash size doesn't matter...no ESP32 board has a flash size defined, only ESP8266 boards...

**Comment by nagyrobi** [comment]
Closing as the answer above is clear.
