### ISSUE TITLE
When is active captive_portal it is impossible redirect to static web server

### ISSUE THREAD

**Issue by emilioaray-dev** [esphome/feature-requests#1182]
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

When is active (captive portal) it is impossible to go to the static web server in case of impediment to be part of a network.

**Additional context**

It should add an action or skip button and redirect to web server.

**Comment by jhenkens** [comment]
I hit this too. I'm looking at making changes to the webserver components to allow this.

**Comment by nagyrobi** [comment]
Duplicate of https://github.com/esphome/feature-requests/issues/1334
