### ISSUE TITLE
Support for persistent state (across reboot/reflash) - Keeloq

### ISSUE THREAD

**Issue by RoganDawes** [esphome/feature-requests#1189]
**Describe the problem you have/What new integration you would like**
I am planning to build a Keeloq transmitter/receiver integration. This relies on a shared knowledge of a sequence number per transmitter to prevent replay attacks. I want to be able to store the observed sequence numbers on the ESP32/ESP8266, and increment them as new transmissions occur.

**Please describe your use case for this integration and alternatives you've tried:**
Keeloq transmitters could be used as a (more) secure method to trigger ESPHome actions (or Home Assistant actions). There are two main use cases, depending on whether the action will be offline-capable or online-only.

In the first case, ESPHome must be able to validate the sequence number, even in the absence of an upstream connection to Home Assistant or some other controller. To do this, it must have a local copy of the last sequence number used for each transmitter.

In the second case, the task of validating (and storing/updating) the sequence number can be offloaded to a Home Assistant integration, potentially allowing synchronisation of sequence numbers between geographically distant receivers. i.e. You could have a network of receivers all accepting and relaying signals.   
 
**Additional context**
So, it is the first use case above that should be addressed by this feature request.

 From what I have seen, ESPHome has no facility for persistent storage of large amounts of data (e.g. kilobytes), in a way that will survive power loss (i.e. no RTC memory) or being reflashed.

My thoughts are to reserve one or two pages at the end of the available flash for storage of log events. So long as the current and future firmwares are aware of the reservation, and don't erase the entire flash in the process of updating, this should be fine, I would think. The idea would then be to start with both pages erased, then write log entries (timestamp, serial number, sequence number, function) to a journal as transmissions are received. This should hopefully not require erasing of the flash page for each write (although not verified). When a sequence number needs to be validated, ESPHome would perform a binary search on the page to find the end of the journal, then work backwards to find the most recent journal entry for the designated serial number, before writing the next update to the end of the journal. When the page is full, ESPHome could then consolidate the journal, storing only the most recent event for each serial number to the start of the second page. Once successfully written, the first page could be erased. In this way, journal entries could alternate between pages, hopefully reducing wear on the flash. The active page would be obvious, based on which page actually has a log entry in the first position.

Initial sequence numbers can be provided as part of the receiver configuration, as a worst case scenario if the flash pages are erased. Yaml configuration would remain the authoritative record of which receivers are defined for offline use, and which actions are associated with each button. If there is a journal entry for a transmitter, but no entry for it in the yaml configuration, that transmitter would not be accepted for offline use, but only relayed to a central controller.

**Comment by Bascht74** [comment]
@RoganDawes any progress on building this? I am looking into this as well now…

**Comment by RoganDawes** [comment]
> @RoganDawes any progress on building this? I am looking into this as well now…

Unfortunately not. The STM32-based hardware I have actually has an EEPROM, which is/would be a better solution to this problem than trying to prevent some of the uC flash being overwritten during programming.

I still haven't got around to actually implementing this, though, although I have designed how the 1 MB EEPROM flash can be divided up into space for remotes and space for events, including exactly how many bytes are required per record.

I'm curious to know whether you are also needing Keeloq support, or is this for something else?

**Comment by Bascht74** [comment]
Hi @RoganDawes, 

> I'm curious to know whether you are also needing Keeloq support, or is this for something else?

Yes, I have some Jarolift motors in my awning that I want to control via Keeloq. 
I found the KeeLoq NLF LSB and MSB for the remotes. So far I used Tasmota for that, but as I am switching to ESPHOME I am looking for a solution there.

You wrote:
> Unfortunately not. The STM32-based hardware I have actually has an EEPROM, which is/would be a better solution to this
> problem than trying to prevent some of the uC flash being overwritten during programming.

That is not true. As of a solution for ESPHOME with ESP32 you can use global variables that can be used in lambda: 
https://esphome.io/guides/automations.html#global-variable

like this: 
 ```
globals:
   - id: keeloq_counter
     type: int
     restore_value: yes # That is the key :-)
     initial_value: '0'
```

- type (Required, string): The C++ type of the global variable, for example bool (for true/false), int (for integers), float (for decimal numbers), int[50] for an array of 50 integers, etc.
- restore_value (Optional, boolean): Whether to try to restore the state on boot up. 
- initial_value (Optional, string): The value with which to initialize this variable if the state can not be restored or if state restoration is not enabled. This needs to be wrapped in quotes! Defaults to the C++ default value for this type (for example 0 for integers).

Than you can use in lambda:
```
    - lambda: |-
        id(keeloq_counter) += 1;
        ESP_LOGD(TAG, "Global value is: %d", id(keeloq_counter));
```

A guy here uses that: 
https://community.home-assistant.io/t/cumulative-counter-is-possible/344008/4

He said: ... Counter still [works] even after flashing with a new version os firmware/program.
So I think that is what you are looking for...

As of...
https://newscrewdriver.com/2022/03/25/flash-memory-wear-effects-of-esphome-recovery-esp8266-vs-esp32/

... it is save to use it even with frequent changes... 
**... So no special STM32-EEPROM needed AND no need to implement a "storing mechanism" for the counter.**

That way you can even use several global variables or every interesting variable (e.g. NLF LSB and MSB as well as the remote serial). 

These could all be set persistently via Home Assistant services at runtime, see: 
https://esphome.io/components/api.html#user-defined-services

- or - 

Another way would be via `input number` and e.g. the web interface or mqtt:

```
globals:
   - id: global_serial
     type: int
     restore_value: yes # That is the key :-)

number:
  - platform: template
     name: serial
     on_value:
      then:
        - lambda: id(global_serial) = id(serial).state 
```

see:
https://esphome.io/components/number/index.html
and https://esphome.io/guides/automations.html#global-variable

take a look at this for flash wearing of the ESP32: 
https://community.home-assistant.io/t/how-to-update-a-globals-variable/338882
> While I see that ESP32 has its own concept of RTC, looking in ESPHome source code for ESP32 variant of preferences.cpp I see that it used a different mechanism called NVS. Non-Volatile Storage library is tailored for storing small key-value pairs in flash memory, and was written to minimize wear . This is great. Even better, the API also leaves the door open for different storage mechanisms in future hardware revisions, possibly something with better write durability. [...] **From this, I conclude that ESPHome projects that require restoring states through reboots events are better off running on an ESP32 and its dedicated NVS mechanism**.

Sebastian

**Comment by Bascht74** [comment]
so: 

> In the first case, ESPHome must be able to validate the sequence number, even in the absence of an upstream connection to Home Assistant or some other controller. To do this, it must have a local copy of the last sequence number used for each transmitter.
This can be done that way, even multiple ones it you want to implement it as the receiver...

> In the second case, the task of validating (and storing/updating) the sequence number can be offloaded to a Home Assistant integration, potentially allowing synchronisation of sequence numbers between geographically distant receivers. i.e. You could have a network of receivers all accepting and relaying signals.
This could be done with mqtt very easily and doesn't need any home assistant instance, as you can just listen to an mqtt topic and use that for changing the global variable. 
This way you could even use a single keeloq remote for multiple ESP32-receivers and synchronize them via the mqtt topic

that way you could act as remote and receiver at the same time, even on multiple locations in the house. So you could use ESPHOME e.g. as a cover (https://esphome.io/components/cover/template.html) and control the keeloq-covers via keeqlog messages and - as a bonus - you could receive and process the "real" remote messages and set the state of the cover accordingly ...

But this would be two tasks to solve.

Sebastian

**Comment by Bascht74** [comment]
Even with ESP8266 it seems to hold 100.000 write cycles. you have to set 

```
esphome:
[...]
esp8266_restore_from_flash: true 

```

than you could use a hacked Sonoff RF Brücke R2 (15 Euros) for this: 
https://github.com/xoseperez/espurna/wiki/Hardware-Itead-Sonoff-RF-Bridge---Direct-Hack
https://community.home-assistant.io/t/new-sonoff-rf-bridge-board-need-flashing-help/344326

Seb

**Comment by RoganDawes** [comment]
That is all very interesting. I will have to look into this a bit more!

In my specific case, the radio is 403MHz, not 433MHz, and I have been unable to find any other readily available receivers or transmitters other than those made by this particular vendor. ie. not general purpose.

For those that have 433MHz devices, this may well be a very good solution. Store the sequence number for the next transmission in a global variable, and be done with it.

Note: while I have so far implemented a Keeloq decoder for the remote_base component (https://github.com/RoganDawes/esphome/blob/keeloq/esphome/components/remote_base/keeloq_protocol.cpp), I have not yet done the same for the encoder. It really should not be terribly difficult to do so, though!
