### ISSUE TITLE
Include WLED effect system/frontend

### ISSUE THREAD

**Issue by poelzi** [esphome/feature-requests#1190]
**Describe the problem you have/What new integration you would like**

I really like esphome, but as soon as I have a adressable led strip to controll, I end up with a wled next to it, because the effect system is just so much more convinient and flexible. Changing some parameters in the web ui and tweaking until it just looks perfect and saving the result in a preset is just so much more convinient then changeing parameters in a yaml file, recompiling and flashing a firmware.
I even sometimes have non technical friends over and  open them the browser and they create new presets and have a lot of fun with this.

But as soon as something more custom is required, like extra sensors, button or even controlling different stripes with one controller that have nothing to do with each other, wled is clunky and usermods are quite hacky. 

A parameter on the addressable_light type will include the wled effect system on that stip.
You will have a webui to control exactly that stip, different urls for each stip, loading the same web frontend interface.
It should be a reduced wled interface, no configuration or info, but the color settings with paletts, effects settings, dynamic segment configuration and presets.

I imaging wled with some refactoring could be modulized and share the same code with esphome. This way, both sides could benefit from this. WLED for the stand alone and simple case, and esphome for more advanced configurations wtih extra modules while still having the effect system

**Please describe your use case for this integration and alternatives you've tried:**

Describing addressable led effects with text files is cumbersome. Very few effects, no color palettes, no dynamic changes.

**Additional context**

**Comment by oxan** [comment]
I expect it'd be incredibly unlikely that WLED will ever be able to be merged into a ESPHome firmware.

However, ESPHome supports the [WLED effect protocol](https://esphome.io/components/light/index.html#wled-effect), so you can have one node running WLED control multiple different light strips running ESPHome.
