### ISSUE TITLE
Dynamic DNS with EasyDDNS

### ISSUE THREAD

**Issue by ibarbech** [esphome/feature-requests#1192]
**Describe the problem you have/What new integration you would like**

I would like the ESP device itself to be able to update the public IP of my router, to be able to do Dynamic DNS.

**Please describe your use case for this integration and alternatives you've tried:**

I have a server in my house and I want a camera (ESP32-cam) that I have in my second house to be able to connect through dynamic DNS.
I have found the EasyDDNS library (https://github.com/ayushsharma82/EasyDDNS) and with the arduino IDE it has worked perfectly with dynu. But I have not located an integration in ESPHOME

**Additional context**

**Comment by jesserockz** [comment]
See esphome/esphome#1711 for comments
