### ISSUE TITLE
Serial Flashing directy from browser

### ISSUE THREAD

**Issue by lhartmann** [esphome/feature-requests#1194]
**Describe the problem you have/What new integration you would like**

<a href="https://web.dev/serial/">Browser support for hardware serial ports</a> has just been added to Google Chrome. This could prove a conveninent zero-install alternative to esphomeflasher/esptool.

**Please describe your use case for this integration and alternatives you've tried:**

OTA is awesaome, but the initial flash could be made more convenient (no python or dependencies to install).

**Additional context**

Could also be useful for ESP01-512kB modules, which are fiddly with OTA.

**Comment by mkaatman** [comment]
https://esphome.github.io/esp-web-tools/
