### ISSUE TITLE
GY-49 (MAX44009) I2C light sensor integration

### ISSUE THREAD

**Issue by a1laserboy** [esphome/feature-requests#1195]
**Describe the problem you have/What new integration you would like**

Add light sensor board GY-49 compatibility to esphome please

**Please describe your use case for this integration and alternatives you've tried:**

I've tried to use the existing 2 supported light sensors (TSL2561 & BH1750) to use my GY-49 but get crazy figures. 

**Additional context**

I'm using a D1mini and the node can see the device in the i2c address I set, so that's something. The device is used in this project that I'm trying to replicate in esphome to avoid mqtt: https://github.com/daromer2/TempHumLight-ESP01 here is the arduino library I think: https://www.arduino.cc/reference/en/libraries/max44009-library/ here is a wiki on the sensor as a whole: http://wiki.sunfounder.cc/index.php?title=Digital_Light_Intensity_Sensor_Module_(GY-49)

I've discussed this with Morris_B on your discord and it seems the best way would be to ask you directly to consider adding support. 

Thanks for a great thing!!!

**Comment by richardklingler** [comment]
Maxim lists this chip as obsolete and isn't selling it anymore...

Also Digikey has no MAX44009, only some bloody expensive eval kits....
so hard for developers adding support for it...no one wants to buy a kit for over US$ 120 (o;

**Comment by nagyrobi** [comment]
Implemented https://esphome.io/components/sensor/max44009.html
