### ISSUE TITLE
Improving PMSX003 component to include all sensor readings (Concentration Units (environmental) & Particles per 0.1L air

### ISSUE THREAD

**Issue by genestealer** [esphome/feature-requests#1201]
**Describe the problem you have/What new integration you would like**

Improving PMSX003 component to output all possible sensor readings.
Currently the available sensors are limited to PMx concentrations. 
However many of the sensors in that range, such as the PMSX003_TYPE_5003ST (PMSX5003ST), also output:
- Concentration Units (environmental)
- Particles per  0.1L air (Particles > 0.3um / 0.1L air, Particles > 0.5um / 0.1L air, Particles > 1.0um / 0.1L air)  etc.

This information is available in additional bytes of the incoming data stream and just needs to be captured in theget_16_bit_uint_(xx) [pmsx003.cpp](https://github.com/esphome/esphome/blob/5c86f332b269fd3e4bffcbdf3359a021419effdd/esphome/components/pmsx003/pmsx003.cpp)

Linked to a copy of the data sheet: [plantower-pms5003-manual_v2-3.pdf](https://cdn-shop.adafruit.com/product-files/3686/plantower-pms5003-manual_v2-3.pdf) which details the data stream.

Code example from adafruit: https://github.com/adafruit/Adafruit_PM25AQI

**Please describe your use case for this integration and alternatives you've tried:**

Unable captured additional data streams already present.

**Additional context**

component: sensor.psmx003
integration: psmx003

**Comment by genestealer** [comment]
Looks like someone is looking into this already: https://github.com/esphome/esphome/pull/1694

**Comment by warthog9** [comment]
Yeah, this has been chugging along for me for a bit without any issue, happy to answer any more questions or fix things if they are needed

**Comment by genestealer** [comment]
Integrated via https://github.com/esphome/esphome/pull/1694
