### ISSUE TITLE
Add esp32thing_plus board

### ISSUE THREAD

**Issue by Aulos** [esphome/feature-requests#1205]
**Describe the problem you have/What new integration you would like**

Please add Sparkfun's ESP32 Think Plus, which is described here: https://docs.platformio.org/en/latest/boards/espressif32/esp32thing_plus.html

**Please describe your use case for this integration and alternatives you've tried:**

For now I am using basic Sparkfun ESP32 Thing board which seems to work fine

**Additional context**

**Comment by nagyrobi** [comment]
Works with Sparkfun ESP32.
