### ISSUE TITLE
Nextion reported variable name invalid!

### ISSUE THREAD

**Issue by OptimusGREEN** [esphome/feature-requests#1211]
**Describe the problem you have/What new integration you would like**
Nextion reported variable name invalid!
It would be great if the variable name was printed in this error output as i cant find the issue anywhere

**Please describe your use case for this integration and alternatives you've tried:**
simpler debugging

**Additional context**

**Comment by nagyrobi** [comment]
Please contact us via Discord channel for quick responses.
