### ISSUE TITLE
Duplicate an existing configuration

### ISSUE THREAD

**Issue by Korte68** [esphome/feature-requests#1212]
**Describe the problem you have/What new integration you would like**
It would be great if we can easily duplicate an existing configuration.

**Please describe your use case for this integration and alternatives you've tried:**
We have to set the configuration from scratch.

**Additional context**

**Comment by nagyrobi** [comment]
Can be easily done by going to `esphome` configuration folder and copying in-place the existing configuration yaml file to a new name. It will be duplicated and the Dashboard will immediately pick it up.
