### ISSUE TITLE
Set a template yaml with the default configuration

### ISSUE THREAD

**Issue by Korte68** [esphome/feature-requests#1213]
**Describe the problem you have/What new integration you would like**
It would be great if we can define a template configuration with predefined code.
For example Wifi SSID, password, some sensor, which we usually wants to add to every eső modul. 

**Please describe your use case for this integration and alternatives you've tried:**
have an external file with this, and CTRL-C CTRL-V

**Additional context**

**Comment by oxan** [comment]
This should already be possible using [includes and packages](https://esphome.io/guides/configuration-types.html#packages).
