### ISSUE TITLE
IR Remote Climate Panasonic

### ISSUE THREAD

**Issue by markusg1234** [esphome/feature-requests#1218]
**Describe the problem you have/What new integration you would like**
Please add support receiver platform for Panasonic in IR Remote Climate

**Please describe your use case for this integration and alternatives you've tried:**
Not supported in current version

**Additional context**

**Comment by nagyrobi** [comment]
Implemented in https://esphome.io/components/climate/climate_ir.html, multiple Panasonic protocols.
