### ISSUE TITLE
Merge component settings when using include

### ISSUE THREAD

**Issue by apeeters** [esphome/feature-requests#123]
**Describe the problem you have/What new integration you would like**
Currently when using yaml includes, the list of components (sensor, switch,...) defined in the included file is overwritten in the including file. This makes it hard/impossible to have a common set of sensors shared across esphome instances.

**Please describe your use case for this integration and alternatives you've tried:**
I would like to include a common set of sensors, for example wifi_signal, version, ip_address without having to duplicate this in multiple yaml configurations.

**Additional context**

**Comment by OttoWinter** [comment]
That is a YAML limitation, and esphome can't solve that because it follows the yaml spec.

The way to work around that is to use the `!include_dir_list` directive.
