### ISSUE TITLE
Support Yeelight Wireless Switch S1 - YLAI003

### ISSUE THREAD

**Issue by andrewjswan** [esphome/feature-requests#1230]
**Describe the problem you have/What new integration you would like**
**Yeelight Wireless Switch S1 - YLAI003** - https://aliexpress.ru/item/1005001552119268.html
The button has three actions, **press, double press, long press**.
There is also a battery charge value.
When i add it to MiHome, a bindkey was generated.

**Please describe your use case for this integration and alternatives you've tried:**

Manage smart home devices, transfer clicks to the HA.

**Additional context**

Already support by [BLE-monitor](https://github.com/custom-components/ble_monitor/pull/274)

**Comment by andrewjswan** [comment]
More info: https://github.com/custom-components/ble_monitor/issues/268

**Comment by dentra** [comment]
You could use it as custom component: https://github.com/dentra/esphome-components/tree/master/components/miot_ylyk01yl

**Comment by andrewjswan** [comment]
Thanks, work!
