### ISSUE TITLE
Light component: color from UI color wheel for custom effects

### ISSUE THREAD

**Issue by Jojo-A** [esphome/feature-requests#1234]
**Describe the problem you have/What new integration you would like**

Am I forced to define the color (for a custem effect like strobe for example) strictly in my effect config, or is it somehow possible to select the desired color from the color wheel in Homeassistant? This is already the case for the flicker effect: here you just select the color from the wheel and it flickers with the defined timing parameters...

Thanks and greeting!

**Please describe your use case for this integration and alternatives you've tried:**

I have normal RGBW LED strips here, configured ESPhome PWM outputs accordingly, integrated in Home Assistant -> works perfect.

**Additional context**

I have started to write very basic custom effects like a (single color) strobe or a (single color) fade-in/out. I pre-defined the colors for each effect in its corresponding config.

**Comment by nagyrobi** [comment]
Please ask direct questions in Discord channel.
