### ISSUE TITLE
Option to have Home Assistant integration remove unavailable entities.

### ISSUE THREAD

**Issue by lanrat** [esphome/feature-requests#1241]
**Describe the problem you have/What new integration you would like**

When a component is removed from ESPHome (say you update the YAML and remove a sensor) having an option to remove the entity from Home Assistant would be nice.

**Please describe your use case for this integration and alternatives you've tried:**

When removing sensors/entities from ESPHome, they are marked as "Unavailable" in Home Assistant. They can individually be disabled, but this is sometimes a pain. Additionally, if some entities or sensors are moved from one ESPHome node to another, the old entities stick around in Home Assistant with no way to remove them and the new ones get names like `switch.light_2` where `switch.light` is always "Unavailable" and can not be removed.

**Additional context**
One way around this is to delete the entire ESPHome node from Home assistant and re-add it. However this has the downside that all history and other metadata for the device is also lost.

One potential implementation could be to mimic the removing and re-adding of the node in Home Assistant, but somehow keep the history.

**Comment by DOWIT-JoelFrojmowicz** [comment]
+1

**Comment by nagyrobi** [comment]
This works now.
