### ISSUE TITLE
Update all devices with single button

### ISSUE THREAD

**Issue by atomhirsch** [esphome/feature-requests#125]
**Describe the problem you have/What new integration you would like**

The more devices you have, the longer it takes to keep everyone up to date. So far you have to update every single device. Then wait until it is updated and then update the next one.
I would love to have an button to start updating all devices with a single press.
Each update can still run one after the other but as soon as an update is finished the next device will be updated.

**Please describe your use case for this integration and alternatives you've tried:**

The advantage would be the time saving because you don't have to start an update over and over again.

**Additional context**

**Comment by OttoWinter** [comment]
I do not find this a good idea.

1. Even though esphome is supposed to be stable, there's always the possibility that something does not work / a bug was introduced. Updating all esphome devices at once seems like a bad idea.

2. The dashboard user interface is supposed to be minimal, I don't see where a new upload all button would fit there.

3. The edge cases are impossible to handle correctly for all users. For example, what if one device is offline? What if upload/compile fails? Should it just continue on as if nothing happened and potentially leave the user *thinking* the node has been updated when in reality it is not? Bad UX

If you really want upload all functionality, write a quick bash script that does it for you. It's not that hard.
