### ISSUE TITLE
xiaomi_ble: add support to ble door locks, sure it's possible

### ISSUE THREAD

**Issue by xcray** [esphome/feature-requests#1252]
**Describe the problem you have/What new integration you would like**

add support to all the xiaomi eco ble door locks, including xiaomi/mijia, zelkova, loock, etc.
xiaomi eco ble door locks use the same the same encryption algorithm as LYWSD03MMC, and now there are at least 2 methods to get the beaconkey: a kind of ble gateway (chuangmi xiaobai ir remote) will print out it on the TTL port, and it can also be found in the log of the multi-mode gw ( Xiaomi Gateway 3 (ZNDMWG03LM and ZNDMWG02LM, with telnet enabled).
so, it's possible to support them without big difficulty.
**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

I had a successful try with modifications on the codes of xiaomi_lywsd03mmc and xiaomi_ble.

key point: door locks transmit data via the manufacturer advertisement, without mac address, while lywsd03mmc (and other ble sub-devices) transmit via service adv with mac.

the working code could be found here:
xcray/xiaomi_ble_doorlocks: modified esphome code of xiaomi_lywsd03mmc & xiaomi_ble to support the door lock brand Zelkova (github.com)

and I think it could be better when merged into the future releases, and text sensor will be a better result with the data of pdid/eid/edata.

**Comment by nagyrobi** [comment]
Please contract the dev team on Discord for questions how to prepare a custom component or a PR to implement this.
