### ISSUE TITLE
Changelog link in the Update pending tile (HA Supervisor Add-on info screen)

### ISSUE THREAD

**Issue by marcelkous** [esphome/feature-requests#1265]
**Describe the problem you have/What new integration you would like**

Is it possible to add a link to the changelog in the "Update pending"tile?

![image](https://user-images.githubusercontent.com/61436181/122452634-c109ce00-cfa9-11eb-8a84-991bb8d228c9.png)

**Please describe your use case for this integration and alternatives you've tried:**

It is easier to find the changelog if you are taken directly to the web page.

**Additional context**

New and inexperienced users can find the information much easier. 
(The link in the info page isn't working either, https://github.com/esphome/issues/issues/2150)
Thanks.

**Comment by jesserockz** [comment]
This has been added with esphome/hassio#33
