### ISSUE TITLE
XPT2046 multiples pages?

### ISSUE THREAD

**Issue by Electronlibre2012** [esphome/feature-requests#1269]
**Describe the problem you have/What new integration you would like**

Hello, i know i am dreaming...but, is there a way to have multiples pages detection with binary_sensor.xpt2046, in this way, different pages in display, i can make different action button with touch screen : like page 1, 2, 3...i would have touchscreen page 1,2 ,3...
Dont know if i am clear, english is not my native language, sorry.

thanks
**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by nagyrobi** [comment]
Duplicate for https://github.com/esphome/feature-requests/issues/1480
(let all displays support pages!)
