### ISSUE TITLE
Support: Grove - AHT20 I2C Industrial Grade Temperature&Humidity Sensor

### ISSUE THREAD

**Issue by sj3fk3** [esphome/feature-requests#1273]
**Describe the problem you have/What new integration you would like**
I would like to use the (Grove)  AHT20 I2C Industrial Grade Temperature&Humidity Sensor with ESPHome

**Please describe your use case for this integration and alternatives you've tried:**
It's a very accurate temp/hum sensor that uses I2C

**Additional context**
To be honest I think the grove ecosystem fits nicely into the ESPHome concept. They have a standardised plug, it works on ESP32's, Pi's and NodeMCU's (M5Stack also uses it).

https://wiki.seeedstudio.com/Grove-AHT20-I2C-Industrial-Grade-Temperature%26Humidity-Sensor/

https://github.com/Seeed-Studio/Seeed_Arduino_AHT20/archive/master.zip

**Comment by jcastro** [comment]
Is not working with https://esphome.io/components/sensor/aht10.html ? Just curious as I also want to buy this sensor!

**Comment by sj3fk3** [comment]
OMG I am so embarrassed! It works with the aht10 integration. Going to close this one.. No one has seen it right?

**Comment by jcastro** [comment]
NO ONE
NO ONE
NO ONE
NO ONE
