### ISSUE TITLE
PCA9555 16-bit I/O expander support

### ISSUE THREAD

**Issue by NdK73** [esphome/feature-requests#1275]
**Describe the problem you have/What new integration you would like**

I'd like to be able to handle PCA9555 like MCP23017.

**Please describe your use case for this integration and alternatives you've tried:**

I tried using MCP23017, but it costs more and does not guarantee output states during boot.

**Additional context**

I'd like to be able to install ESPHome on my DomoNode2 boards. Could a pull-request be useful?

**Comment by NdK73** [comment]
Still got no answer, so I wrote a custom device and made it available at https://github.com/NdK73/DomoNode21_for_ESPHome . ESPHome experts can probably simplify it quite a lot.

**Comment by nagyrobi** [comment]
Please feel free to submit it as a PR.
