### ISSUE TITLE
Bring back 'Auto Save'

### ISSUE THREAD

**Issue by 3ative** [esphome/feature-requests#1276]
**Describe the problem you have/What new integration you would like**

In the previous build (v1.18) when you clicked, what was then the "Compile' Button - now "Install", ESPHome would first 'Save' the code in the editor before taking action. 

![Capture](https://user-images.githubusercontent.com/51385971/123141086-e6865400-d44f-11eb-8c75-99ad66aca268.JPG)

- _It wold be great and a time saver to have this feature back._  👍

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by jesserockz** [comment]
This was a bug introduced with the dashboard changes, but has been fixed in v1.19.4

**Comment by 3ative** [comment]
@jesserockz 
💕That's great news, thanks for the info.

**Comment by 3ative** [comment]
Confirmed - Closing this thread.
Thanks to everyone involved. 👍
