### ISSUE TITLE
add option to add hosts in /etc/hosts from configuration tab

### ISSUE THREAD

**Issue by mohyat** [esphome/feature-requests#1285]
**Describe the problem you have/What new integration you would like**

When I add devices in ESPHome addon devices not resolved to ip localy, because of that I add manualy my devices
in /etc/hosts like:

my_device_001.local 192.168.0.1
my_devce_002.local  192.168.0.2
....

and I must do that on every restat of ESPHome add-on

I know I can assign static IP to my devices, but adding devices trough configuration tab will bi great feature for people
like my who like tu use DHCP for every device.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by nagyrobi** [comment]
No need to do that. You should ensure MDNS works in your environment, devices will be discovered/resolved automatically.
