### ISSUE TITLE
I need Edge-triggered Switch or Binary_Sensor 

### ISSUE THREAD

**Issue by erreipi** [esphome/feature-requests#1291]
**Describe the problem you have/What new integration you would like**

Currently, the switch or binary_sensor status updates during the on period or off period, it is called level-triggering.
But, I need to design an edge detection as the switch or binary_sensor status updates during (On -> Off) or (Off -> On) period.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

Ex)
Level-triggered Switch : on_turn_on:  or on_turn_off:
Edge-triggered Switch : on_posedge:  or on_negedge:

**Comment by bkaufx** [comment]
on_turn_on and on_turn_off are edge triggering.

**Comment by bkaufx** [comment]
Same with on_press and on_release for binary sensors.

**Comment by erreipi** [comment]
> on_turn_on and on_turn_off are edge triggering.
Oh, there is a way. Thank you !!!
