### ISSUE TITLE
Implement "select" entity from Home Assistant

### ISSUE THREAD

**Issue by jhenkens** [esphome/feature-requests#1297]
**Describe the problem you have/What new integration you would like**

HomeAssistant recently released [select entities](https://www.home-assistant.io/blog/2021/07/07/release-20217/#new-entity-select) which I think have some valid use cases in mapping ESP devices. 
**Please describe your use case for this integration and alternatives you've tried:**

Using multiple internal relays and exposing one "drop down" would works similarly to exposing the relays themselves and using interlock groups, except it is more explicit in its function once exposed to the outside world.

**Additional context**

**Comment by cliffordwhansen** [comment]
To add to the use cases:
- ESP Powered airfreshner, can expose a dropdown with pre set time intervals (9, 18, 32)
- Fan can return a drop down of speeds instead of a slider

**Comment by oxan** [comment]
This has landed in dev now, and will be released with v1.21.
