### ISSUE TITLE
When creating a new ESPHome device, provide the option to use password: !secret wifi_password

### ISSUE THREAD

**Issue by SteveRMann** [esphome/feature-requests#1299]
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

When creating a new ESPHome device, provide the option to use password: !secret wifi_password, or at least recognize the !secret keyword and don’t surround it with quotes.

**Comment by cliffordwhansen** [comment]
I would request both ssid and password as I have both stored in secrets.yaml

**Comment by cliffordwhansen** [comment]
Duplicate of: https://github.com/esphome/feature-requests/issues/1279
