### ISSUE TITLE
Character LCD Pages

### ISSUE THREAD

**Issue by LewisSpring** [esphome/feature-requests#1300]
**Describe the problem you have/What new integration you would like**

Support for pages for character LCDs
**Please describe your use case for this integration and alternatives you've tried:**

Being able to show multiple pages of information like a dashboard on a character LCD. Similar behaviour to current implementation of pages in other displays. 
**Additional context**

![image](https://user-images.githubusercontent.com/40576482/125369752-d558a500-e374-11eb-8e3d-8d00187173e1.jpeg)

**Comment by nagyrobi** [comment]
Duplicate for https://github.com/esphome/feature-requests/issues/1480
