### ISSUE TITLE
Show device IP address on dashboard

### ISSUE THREAD

**Issue by ronschaeffer** [esphome/feature-requests#132]
**Describe the problem you have/What new integration you would like**

Show the IP address of each device on the ESPHome dashboard and whether it is manual/static or assigned, for example similar to this mock-up:
![image](https://user-images.githubusercontent.com/12379923/54772947-73525f80-4c00-11e9-9862-d69ff0988105.png)

**Please describe your use case for this integration and alternatives you've tried:**

Showing the IP address would be useful for diagnosing problems. For example, I have accidentally assigned the same static IP to two devices due to config cut/paste errors. This would be a quick way to identify the issue without looking at the router device table.

**Additional context**

**Comment by noxhirsch** [comment]
+1

**Comment by OttoWinter** [comment]
No, the dashboard interface is intentionally minimal. I don't want to clutter it with info that _might_ be useful to some users.

Besides, there's a component for this already: `text_sensor.wifi_info`
