### ISSUE TITLE
Mac address info for ethernet component 

### ISSUE THREAD

**Issue by r312645** [esphome/feature-requests#1326]
**Describe the problem you have/What new integration you would like**
Can we get MAC information under the Ethernet component like WIFI?

`text_sensor:

platform: wifi_info
ip_address:
name: ESP IP Address
ssid:
name: ESP Connected SSID
bssid:
name: ESP Connected BSSID
mac_address:
name: ESP Mac Wifi Address`

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by nagyrobi** [comment]
https://github.com/esphome/feature-requests/issues/1683

**Comment by pepsonEL** [comment]
Any news about this ? Is any chance to show MAC for Ethernet module ?

**Comment by ptr727** [comment]
Looks like the ethernet component is not exposing the MAC address, so non trivial to get it.

MAC address is logged but not exposed:  
https://github.com/esphome/esphome/blob/dev/esphome/components/ethernet/ethernet_component.cpp#L504

```cpp
  uint8_t mac[6];
  err = esp_eth_ioctl(this->eth_handle_, ETH_CMD_G_MAC_ADDR, &mac);
  ESPHL_ERROR_CHECK(err, "ETH_CMD_G_MAC error");
  ESP_LOGCONFIG(TAG, "  MAC Address: %02X:%02X:%02X:%02X:%02X:%02X", mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
```

`eth_handle_` is private so not accessible from a lambda.
