### ISSUE TITLE
Support for Home Assistant's Input Integrations

### ISSUE THREAD

**Issue by rjmurph2241** [esphome/feature-requests#1333]
**Describe the problem you have/What new integration you would like**

Support for Home Assistant's number integration was recently added, which is awesome, but it would also be great if the other input options were also supported:  [Input Select](https://www.home-assistant.io/integrations/input_select/), [Input Boolean](https://www.home-assistant.io/integrations/input_boolean/), and (of most interest to me) [Input Datetime](https://www.home-assistant.io/integrations/input_datetime/)

**Please describe your use case for this integration and alternatives you've tried:**

I'm working on a smart alarm clock that I can set the alarm time in Home Assistant or on the clock itself.  And then use the alarm set time to run an automation to turn on lights when the alarm goes off.  I'm currently using two input numbers on the alarm clock but it would be nice to just have a single time on the front end.  There's probably a workaround with an input datetime in Home Assistant and homeassistant sensors and homeassitant.service actions with maybe some global variables on the ESP but it would be clunky.  

**Additional context**

#969 was recently closed when numbers was added.  It sounds like there's limitations on the Home Assistant side that prevent adding the other input methods at the moment but I wanted keep the request alive if Home Assistant ever added support.

**Comment by nagyrobi** [comment]
Most of this request is implemented since.
Also see this for a nice alarm clock project: https://github.com/mmakaay/esphome-alarm-clock
