### ISSUE TITLE
Seperate (or Merge) Captive Portal and WebSever functionalities

### ISSUE THREAD

**Issue by manju-rn** [esphome/feature-requests#1334]
**Describe the problem you have/What new integration you would like**

Currently when Captive Portal and Web Server are both provided in the YAML, Captive Portal overrides the WebServer, in the sense that when there is NO WIFI or API connectivity, the Captive Portal is activated and uses the same page & port # as that of the Web Server.  So even if I have local controls (say buttons) in esp, they cannot be seen since Captive Portal page takes over and one needs to provide either the WIFI creds or upload a new firmware.  The solution could be either:
1.  Separate Captive Portal and Web Server ports so that both could be used concurrently
2.  Merge both the functionalities, like the Web Server page should always display the components and the logs as usual but the Captive portal options is somewhere in the start, end of even small iframe at the side

**Please describe your use case for this integration and alternatives you've tried:**

Sometimes ESP just fails to connect to API or WIFI or the router is turned off. Since Captive portal runs a hot spot, one should still be able to connect directly to that hot spot and use the esp's Web server to control the local components (& automations) that are hosted within that esp. For example:
1. An IR transmitter connected to ESP does not need a wifi and even if the wifi is gone, should be able to be activated just by going to web server and clicking a button.  
2. Same for any sensor which are connected directly to esp and just reporting the values. One should be able to view those numbers

**Additional context**

**Comment by emilioaray-dev** [comment]
Describe the problem you have/What new integration you would like

In my case. I have generated some modules for family and friends and it is annoying to have separate firmware.

In the case that people only want to view the device and not be part of a network, the AP mode is excellent.

However if you want to connect the device to a Wi-Fi network. they ned new firmware when activating the captive mode.
then stop displaying the webserver. Only the captive portal can be viewed.

Recommendation.
The captative portal must be a submodule of webserver.
This must be a button, which will redirect the user in case they decide to leave AP mode and connect to a network.
