### ISSUE TITLE
Sensor Components "PMSX003" ADD type "PMS5003S"，Please！！！

### ISSUE THREAD

**Issue by sexychina** [esphome/feature-requests#1336]
**Describe the problem you have/What new integration you would like**

PMS5003S is a laser dust formaldehyde temperature and humidity two-in-one sensor, but there is no temperature and humidity. Sensor Components "PMSX003" does not have a "PMS003S" type, so I cannot use the sensor.

**Please describe your use case for this integration and alternatives you've tried:**
I am using ESPhone+nodemcu+PMS5003s+DHT22 as a home air detector and connected to HA

**Additional context**

**Comment by nagyrobi** [comment]
Implemented: https://esphome.io/components/sensor/pmsx003.html?highlight=PMS5003S
