### ISSUE TITLE
Riemann Sum intergral

### ISSUE THREAD

**Issue by enablingpenguin** [esphome/feature-requests#1338]
**Describe the problem you have/What new integration you would like**

Would it be possible to add a Riemann sum integral component directly into esphome, pretty much doing what home assistant is doing this this integration but directly on the esphome?

**Please describe your use case for this integration and alternatives you've tried:**

Currently calculating watthrs in home assistant

**Additional context**

**Comment by enablingpenguin** [comment]
Forgot to link home assistant integration:
https://www.home-assistant.io/integrations/integration/

**Comment by OttoWinter** [comment]
See https://esphome.io/components/sensor/integration.html

**Comment by enablingpenguin** [comment]
> See https://esphome.io/components/sensor/integration.html

Thank you very much that will work, It does not appear when you search "Riemann" on esphome for any future searchers.
