### ISSUE TITLE
Total Daily Energy calculation for "spikey" devices like water boiler

### ISSUE THREAD

**Issue by seanomat** [esphome/feature-requests#1348]
**Describe the problem you have/What new integration you would like**

It would be great to have some alternative calculation methods for the total daily energy like the home assistant Riemann integration has.

**Please describe your use case for this integration and alternatives you've tried:**

The calculation for total daily energy fails with devices that use power in very short and high bursts, like water heaters. They typically heat only for a minute or less with about 2kW.
A 30 second burst of 2 kW results in a 2 kWh increase in total daily energy.

**Additional context**

**Comment by nuttytree** [comment]
This should be resolved by esphome/esphome#2163.
