### ISSUE TITLE
Set QoS for MQTT default state topic

### ISSUE THREAD

**Issue by stefanku** [esphome/feature-requests#1355]
**Describe the problem you have/What new integration you would like**

Setting QoS for MQTT messages is possible if you publish messages with the mqtt.publish-action. However, you can't set the QoS for the default state reports that are published. These messages seem to be published with QoS level 0.

**Please describe your use case for this integration and alternatives you've tried:**

It would probably be possible to write an automation that publishes information about the state of the component and define QoS there. That however requires some additional coding. Moreover, if ESPHome by default publishes information about the state of a component, then why not offer the possibility to set the QoS of those messages?

**Additional context**

Setting QoS is important if a ESPHome-based device operates at a location where WiFi coverage is subpar.

**Comment by shentharo** [comment]
i was thinking of using esphome, until i realized its qos0
