### ISSUE TITLE
ESPHome & LCD2004a

### ISSUE THREAD

**Issue by agamemnen** [esphome/feature-requests#1359]
**Describe the problem you have/What new integration you would like**
How do I display my unique characters on the 2004 display?
Is it possible to display characters with commands as on arduino?

For example:
lcd.print(char(127));

For example:
byte smile[8] =
{
B00010,
B00001,
B11001,
B00001,
B11001,
B00001,
B00010,
B00000,
};

If there are no such opportunities, please consider the possibility of introducing them.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**
Introduce the possibility of using functions similar to arduino for your symbols.
For example:
lcd.print(char(127));

**Comment by nagyrobi** [comment]
Implemented: https://esphome.io/components/display/lcd_display.html?highlight=lcd#user-defined-characters
