### ISSUE TITLE
Customize the priority of wifi networks

### ISSUE THREAD

**Issue by Lanfeng2017** [esphome/feature-requests#136]
**Describe the problem you have/What new integration you would like**

How to customize the priority of wifi but not follow the signal strengths when multiple networks are available? Does there exist any similar configuration or setup ? If not, could any developer add this feature into the next version ?

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by OttoWinter** [comment]
Please fill out the template. Specifically use cases.

**Comment by yozik04** [comment]
My use case would be:
Connect to a hidden network on a separate router if it is available, otherwise connect to main house SSID.
