### ISSUE TITLE
Passive BLE monitor integration (Xiaomi MiBeacon and Scale, Qingping, ATC, Kegtron and Thermoplus sensors)

### ISSUE THREAD

**Issue by kiwipaulrob** [esphome/feature-requests#1384]
**Describe the problem you have/What new integration you would like**
Passive BLE monitor integration in HA  (Xiaomi MiBeacon and Scale, Qingping, ATC, Kegtron and Thermoplus sensors) offers access to many useful sensors, but this integration requires a Raspberry Pi or similar setup and adding Bluetooth devices to your Home Assistant instance can be difficult.

I have a couple of ESP32’s set up using ESP Home which is great, but these instances do not support all the devices that are supported by the HACS integration.

How hard to get the same functionality?

**Please describe your use case for this integration and alternatives you've tried:**
Having access to all these bluetooth devices via 'satellite' ESP32 modules greatly extends range.

**Additional context**
Codebase in the HA add on looks stable so hopefully not to hard to add to ESPhome

**Comment by nagyrobi** [comment]
Please check the documentation for specific devices as many of this were implemented since.
