### ISSUE TITLE
Update all - limit to online devices

### ISSUE THREAD

**Issue by tortfeaser** [esphome/feature-requests#1385]
**Describe the problem you have/What new integration you would like**
I have a bunch of ESPHome entries in the Home Assistant add-on I don't currently use for devices that aren't online right now.

Can the 'Update All' entry in the three dots menu include an option to update only the devices that are online?

**Please describe your use case for this integration and alternatives you've tried:**

It's not useful to compile updates for devices that aren't being used.

**Comment by nagyrobi** [comment]
Duplicate for https://github.com/esphome/feature-requests/issues/1695
