### ISSUE TITLE
Second gas meter

### ISSUE THREAD

**Issue by peterjohan52** [esphome/feature-requests#1387]
**Describe the problem you have/What new integration you would like**

I got an error and the “slimme meter” gives no data.

Missing unit
[E][dsmr:138]: 0-1:24.2.1(700101010000W)(00000000)

**Please describe your use case for this integration and alternatives you've tried:**

Part of the telegram:

0-1:24.1.0(003)
0-1:96.1.0()
0-1:24.2.1(700101010000W)(00000000)
0-2:24.1.0(003)
0-2:96.1.0(4730303339303031383433313135303138)
0-2:24.2.1(210830122505S)(01501.449*m3)

**Additional context**

When I got a gasmeter, it won’t connect. Then they replaced the meter with another. Hé came as second meter in the telegram. But is not recognized in slimmemeter.

**Comment by LarsStegman** [comment]
Not sure if you still have this problem, but maybe you can use this solution: https://github.com/esphome/issues/issues/2517#issuecomment-1158830759
