### ISSUE TITLE
DSMR Gas is not working on channel 2

### ISSUE THREAD

**Issue by peterjohan52** [esphome/feature-requests#1394]
**Describe the problem you have/What new integration you would like**

You got an error, when the gasmeter is on channel 2 and channel 1 is in error.

**Please describe your use case for this integration and alternatives you've tried:**

Missing unit
[E][dsmr:138]: 0-1:24.2.1(700101010000W)(00000000)

Wrote this errormessage.

**Additional context**

this is the telegram.

0-1:24.1.0(003)
0-1:96.1.0()
0-1:24.2.1(700101010000W)(00000000)
0-2:24.1.0(003)
0-2:96.1.0(4730303339303031383433313135303138)
0-2:24.2.1(210830122505S)(01501.449*m3)

This is the error.

Missing unit
[E][dsmr:138]: 0-1:24.2.1(700101010000W)(00000000)

Thérè wil no data displayed, not even from the electricity.

**Comment by LarsStegman** [comment]
Fixed: https://esphome.io/components/sensor/dsmr.html?highlight=gas_mbus_id
