### ISSUE TITLE
Add support for ANT BMS

### ISSUE THREAD

**Issue by lucasimons** [esphome/feature-requests#1396]
**Describe the problem you have/What new integration you would like**

Add support for ANT BMS over UART or ble uart
**Please describe your use case for this integration and alternatives you've tried:**

Now i use a python script to read the data and send to mqtt on a rpi4
**Additional context**

https://github.com/juamiso/ANT_BMS
https://github.com/Sgw32/BMSCtl
https://github.com/Louisvdw/dbus-serialbattery/wiki/Driver-BMS-support
https://github.com/imval/AntBMS/blob/main/AntBMS.cpp

[ANT_communication_protocol_EN.1.pdf](https://github.com/esphome/feature-requests/files/7189474/ANT_communication_protocol_EN.1.pdf)

https://diysolarforum.com/threads/for-those-of-you-looking-to-monitor-your-ant-bms-with-pi3-via-bluetooth.6726/page-6

**Comment by SeByDocKy** [comment]
I got a custom sensor for the ANTBMS 2020 ... Unfortunatly they changed the protocol for the 2021 model :(

**Comment by lucasimons** [comment]
Can you explain to me how you did it? did you connect to the display port? I currently use a script and connect to the bms via bluetooth

**Comment by SeByDocKy** [comment]
Yes on the display port.... it's an UART ... so basic wiring, ANTBMS: (GND,TX,RX) <=> ESP32 : (GND,RX,TX)

**Comment by lucasimons** [comment]
Have you used esphome?  Do you also have the option to switch the mosfet?

**Comment by SeByDocKy** [comment]
Yes ESPhome with a custom sensor : https://drive.google.com/file/d/1dwPWgargfSiYi-KMFOFXDH9V1jTvhBTh/view?usp=sharing

You can play with it... Tuned for a 16S battery

**Comment by lucasimons** [comment]
thank you very much, how did you connect the cables? i.e. you only connected gnd to gnd, rx to tx (gpio01), tx to rx (gpio03)

**Comment by SeByDocKy** [comment]
right

**Comment by lucasimons** [comment]
How does it work when you connect the display cable to the esp, the bluetooth still works?

**Comment by lumiror** [comment]
> Áno ESPhome s vlastným senzorom: https://drive.google.com/file/d/1dwPWgargfSiYi-KMFOFXDH9V1jTvhBTh/view?usp=sharing
> 
> Dá sa s tým hrať... Vyladené na 16S batériu


You can describe it in more detail, I'm not an experienced user, I would need a little more detailed explanation if possible. Thank you

**Comment by lumiror** [comment]
> Yes ESPhome with a custom sensor : https://drive.google.com/file/d/1dwPWgargfSiYi-KMFOFXDH9V1jTvhBTh/view?usp=sharing
> 
> You can play with it... Tuned for a 16S battery

You can describe it in more detail, I'm not an experienced user, I would need a little more detailed explanation if possible. Thank you

**Comment by SeByDocKy** [comment]
Juste install the yaml and .h files into your /config/Esphome directory. Edit in Esphome the yaml file and change your WiFi informations... Be sure to connect the TX & RX to the pins specified in the top of the .h file... Than compile and install the file on your ESP32.

**Comment by lucasimons** [comment]
I received the batteries so now I would like to use the bms if I'm not mistaken this connector I have to use it to power the two wires to turn on the bms after connecting them in short circuit, instead the other two wires are rx and tx right?  Can you send some pictures of the links?  I thank you in advance

**Comment by lumiror** [comment]
> Stačí nainštalovať súbory yaml a .h do vášho adresára /config/Esphome. Upravte v Esphome súbor yaml a zmeňte informácie o WiFi... Uistite sa, že ste TX & RX pripojili ku kolíkom uvedeným v hornej časti súboru .h... Potom súbor skompilujte a nainštalujte do svojho ESP32.

Thank you for the answer, it is possible to use the module WeMos D1 Mini, ie ESP8266

**Comment by SeByDocKy** [comment]
As I wrote from the beginnin the code I wrote sometimes ago was for the ANTbms model 2020.... Not sure it will work with the 2021 version as you have since the Appz changed between.... I guess they changed something in the protocol. But yes it's possible to use a simple WeMos D1 mini

**Comment by lumiror** [comment]
I don't know what I'm doing wrong but if I add an "includes" command I get an error, can you please help me how to fix it? I created a new file "antbms_custom_sensor.h" is that ok? Thanks.

**Comment by SeByDocKy** [comment]
The include part must be in the esphome: section like

```esphome:
  name: antbms
  platform: ESP32
  board: esp32dev
  includes:
    - antbms_custom_sensor.h```

**Comment by lumiror** [comment]
Thank you for the quick reply it helped. Can you please help me again? I got a SERIAL error, I changed the SERIAL2 to SERIAL1 error then only to SERIAL and also the error so I don't know how to fix it.
![error](https://user-images.githubusercontent.com/33359116/150853625-7fbfe251-3584-4076-8a8d-78f2f9c6b187.jpg)

**Comment by lumiror** [comment]
So I managed to compile and upload to esp32 because esp 2886 didn't work. But now I have a problem, in homeassistant I see no data for entities. In antbms_custom_sensor.h is RX at 17 and TX at 16, is that correct? It should not be the other way around. Can there be a problem with that? I also tried TX on Tx RX on RX but I still don't see any data just unknown. Plus contact from BMS should not be connected? Because if I connect a display without a plus contact, the BMS will not connect to the display. Can you please help where there may be a mistake, maybe I'm close to making it work, I'd be very grateful. That's how I connected it.

![ant](https://user-images.githubusercontent.com/33359116/151700089-b5b1e163-42d3-4349-bebf-012d1acad37a.jpg)

**Comment by HaraldRuppert** [comment]
Hi,
same for me. I've also just tried to connect it the way it's described here: https://github.com/imval/AntBMS/issues/1
@lumiror are you using it for 8S or 16S? I've also tried to port it to ESP8266 but even with my ESP32 and unmodified code, ​it doesn't read anything.


Look  at the pinout of your  ANT-BMS LCD btw. the colors for the wires don´t make logical sense.
​For me, green = ground, red = VCC, yellow = RX and black = TX.

But I also struggle to read anything on any wire with a multimeter so I wonder if they even work.

**Comment by lumiror** [comment]
Hi, I use 16S exactly as the author. Unfortunately, I still don't get any data. Maybe if the author gave a photo of which version of BMS he would use, we would move somewhere. I had those cables just like you, but before the assembly I swapped them according to the standard. Do you have a program that works via bluetooth?

**Comment by lucasimons** [comment]
hello, but you have turned on the bms, that is through bluetooh it works for you? I always have to receive the cells then I try if it works, as I asked in this discussion I did not know if I had to connect the black and red cables together because in the manual it is written that you have to apply a voltage of 3.2v between the two cables and then connect them later together, what procedure did you use?

**Comment by lumiror** [comment]
Via bluetooth it works with the original application, but only locally and limited bluetooth range. I don't understand the question, what red and black cable do you want to connect?

**Comment by SeByDocKy** [comment]
> So I managed to make it work. I just have a little problem. The program freezes quite often, so I want to ask someone who uses it, if it happens to you and if so, how often. Thanks

try to remove the date_baud: 0 in the logger and maybe you will have to adjust some timing in the .h

**Comment by lumiror** [comment]
Could you be more detailed please? Where can I find timing in the .h so which line is it. Alternatively, as I delete date_baud: 0 in the logger. I am a beginner and this information will help me a lot.

**Comment by lucasimons** [comment]
Hi, unfortunately I have not yet been able to test the communication between bms and esp but I have seen that new repositories have been created for the various bms and integrated with esphome like this for jk bms

https://github.com/syssi/esphome-jk-bms

, it would be interesting to create a repo for ant bms

**Comment by lucasimons** [comment]
Hi, if you want to join to test and implement ant bms on esphome you can write here

**Comment by lumiror** [comment]
Just today I finished testing a new version from 2021 which also works. I am very satisfied . I have an old and a new version of BMS and they both work via the display port. If you have a display for your BMS and displays the data it is highly likely that it will work for you as well. Then just tune the stability (this must be done by someone who knows how to program, unfortunately I don't know) and it will be a great version for ANT BMS. Thanks to the author for sharing.
![ANT BMS](https://user-images.githubusercontent.com/33359116/155003772-85d889be-685c-4237-a832-881a3e42ee4d.jpg)

**Comment by lucasimons** [comment]
I also have two bms one 100a old and one new 300a purchased in October 2021, so I think I am in the same condition as you, have you made any changes to the code? Can you explain better?

**Comment by SeByDocKy** [comment]
> Just today I finished testing a new version from 2021 which also works. I am very satisfied . I have an old and a new version of BMS and they both work via the display port. If you have a display for yourANT BMS and displays the data it is highly likely that it will work for you as well. Then just tune the stability (this must be done by someone who knows how to program, unfortunately I don't know) and it will be a great version for ANT BMS. Thanks to the author for sharing. ![ANT BMS](https://user-images.githubusercontent.com/33359116/155003772-85d889be-685c-4237-a832-881a3e42ee4d.jpg)

It's me :)

**Comment by lumiror** [comment]
> >
> It's me :)

I know

![perfect](https://user-images.githubusercontent.com/33359116/155006405-8693e043-5d76-4a57-baba-ef65d83604a9.jpg)

**Comment by lumiror** [comment]
> I also have two bms one 100a old and one new 300a purchased in October 2021, so I think I am in the same condition as you, have you made any changes to the code? Can you explain better?

I didn't change anything, I just copied it to ESPHome and ESP32 as described by SeByDocKy.

**Comment by SeByDocKy** [comment]
> > I also have two bms one 100a old and one new 300a purchased in October 2021, so I think I am in the same condition as you, have you made any changes to the code? Can you explain better?
> 
> I didn't change anything, I just copied it to ESPHome and ESP32 as described by SeByDocKy.

Glad to know that my code still work with the antbms 2021.... Some tested but was not working. I went directlly to the JKBMS when I saw the amazing @syssi integration

**Comment by lumiror** [comment]
As I wrote, I had to connect plus contact otherwise it also didn't work for me.

**Comment by lucasimons** [comment]
> > I also have two bms one 100a old and one new 300a purchased in October 2021, so I think I am in the same condition as you, have you made any changes to the code? Can you explain better?
> 
> I didn't change anything, I just copied it to ESPHome and ESP32 as described by SeByDocKy.
> 
> **Note:** I also had to connect a plus contact to 3.3V on my BMS. I used a 3.3V output from ESP32. :)

how did you connect the esp32 to the bms? do you have a picture?

**Comment by lucasimons** [comment]
> > > I also have two bms one 100a old and one new 300a purchased in October 2021, so I think I am in the same condition as you, have you made any changes to the code? Can you explain better?
> > 
> > 
> > I didn't change anything, I just copied it to ESPHome and ESP32 as described by SeByDocKy.
> 
> Glad to know that my code still work with the antbms 2021.... Some tested but was not working. I went directlly to the JKBMS when I saw the amazing @syssi integration

I also saw the various syssi integrations and in fact I asked to @syssi if it was possible to merge what you wrote and integrate it on esphome, seen the results of @lumiror  I believe that there are no problems

**Comment by lumiror** [comment]
As I described. Just be careful, I swapped cables. You have them connected differently by color
![connect](https://user-images.githubusercontent.com/33359116/155008871-d88f79d1-85f9-4458-9438-3471106a97fd.jpg)
.

**Comment by syssi** [comment]
@SeByDocKy You did a great job building the custom sensor setup! I've converted your findings/knowledge into a custom component and would be happy about some testers. Please give a try:

https://github.com/syssi/esphome-ant-bms/
https://github.com/syssi/esphome-ant-bms/blob/main/esp32-example.yaml

If it doesn't work out of the box please create an issue and provide some log output. The debug output of the `uart` component is enabled per default at the moment to log as much as possible (the serial traffic).

**Comment by SeByDocKy** [comment]
> @SeByDocKy You did a great job building the custom sensor setup! I've converted your findings/knowledge into a custom component and would be happy about some testers. Please give a try:
> 
> https://github.com/syssi/esphome-ant-bms/ https://github.com/syssi/esphome-ant-bms/blob/main/esp32-example.yaml
> 
> If it doesn't work out of the box please create an issue and provide some log output. The debug output of the `uart` component is enabled per default at the moment to log as much as possible (the serial traffic).

WHaooohhhh so great :) Incredible. I know several person with the AntBMS 2021 (I have one too)... so  we will have feedbacks. Little out of topic. Why you don't ask the official integration of your JKBMS into ESPhome ?

**Comment by syssi** [comment]
Off-topic answer: Because of some "technical debt". The JK-BMS component uses a modified version of the [modbus component](https://github.com/esphome/esphome/tree/dev/esphome/components/modbus) component. The successor of the `modbus` component is the [modbus_controller](https://github.com/esphome/esphome/tree/dev/esphome/components/modbus_controller) (a great component with important features f.e. send individual frames + queueing of commands/requests + expect responses). To control the BMS command queueing is required. The generic `modbus` component cannot be extended easily without becoming device specific. IMO the JK-BMS component shouldn't merged into ESPHome as long it doesn't use the `modbus_controller` as base.

**Comment by lucasimons** [comment]
> platform: ESP32
>   board: esp32dev
I tried to use the custom component of @SeByDocKy , but unfortunately it doesn't work with esp8266 and with esp32 I have these disconnections
![image](https://user-images.githubusercontent.com/67467751/155024464-6bf940a7-ec1a-487a-bec6-1cc84a19707b.png)
![image](https://user-images.githubusercontent.com/67467751/155025205-95a08aec-4306-44e2-9897-47f64850b9e0.png)

**Comment by lucasimons** [comment]
This is my configuration, I have also tried to connect the red wire with the 3.3v but i don't show anything on home assistant

**Comment by lumiror** [comment]
Your BMS is different. Do you have a display? Does it show you data from BMS? As you have it connected, take a picture.

**Comment by lucasimons** [comment]
> Your BMS is different. Do you have a display? Does it show you data from BMS? As you have it connected, take a picture.

I have two bms both without display, I soldered some wires because I did not have the display connector however starting from the left it says on the pcb positive, gnd, B, A, assuming that the last two pins are for the display

**Comment by lumiror** [comment]
I have it connected like this:
positive to output  3.3v ESP32
gnd = gnd
A = RX
B = TX

**Comment by lumiror** [comment]
still check if you have correctly assigned pins, in the program it is:
#define RXD2 17
#define TXD2 16
but your ESP32 has the other way around

**Comment by lucasimons** [comment]
I connected the left pin to 3.3 the pin 2 to gnd then the white cable to 16 and the right cable to 17, so I have no instability problems, but it gives an error trame
![image](https://user-images.githubusercontent.com/67467751/155103095-fc40b117-ff82-4876-b19c-f57df6049ac9.png)

**Comment by lucasimons** [comment]
the original display cable have this color red, black, yellow, green 

red to 3.3v
gnd to gnd
yellow ( white in my pic) to tx2 
green  ( yellow in my pic) to rx2

**Comment by lumiror** [comment]
For me, the flood color of cables:
  red = VCC
green = GND
yellow = A (RX)
black = B (TX)

**Comment by lumiror** [comment]
Do you see the data in the APP via bluetooth? If so, try to change RX and TX or disconnect the VCC 3,3V from ESP 32. You have to try several options and see what it does.

**Comment by lucasimons** [comment]
I think I got confused with the cables ... Anyway, do you know what kind of connector is the one of the display?

**Comment by lumiror** [comment]
I don't know exactly what type it is, but it's this:

![connector](https://user-images.githubusercontent.com/33359116/155202927-41eb2fa0-d6bb-4973-bada-5fc20cec155b.jpg)

**Comment by SeByDocKy** [comment]
Should be JST XH2.0 4P or JST/microMolex 1.25mm 4p

**Comment by lucasimons** [comment]
I tried but through the custom components it does not work and there are always problems with the esp 32 that I have and unfortunately I do not know the reason but it does not work on esp8266, I had reversed the cables because the black was not gnd but tx

**Comment by lumiror** [comment]
This is not a BMS mainboard, but a display

**Comment by syssi** [comment]
Good point. It helps nevertheless to identify `VCC` and `GND`. `TX` and `RX` will have to be tried out.

**Comment by lumiror** [comment]
> I tried but through the custom components it does not work and there are always problems with the esp 32 that I have and unfortunately I do not know the reason but it does not work on esp8266, I had reversed the cables because the black was not gnd but tx

ESP8266 don't even try it doesn't work, but as Syssi writes take photos as you have it connected. But good quality, focused so we can see the details

**Comment by lumiror** [comment]
..... something to motivate ![foto1](https://user-images.githubusercontent.com/33359116/155368849-d6208af3-77c7-4e09-8281-3866a71e4740.jpg)


![foto](https://user-images.githubusercontent.com/33359116/155369077-be88f04a-1cce-4ac2-8568-4634b85e6e8d.jpg)

**Comment by lumiror** [comment]
take yet photo of ESP32

**Comment by lucasimons** [comment]
![IMG_20220223_180041.jpg](https://user-images.githubusercontent.com/67467751/155372023-bb22d468-e4c6-4505-929d-f8cb55483659.jpg)

**Comment by lumiror** [comment]
It is not visible to which pins you have the green and yellow cable connected

**Comment by lucasimons** [comment]
now it works fine 
![image](https://user-images.githubusercontent.com/67467751/155375425-b69f6fe7-edd1-4328-8ef1-d1b461f72196.png)

**Comment by lumiror** [comment]
That's great. Maybe I would connect it for safety on IO 17 and IO16 TX2 RX2

**Comment by arnold34740** [comment]
Hello , not sure to post at the correct place , 
i've got antbms 20A with tx 15 rx 13 on esp8266 wemos d1 mini . All switches works perfectly but no sensors are displayed.
I try to reverse rx with tx but when i do that i loose switch commands . It's a old 2020 protocol with the old app i don't know what to do .
Thanxs 4 ur help

**Comment by syssi** [comment]
Could you provide your yaml configuration?

**Comment by lucasimons** [comment]
> 

haw many amp? 20a? Can you send a pic?
