### ISSUE TITLE
Add authentication to the node management page

### ISSUE THREAD

**Issue by andker87** [esphome/feature-requests#1419]
**Describe the problem you have/What new integration you would like**

it would be useful to offer the possibility to protect the main node management page with a login given by username and password

**Please describe your use case for this integration and alternatives you've tried:**

if someone performs a port scan inside the network he could identify the service, enter in the nodes management page, alter them and upload the modified firmware 

**Additional context**

**Comment by OttoWinter** [comment]
Already exists

For the HA addon installation method it's secured through HA's ingress feature.

For docker based installs you just need to change the username/password env variables: https://github.com/esphome/esphome/blob/dev/docker/Dockerfile#L70

For pip based installs there are cli options for that: 
```
$ esphome dashboard --help       
usage: esphome dashboard [-h] [--port PORT] [--username USERNAME] [--password PASSWORD] [--open-ui] [--socket SOCKET]
                         configuration

positional arguments:
  configuration        Your YAML configuration file directory.

optional arguments:
  --username USERNAME  The optional username to require for authentication.
  --password PASSWORD  The optional password to require for authentication.
```
