### ISSUE TITLE
Advanced IR remote climate for Mitsubishi AC

### ISSUE THREAD

**Issue by LarkeMikko** [esphome/feature-requests#1420]
**Describe the problem you have/What new integration you would like**

I'd need more advanced features to control Mitsubishi AC with IR transmitter. More specifically feature to control pumps fan speed through EspHome would be needed. This feature already is available at least for Fujitsu AC through EspHome and works from Mitsubishi original remote, so should be doable?

**Please describe your use case for this integration and alternatives you've tried:**

I'm planning to use PIR sensor to detect motion on AC pumps flow path, and lower the fan speed if motion is detected. Already tried to catch the IR raw code from remote with IR receiver and control it through custom switch, but with no success.

**Additional context**

**Comment by nagyrobi** [comment]
See https://esphome.io/components/climate/climate_ir.html?highlight=mitsubishi
