### ISSUE TITLE
Media_Player Component, customizable based on device abilities

### ISSUE THREAD

**Issue by glyndon** [esphome/feature-requests#1421]
**Describe the problem you have/What new integration you would like**

An ESPHome component that appears as a Media Player to Home Assistant, and presents whatever controls the ESP has to present.
e.g. Media Player/Speakers, which would present on/off and 'Volume' for control by HA.

**Please describe your use case for this integration and alternatives you've tried:**

In my case, I will have an audio amplifier with its own signal source and attached speakers, but whose volume control is accessible via I2C. So an ESP would make an easy way to control its audio volume via HA.

**Additional context**

An existing component with very similar functionality is "Monochrome Light", because it offers on/off/dimming functions. If you substitute 'volume' for 'dimming' it's almost the same thing. The main difference is that it should present itself to HA as a 'media player' instead of as a 'light'.

**Comment by magiva** [comment]
Phil Schatzmann has already created the esp32 library for audio streaming https://github.com/pschatzmann
We just need to be able to expose/register the esp32 device as a home assistant media player.
This would be an awesome solution and step forward to non-cloud home control

**Comment by nagyrobi** [comment]
https://github.com/esphome/feature-requests/issues/783
