### ISSUE TITLE
Add slider option to template number

### ISSUE THREAD

**Issue by chatziko** [esphome/feature-requests#1431]
**Describe the problem you have/What new integration you would like**

Template number is extremely useful for getting input from HA. However, it is currently shown in the UI as a __box__, which is hard to use for several use cases (especially on touch devices). HA's `input_number` uses a __slider__ by default (configurable via the [mode option](https://www.home-assistant.io/integrations/input_number/#mode)), it would be great to have an option to use sliders also in esphome's template number.

**Please describe your use case for this integration and alternatives you've tried:**

IMHO most of the use cases of a template number would benefit frrom a slider UI.

For instance: I'm implementing a esp32 control for an active speaker, and I want its volume to be shown as a template number. A slider is the natural UI for that.

**Additional context**

Thanks for your amazing work on esphome! :smile:

**Comment by OttoWinter** [comment]
> HA's input_number uses a slider by default (configurable via the mode option), it would be great to have an option to use sliders also in esphome's template number.

I agree, but that is not in esphome's domain.

We just implement the [number entity](https://developers.home-assistant.io/docs/core/entity/number/) interface (`input_number` is a different/older thing in HA, that we wouldn't be allowed to use).

You need to request this feature in the [HA forums](https://community.home-assistant.io/) to have it added to the number entity, then ESPHome can easily add support for that too.
