### ISSUE TITLE
Add support for Modbus Slave 

### ISSUE THREAD

**Issue by hieumaric** [esphome/feature-requests#1435]
**Describe the problem you have/What new integration you would like**

It would be great to be able to use ESPhome on ESP32 as a Modbus slave.
I would like to use Modbus RTU via RS-485, but Modbus TCP would also suffice.

**Please describe your use case for this integration and alternatives you've tried:**
I asked at Discord and ESPhome can only use Modbus Controller

**Additional context**
Thank you!!

**Comment by nagyrobi** [comment]
https://github.com/esphome/feature-requests/issues/708
