### ISSUE TITLE
Support Dallas/DHT temperature addon for Shelly 1 device

### ISSUE THREAD

**Issue by alexander-vitishchenko** [esphome/feature-requests#1456]
**Describe the problem you have/What new integration you would like**
Let's add support for Dallas/DHT temperature sensor addon for Shelly 1 device, for being able to use it as climate thermostat. Luckily, the implementation is already created and it "just" needs to be merged from https://github.com/persuader72/esphome-components, which is a fork of "dallas" platform.

**Please describe your use case for this integration and alternatives you've tried:**
I'm currently using a forked version of the "dallas" that is called "shelly_dallas". It works great, but new features development for "Dallas" and "Shelly_dallas" are out of sync, leaving users without the best from two worlds..
 
**Additional context**
Here go more details on how the existing "shelly_dallas" implementation appeared - https://github.com/esphome/feature-requests/issues/701

**Comment by kcinnaySte** [comment]
That would be definitely interesting!
