### ISSUE TITLE
Add support for temperature sensor in custom climate

### ISSUE THREAD

**Issue by nagyrobi** [esphome/feature-requests#1464]
**Describe the problem you have/What new integration you would like**
We would like to have the same `sensor` configuration option available for [Custom Climate](https://esphome.io/components/climate/custom.html) just like the way it is present in [IR Remote Climate](https://esphome.io/components/climate/ir_climate.html).
The problem is that as the climate shows up in Home Assistant it has an unavailable sensor present and it's quite unusable like this. While it's possible to have on the same node a dedicated temperature sensor, even set as internal, we miss the possibility to link it with the climate. 

```
[14:38:04][D][sensor:121]: 'IR-4 Hőmérséklet': Sending state 23.18750 °C with 1 decimals of accuracy
[14:38:13][D][climate:009]: 'IR-4 Klíma 2' - Setting
[14:38:13][D][climate:013]:   Mode: OFF
[14:38:13][D][climate:373]: 'IR-4 Klíma 2' - Sending state:
[14:38:13][D][climate:376]:   Mode: OFF
[14:38:13][D][climate:393]:   Swing Mode: OFF
[14:38:13][D][climate:396]:   Current Temperature: nan°C
[14:38:13][D][climate:402]:   Target Temperature: 19.20°C
```

**Please describe your use case for this integration and alternatives you've tried:**
Just like [IR Remote Climate](https://esphome.io/components/climate/ir_climate.html) has, have an option similar to this:

```
climate:
- platform: custom
  lambda: |-  # just example lambda code 
    auto bedroom_ac = new GreeAC();
    App.register_component(bedroom_ac);
    return {bedroom_ac};
  climates:
    name: "IR-4 Klíma 2"
      sensor: temp   # new option

sensor:
  - platform: dallas
    address: 0x840300A27936CC28
    name: IR4 Hőmérséklet
    id: temp
    filters:
      - filter_out: nan
```

**Additional context**
Using Gree climate control from https://github.com/Hagakurje/ESPHome_Gree_AC

**Comment by OttoWinter** [comment]
It is possible already, it just needs to be implemented in the custom climate device.

In the `custom` lambda, pass the sensor to the custom component `... = new GreeAC(id(temp));`

And in the custom code accept a `sensor::Sensor *` in the constructor like in the climate devices in esphome.

So you need to ask the Gree_AC custom component author to add support for that.
