### ISSUE TITLE
Allow logging to be disabled over MQTT

### ISSUE THREAD

**Issue by baze-** [esphome/feature-requests#1465]
**Describe the problem you have/What new integration you would like**

I would like to disable logging over MQTT, but have UART logging enabled. Also MQTT needs to be enable so metrics can be sent to server.

**Please describe your use case for this integration and alternatives you've tried:**

High update_interval sensors are causing flood of debug messages to be sent to MQTT Server.
Disabling logging completely or disabling UART Logging for specific sensor makes troubleshooting hard.

It would be perfect if I could have logging enabled on local UART but disabled on MQTT.
Disabling MQTT isn't an option as that is used to send the metric to server.

**Additional context**

Adding new directive to **configuration file** could be:
```
Logger:
     log_over_mqtt: true
```
**log_over_mqtt** would be enabled by default, but could be disabled if needed.
"log_over_mqtt" could cause new "**#define USE_MQTT_LOGGER**" that could be used in [mqtt_client.cpp:48](https://github.com/esphome/esphome/blob/dev/esphome/components/mqtt/mqtt_client.cpp#L48) to enable or disable logging.

**Comment by OttoWinter** [comment]
Yeah, this is already possible, closing
