### ISSUE TITLE
Version control for Configuration

### ISSUE THREAD

**Issue by kriss2013** [esphome/feature-requests#1466]
**Describe the problem you have/What new integration you would like**

I have a lot of ESPHome devices connected to HA which I have running for months at once without tinkering, just enjoying;-) then I have some new ideas, for HA or ESPHome, and more often than not I realize (mostly the hard way) that the YAML in HA ESPHome dashboard does not reflect the running firmware. Reasons are multiple, call me sloppy if you want, but it occurs.

**Please describe your use case for this integration and alternatives you've tried:**

ESPHome could implement some kind of Version Control for the firmware.  A "poor man" way could look like this: as the firmware is defined by a YAML file, a canonical form (to avoid irrelevant formatting differences) of the YAML could be the version string, this string should be stored into the device. This way, the dashboard could show any discrepancy between the editor and the running firmware. 

**Additional context**

- One drawback: this does not take the content of included files into account (hence "poor man"). 
- One extra: it would need the YAML content to be stored somehow into the device, making it recoverable.

**Comment by OttoWinter** [comment]
Duplicate/connected to https://github.com/esphome/feature-requests/issues/1423, https://github.com/esphome/feature-requests/issues/1239, https://github.com/esphome/feature-requests/issues/528
