### ISSUE TITLE
"Getting Started" somewhat confusing

### ISSUE THREAD

**Issue by r0oland** [esphome/feature-requests#1468]
Not sure how to go about this, i.e. suggest here or should I suggest changes directly via pull request? 

**Describe the problem you have/What new integration you would like**

Quick Background to my person for some perspective:
- experienced embedded designer
- novice home assistant user 
- 
I found the getting started infos somewhat lacking. Like it's not bad, but still somewhat confusing. 

Some recommendations:
- add getting started to table of contents (not just the sensors)
- update the infos on the "Dashboard Interface" (https://esphome.io/guides/getting_started_hassio.html#dashboard-interface), COMPILE does not exist and is part of INSTALL
- add instructions to manually flash the initial firmware for later OTA updates
  - I found it a lot easier to just INSTALL -> Manual download and use ESP flasher for the first setup rather than setting up HTTPS for a local home assistant install and having to setup lets encrypt etc
- add infos for more experienced users, i.e. how do I compile firmware locally (rather than on the rather slow Home Assistant machine
- add concret, copy & paste examples for the sensors, or at least a somewhat more extended / complete example how to get started with a first few devices.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by r0oland** [comment]
To illustrate my first point:
![image](https://user-images.githubusercontent.com/558053/137678696-ae93de90-2e70-4e58-919e-64e9bb3e34b6.png)

**Comment by BruceCrowthorne** [comment]
As another new user, I second this - getting started is a pain!!!!
You need some SIMPLE code examples.
