### ISSUE TITLE
Add decoder/IR remote receiver support for the MagiQuest wand (Halloween yay!) 

### ISSUE THREAD

**Issue by kwatkins** [esphome/feature-requests#1483]
**Describe the problem you have/What new integration you would like**
The magiquest wand as a decoder time for remote_receiver.

**Please describe your use case for this integration and alternatives you've tried:**
This would decode when magiquest wands are used, sending the decoded information to home assistant for automations, great for kids. 

**Additional context**
The protocol has been fully decoded, see https://arduino-irremote.github.io/Arduino-IRremote/ir__MagiQuest_8cpp_source.html

**Comment by sreknob** [comment]
@ImSorryButWho thanks for integrating this! Works like a treat!
My kids got these on the weekend and are now going around the house working on their Lumos spell! 🤣
