### ISSUE TITLE
Control two or more ESPs for lights without Home Assistant

### ISSUE THREAD

**Issue by AWSb24** [esphome/feature-requests#1496]
**Describe the problem you have/What new integration you would like**

Control two or more ESPs for lights without Home Assistant

**Please describe your use case for this integration and alternatives you've tried:**

Is it possible to control two or more ESPHome devices with the same config/pin map via Home Assistant or IR receiver without automatization in Home Assistant?

**Additional context**

I have a kitchen counter and a kitchen island. Both are not electrically connected. Hence I want to use two ESPs to control the RGB strip on the counter and on the island. I want to connect an IR receiver to the ESP in the island to control the lights without using the Home Assistant App. Hence the ESP in the island has to tell the ESP in the counter the change the color. I don't want to depend on HA to control the lights.

**Comment by randybb** [comment]
It is not intended use of esphome, but it is possible. [Web server](https://esphome.io/components/web_server.html) provides [REST API](https://esphome.io/web-api/index.html) that can be controlled by [http requests](https://esphome.io/components/http_request.htm).
