### ISSUE TITLE
Add COVER_OPERATION_POSITIONING

### ISSUE THREAD

**Issue by nordeep** [esphome/feature-requests#1500]
**Describe the problem you have/What new integration you would like**

For now if cover is in state - set of position by cover.control then CoverOperation is COVER_OPERATION_IDLE. This is not true.
Seems only Open and Close operations are tracked by CoverOperation.
It would be great to have ability to check if Cover is positioning or not. Also it would be great to have the trigger like - cover.on_positioned or cover.on_stop which will fire when cover stop after set of position is done.

**Please describe your use case for this integration and alternatives you've tried:**

In order to release the tension of my chain connected to AM43  I do small backward step by cover.open(cover.close) - delay - cover.stop. To know when to perform tension release I need to know when the cover has stopped. For now I'am using long delay,

**Additional context**

**Comment by nagyrobi** [comment]
According to the docs, this is possible now: https://esphome.io/components/cover/index.html?highlight=opening
