### ISSUE TITLE
Please implement the Az-Delivery Board D1 R32

### ISSUE THREAD

**Issue by Beliar-666** [esphome/feature-requests#1502]
**Describe the problem you have/What new integration you would like**
I suggest to implemetn the Az-Delivery Board D1 R32 Wifi&Bluetooth R32 Based on ESP32 Wroom-32

**Please describe your use case for this integration and alternatives you've tried:**
With using one of the implemented Boards the D1 R32 will not connect to Wifi correctly. I Tried to compile Firmware with similar ESP32 based Boards from ESPHome Dashboard. Wifi won´t work without errors.

**Additional context**

**Comment by martgras** [comment]
You can just use `esp32dev`  instead
