### ISSUE TITLE
Add Support for Environmental Sensor Adafruit BMP390

### ISSUE THREAD

**Issue by TimWilliamsGitHub** [esphome/feature-requests#1517]
**Describe the problem you have/What new integration you would like**

Add Support for Environmental Sensor Adafruit BMP390 in Esphome. The BMP390 is the next-generation of sensors from Bosch and is the upgrade to the BMP280 and BMP388 - with a low-altitude noise as low as 0.1m and the same fast conversion time. And like the previous BMP280, you can use I2C or SPI.

**Please describe your use case for this integration and alternatives you've tried:**

Aim: To accurately measure and record precise pressure changes in the Earths atmosphere. I have used it with Pi Zero, but would like to use it with my ESP32 I2C interface.

**Additional context**

https://www.adafruit.com/product/4816

**Comment by oxan** [comment]
See esphome/esphome#2716.
