### ISSUE TITLE
add I2S PCM5102A & dlna(or another network audio player) for esp32

### ISSUE THREAD

**Issue by ananyevgv** [esphome/feature-requests#1528]
Hi. I would like to get support for audio devices over the i2c bus, with the ability to create a network audio player

**Comment by ananyevgv** [comment]
https://github.com/espressif/esp-adf/blob/ec0ea830cc5fbb702a6745e4e3991ff38595ff0f/examples/advanced_examples/dlna/main/dlna_example.c

**Comment by nagyrobi** [comment]
https://esphome.io/components/media_player/i2s_audio.html

**Comment by ananyevgv** [comment]
Thank you very much!!!!!!!!!!!!!!!!!!!!!!
