### ISSUE TITLE
Siren entity

### ISSUE THREAD

**Issue by Naesstrom** [esphome/feature-requests#1550]
**Describe the problem you have/What new integration you would like**

I've made a siren that uses a GPIO pin to activate a relay and a cheap 12V 120db Siren and a red strobe. Home-Assistant added a siren entity a while back and it would be great to be able to set that in ESPHome
![image](https://user-images.githubusercontent.com/6575206/145973314-8b1f88c4-c324-462e-8b0e-365773dcade1.png)

**Please describe your use case for this integration and alternatives you've tried:**

By setting a variable or something in ESPHome to get Home-Assistant to recognize it as a siren entity

**Additional context**

Link to home-assistant docs: https://developers.home-assistant.io/docs/core/entity/siren

**Comment by Wferr** [comment]
This would be helpful!

**Comment by Naesstrom** [comment]
> This would be helpful!

I just used the new helper function to change the switch to an alarm in home-assistant. Seems to be working
![image](https://user-images.githubusercontent.com/6575206/164887160-92931f31-8cb0-41c6-8fb8-0659af991082.png)
