### ISSUE TITLE
Get current timestamp in milliseconds

### ISSUE THREAD

**Issue by tefracky** [esphome/feature-requests#1554]
**Describe the problem you have/What new integration you would like**

Is ist somehow possible to get the current System time of the ESP in milliseconds? It is possible to get the time in seconds by 

```
time:
  - platform: sntp
    id: sntp_time

...

id(sntp_time).now().timestamp
```

How can I get the timestamp in milliseconds?

Thanks  a lot!

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by bojanpotocnik** [comment]
I'm trying to get logger component to print timestamps with grater precision than seconds, and stumbled upon this request. Any news on this topic?

**Comment by nagyrobi** [comment]
For fast answers, please use the Discord channel.
