### ISSUE TITLE
climate.control missing fields in "swing mode"

### ISSUE THREAD

**Issue by cg089** [esphome/feature-requests#1561]
**Describe the problem you have/What new integration you would like**
Mitsubishi (and other brands too) have a vane that can have different positions (from 1-5, AUTO and SWING) that can be chosen.
This works well with the home assistant climate component and mqtt.
However, according to https://esphome.io/components/climate/index.html only the following modes are integrated: "OFF, BOTH, VERTICAL, HORIZONTAL".

This leads to non-working esphome plugins, see:
https://github.com/geoffdavis/esphome-mitsubishiheatpump/issues/33

**Please describe your use case for this integration and alternatives you've tried:**
Set the vane position in AC.

**Additional context**

**Comment by nagyrobi** [comment]
I think this should be posted in [issues](https://github.com/esphome/issues/issues).
