### ISSUE TITLE
Component and platform buttons to add new devices to esphome yaml

### ISSUE THREAD

**Issue by mvturnho** [esphome/feature-requests#157]
**Describe the problem you have/What new integration you would like**

The dashboard is basicaly a yaml editor. Would it be possible to add components and platforms from a library. This way you get the requred and optional parameters in the yaml. You then edit these settings.

**Please describe your use case for this integration and alternatives you've tried:**

- start a new project with the wizard
- add components from the library and edit the parameters of the component in the yaml editor.
- add platforms using component-hub id's that were previously edited.
- compile and upload to you device 

**Additional context**

**Comment by OttoWinter** [comment]
See https://github.com/esphome/ESPHome/issues/64

There will be an extensibility system in place at some point (with https://github.com/esphome/feature-requests/issues/97), and it will be like the HA model: you can put stuff in a `custom_components` folder and it will be just like any other esphome component.
