### ISSUE TITLE
Add USB CDC support to Logger component

### ISSUE THREAD

**Issue by unaiur** [esphome/feature-requests#1598]
ESP32S2 and ESP32C3 has integrated USB support and modules usually do not include an external USB -> serial bridge. 
But EspHome does not support USB CDC, leaving no easy path forward. 

**Describe the problem you have/What new integration you would like**

Add support for USB CDC in the logger component, to make logging even simpler.

**Please describe your use case for this integration and alternatives you've tried:**

We can use a hardware UART, but it requires an extra USB to serial bridge and consumes one of the two UARTs in ESP32S2/C3. Some modules (like LOLIN S2 mini) not even expose the UART0 pins, leaving no hardware UARTs available.

**Additional context**

**Comment by rbray89** [comment]
I'm interested in this, but for Host USB. I have a device that the only way to communicate with it is to connect it to a USB Host and treat it as a CDC ACM device.

Ideally the UART would be extended to make this as generic as possible.

**Comment by unaiur** [comment]
That would not be handled by the logger.

You would need a full USB stack instead of the one that is integrated into
the chip ROM memory and can only handle logging and firmware upgrades.

Best regards!
