### ISSUE TITLE
Dashboard reboot function

### ISSUE THREAD

**Issue by erazor666** [esphome/feature-requests#161]
**Describe the problem you have/What new integration you would like**
Sometimes I want to restart a node, and it may be in a difficult place to reach. A reboot node function in dashboard if it is technically possible.

**Please describe your use case for this integration and alternatives you've tried:**
I've usually used the OTA function to get the node to restart if I need it to, but a reboot function would be better.

**Additional context**

**Comment by OttoWinter** [comment]
See https://esphome.io/components/switch/restart.html
