### ISSUE TITLE
Authentication for frontend

### ISSUE THREAD

**Issue by Kalypox** [esphome/feature-requests#1610]
**Authentication frontend**

**Please describe your use case for this integration and alternatives you've tried:**
No alternative

**Additional context**
It could be great to have possibility to protect this webpage :
![image](https://user-images.githubusercontent.com/2879180/150853539-5e077428-1d10-4079-8d91-f2968cad05be.png)
My goal is to access this page from outside my local network, that's why a login/password could be great.

Thanks :)

**Comment by randybb** [comment]
Like this? https://esphome.io/guides/cli.html?#dashboard-command

**Comment by Kalypox** [comment]
Hello @randybb,
Yes it seems to be !
Thanks !

I'm using esphome as add-on in home assistant, do you know how can I add these parameters ?

**Comment by randybb** [comment]
This is only for standalone or docker with some modification. I am not familiar with HASS plugins. Would stick with the default option - access it via HA exposed to the internet (web or app).

**Comment by Kalypox** [comment]
Okay clear thanks !
I will try to use it with docker !
