### ISSUE TITLE
Add a "stable" docker tag, HA style

### ISSUE THREAD

**Issue by koying** [esphome/feature-requests#1614]
There is a "stable" tag for Home Assistant docker images, which makes it easy to stick to stable releases.
It would be nice id esphome followed this convention.

Thanks

**Describe the problem you have/What new integration you would like**

Having a "stable" docker tag.

**Please describe your use case for this integration and alternatives you've tried:**

Easiness to upgrade container.

**Additional context**

**Comment by andrey-yantsen** [comment]
JFYI, according to https://github.com/esphome/esphome/blob/281916653933fb5c457ed7201c195299ea8cc03b/docker/build.py#L99-L107 the `latest` tag is added only for the stable releases.
