### ISSUE TITLE
Non-lambda UART string parsing

### ISSUE THREAD

**Issue by agrant-dxc** [esphome/feature-requests#1631]
**Describe the problem you have/What new integration you would like**

Yaml-based string parsing methods (delim, split, index array, trim, hex-->decimal, hex-->char, etc)

**Please describe your use case for this integration and alternatives you've tried:**

I keep running into sensors that leverage UART-based communication and while I can read the data using [Custom UART Device](https://esphome.io/custom/uart.html), and I can write yaml. I can't parse in C++ for the life of me.  So if the sensor output is a long series of hex values, I'm lost on how to consume it. Even if the datasheet sounds very straightforward.

Eg.  

![image](https://user-images.githubusercontent.com/98164417/153437551-9be28361-6a26-41da-a6ea-be565fb45aea.png)

**Additional context**

**Comment by nagyrobi** [comment]
Please contact us on the [Discord channel](https://discord.gg/KhAMKrd) for immediate support.
