### ISSUE TITLE
Button Custom Component (Enabling platform button.custom ?)

### ISSUE THREAD

**Issue by ClemensSchartmueller** [esphome/feature-requests#1638]
**Describe the problem you have/What new integration you would like**

Support for custom button components

**Please describe your use case for this integration and alternatives you've tried:**

For e.g. to trigger advanced actions on an esp8266 that cannot be easily implemented via esphome YAML directly. In my case it is a custom implemented catfeeder with servo and LED+LDR as encoder. An "ugly" workaround would be to use a custom switch component that automatically resets its state.

**Additional context**

The Button class already provides a virtual press_action method ( https://esphome.io/api/classesphome_1_1button_1_1_button.html#aed3ec50ca7cbdb8c036eb77e3bae5609 ) to be overwritten for custom button implementations. (Not knowing ESPHome's core logic) adding the configuration platform button.custom may already do the trick? Tutorial and doc could be easily adapted from the "custom switch component" documentation.

**Comment by rum0s** [comment]
+1 That would also be helpful for me, triggering a 433 command.
At the moment I also use the "ugly" workaround...

**Comment by nagyrobi** [comment]
Using a Template Button this is possible: https://esphome.io/components/button/template.html
