### ISSUE TITLE
nodemcu

### ISSUE THREAD

**Issue by erenuzz** [esphome/feature-requests#1662]
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by erenuzz** [comment]
I made a project with nodemcu and I want my phone to connect to nodemcu first, let's say there are different networks, let's connect to nodemcu first, and let's say the phone is connected to different wifi, if the phone sees nodemcu, it should leave the network it is connected to and connect to nodemcu . How can I do it.

**Comment by nagyrobi** [comment]
Please ask this kind of question on the Discord channel.
