### ISSUE TITLE
Icon template for ESPHome covers

### ISSUE THREAD

**Issue by srk23** [esphome/feature-requests#167]
**Describe the problem you have/What new integration you would like**
Within HA, it is possible to set an icon_template for a cover, to allow the icon state to change when the cover opens/closes; e.g.:

```
icon_template: >-
  {% if is_state('binary_sensor.left_garage_door_status', 'on') %}
    mdi:garage-open
  {% else %}
    mdi:garage
  {% endif %}
```
ESPHome covers do not currently support this customisation.  It would be useful, for example, for a garage door cover, based on the simple garage door cookbook: https://esphome.io/cookbook/garage-door.html

**Please describe your use case for this integration and alternatives you've tried:**
Current workaround is to create the switches/sensors in ESPHome, and the cover in HA.  It would be good to be able to create the whole thing in EPSHome.

**Additional context**

**Comment by OttoWinter** [comment]
Nope, not possible. Icons (and a few other properties) are intentionally static in esphome - it makes a lot of core code much easier and the protocol much simpler. That rules out templates.
