### ISSUE TITLE
Automation on camera snapshot

### ISSUE THREAD

**Issue by Strixx76** [esphome/feature-requests#1673]
**Describe the problem you have/What new integration you would like**

Possibility to add an automation before a snapshot is taking or an stream is opened with the ESP32 Camera Web Server Component, and another after.

**Please describe your use case for this integration and alternatives you've tried:**

To be able to turn the camera light on and of when the camera is accessed.

**Additional context**

**Comment by nagyrobi** [comment]
Implemented `on_stream_start` and `on_stream_end`: https://esphome.io/components/esp32_camera.html?highlight=Automations#
