### ISSUE TITLE
Analog_threshold - allow threshold to be defined by another sensor

### ISSUE THREAD

**Issue by Plawasan** [esphome/feature-requests#1676]
I have a bed occupancy sensor configured as follows:

```
  - platform: template
    name: "Bed Occupancy"
    device_class: "occupancy"
    lambda: |-
      if (id(bed_pressure).state < id(bed_pressure_threshold).state) {
        return true;
      } else {
        return false;
      }    
```
'bed_pressure_threshold' is coming from home assistant - I prefer to use external values so that I don't need to recompile ESPHome..

```
  - platform: homeassistant
    id: bed_pressure_threshold
    name: "Bed Pressure Voltage Threshold"
    entity_id: input_number.bed_pressure_threshold
    accuracy_decimals: 2
    internal: true
```

I wanted to replace that with the new integration, however I don't think I can use the state of another sensor as the threshold...    
 
Ideally something like this:

```
  - platform: analog_threshold
    name: "Garage Door Opening"
    sensor_id: bed_pressure
    threshold_id: bed_pressure_threshold
```

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by nagyrobi** [comment]
Please contact us on the [Discord channel](https://discord.gg/KhAMKrd) for immediate support.
