### ISSUE TITLE
ESP32 Camera on screen data / overlay (i.e. date/time)

### ISSUE THREAD

**Issue by daenny** [esphome/feature-requests#168]
**Describe the problem you have/What new integration you would like**
I would like to overlay the current time/date overlaid on the camera image. 
I have an automation which takes a snapshot and sends me the picture via telegram, but I had it sometimes that the picture was out-dated. So a capture time overlaid on the image (as for instance zoneminder does, see below) would be nice to see that the picture is updated. 

![Screenshot_2019-04-09_09-04-46](https://user-images.githubusercontent.com/3392004/55779752-9ad17500-5aa6-11e9-9ceb-dba3b1b9eed7.png)

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by nickrout** [comment]
I winder if this is something best left to home assistant?

**Comment by OttoWinter** [comment]
Not possible. The ESP just forwards the already-encoded JPEG directly from the camera module to HA. Because it's already encoded, we can't change any pixels directly - that would only be possible if the camera module could do that by itself.

**Comment by daenny** [comment]
I have seen some examples which paint rectangles on detected faces. But they then probably decode and encode the image, I guess, and I see why this might be a bit out-of-scope.  
Ok, maybe it would possible to add that "on receive" in the esphome/camera component in HA?
