### ISSUE TITLE
Megadesk Integration

### ISSUE THREAD

**Issue by JonathanTreffler** [esphome/feature-requests#1684]
**Describe the problem you have/What new integration you would like**
I would like an integration for the ["Megadesk"](https://github.com/gcormier/megadesk) open source controller board replacement for the IKEA Bekant Standing Desk.

**Please describe your use case for this integration and alternatives you've tried:**
This can be used to control the height and settings of the Desk over esphome, turning the original "dumb" up and down button Bekant Desk into a fully smart one, making it pretty much the cheapest prebuilt option for a smart standing desk.

The Developer of Megadesk offers code to make it work with [esphome](https://github.com/gcormier/megadesk/blob/master/esphome.md), but it is a bit messy and harder for a beginner to add to their esphome configuration.

**Additional context**
The Megadesk controller itself has no Wifi/Bluetooth capabilities, but it offers a uart connector.
This is only applicable to IKEA Bekant desks with the control board swapped with a Megadesk.

**Comment by nagyrobi** [comment]
> The Developer of Megadesk offers code to make it work with [esphome](https://github.com/gcormier/megadesk/blob/master/esphome.md), but it is a bit messy and harder for a beginner to add to their esphome configuration.

Please ask this request to the Megadesk author to submit a PR to ESPHome repo in order to include his component.
