### ISSUE TITLE
add a "rename" action in the dropdown menu of a node, in home-assistant's esphome dashboard

### ISSUE THREAD

**Issue by Ironirc** [esphome/feature-requests#1703]
**Describe the problem you have/What new integration you would like**

I tried different ways, resulting in different sorts of connection loss.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by nagyrobi** [comment]
There's a small pen icon in the device settings, near _Device info_ - just for that.

**Comment by Ironirc** [comment]
We 're clearly talking about something different?
![image](https://user-images.githubusercontent.com/10418880/163573971-90aa9447-b1d5-4ab2-8c4b-a8d01af70153.png)

**Comment by nagyrobi** [comment]
Ah there. Just rename the yaml file.

**Comment by nielsnl68** [comment]
I like to have this option as well. 
Yes i know you can do that but it would be cleaner when the dashboard take the action. 
It takes 2 compile sessies and uploads om a device to rename. 
fist with the changed name and wifi: use_address: old_address.
and a second time where we removed the use_address again.

My suggestion would be that the filename is the current name used for mDNS resolve.
when the esphome name is changed after the file is uploaded correctly the filename is changed to the new name.

**Comment by x0001346** [comment]
This would be a really useful feature.
In my case, so far I have 26 devices and due to a bad naming scheme I used I need to change the name of most of them.
I have already changed the name of some of them but this is prone to error and is easy to lose the connection with the device, this is specially con concerning since I'm not able to physically access the device.

**Comment by pat1300** [comment]
I would also love this feature :-)

**Comment by glmnet** [comment]
Done in 2022.5.0 https://esphome.io/changelog/2022.5.0.html
