### ISSUE TITLE
Support for Adafruit QT Py ESP32-S2

### ISSUE THREAD

**Issue by GitHubGoody** [esphome/feature-requests#1707]
Describe the problem you have/What new integration you would like
Support for the Adafruit QT Py ESP32-S2 (https://learn.adafruit.com/adafruit-qt-py-esp32-s2)

Please describe your use case for this integration and alternatives you've tried:
I'm trying to get this board to work with HA using ESPHome. I get various errors.

Additional context
No

**Comment by GitHubGoody** [comment]
This board is now listed in the PlatformIO registry.

https://registry.platformio.org/platforms/platformio/espressif32/boards

**Comment by nagyrobi** [comment]
https://github.com/esphome/feature-requests/issues/996
