### ISSUE TITLE
Better guiding of users when it comes to binary size 

### ISSUE THREAD

**Issue by frog32** [esphome/feature-requests#1710]
**Describe the problem you have/What new integration you would like**

When updating from a previous version my binary seemed to have grown over the threshold which resulted in an error being thrown when trying to upload to my esp8266 (4MB flash) using OTA.
This feature request is to provide better errors and some guidance on what binary size would work using OTA vs when we would have to switch to programming using a serial connection.
In my specific case OTA stopped working around 47% flash usage. It would be great to guide users towards how to reduce flash usage (I reduced the size of some of the descriptions and reduced logging to info (not sure if that part reduced the binary).

**Please describe your use case for this integration and alternatives you've tried:**

Going over the size limit for OTA doesn't result in actionable errors.

**Additional context**

HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|-- <noise-c> 0.1.4
|   |-- <libsodium> 1.10018.1
RAM:   [====      ]  41.2% (used 33732 bytes from 81920 bytes)
Flash: [=====     ]  47.8% (used 499204 bytes from 1044464 bytes)

**Comment by nagyrobi** [comment]
this has been mitigated by introducing gzipped binaries over ota
