### ISSUE TITLE
OpenHASP as ESPHome module (LVGL)

### ISSUE THREAD

**Issue by nagyrobi** [esphome/feature-requests#1721]
**Describe the problem you have/What new integration you would like**
There's OpenHASP: https://openhasp.haswitchplate.com making possible nice stuff like:
![cc-demoscreens](https://user-images.githubusercontent.com/1550668/126154224-11aab55f-8a20-4069-91de-b619ee54f851.png)

There's the new [LCD menu](https://github.com/esphome/esphome/pull/3406) PR implementing the concept of associating menu elements to ESPHome components (currently _select_, _number_ and _switch_). This concept could be also easily extended over OpenHASP. 

OpenHASP creates drawable [objects](https://openhasp.haswitchplate.com/0.6.2/design/objects/) based on LVGL library, these have various properties but the most important part is that these can also get/set values in similar ways. ESPHome's _select_, _number_, _switch_, etc. can be easily matched to OpenHASP's drawable objects:

| ESPHome component | OpenHASP object types |
| ---- | ---- | 
| switch, binary sensor |  binary and toggle types
| number, sensor |  range, some visual types
| select |  selector types
| text |  labels

OpenHASP also has a [groupid](https://openhasp.haswitchplate.com/0.6.2/configuration/gpio/#group) property which can be set for each object, intended to link drawn objects' values with GPIO-related peripherals' values. So theoretically this is compatible with the concept above, ESPHome's components have to be put in OpenHASP's groups to link their values to each other.

OpenHASP uses JSON lines to configure each object functionality and appearance, this could be kept and passed on like a lambda. Also it has its own way to connect to display gpios, this could also be kept but moved in an ESPHome YAML config section.

**Please describe your use case for this integration and alternatives you've tried:**
ESPHome and OpenHASP advantages could be combined into one:
- ESPHome has exceptional Home Assistant integration support and can handle a plethora of periplerals
- OpenHASP offers an exceptional implementation of LVGL to make interactive user interfaces

No need to reinvent the wheel on any of the sides. Currently ESPHome lacks of such a great possibility to draw a graphical UI, and OpenHASP lacks a way to easily integrate external peripherals and run complex automations locally.

Should be easier to implement than Tasmota did.

**Additional context**
OpenHASP's author @fvanroie made a few tests:
https://github.com/fvanroie/esphome-lvgl
https://www.youtube.com/watch?v=9A8NO0gWaAI

**Comment by fvanroie** [comment]
Take a look at the https://github.com/nielsnl68/SwitchPlate project which aims to integrate LVGL into ESPhome.

**Comment by nagyrobi** [comment]
Work in progress, LVGL will be natively supported by ESPHome: https://github.com/esphome/esphome/pull/6363

![lvgl_main_screenshot](https://github.com/esphome/feature-requests/assets/1550668/49a09052-03ae-4711-826e-197623493e33)

**Comment by nagyrobi** [comment]
Done: https://esphome.io/components/lvgl/
