### ISSUE TITLE
LED Status Indicator

### ISSUE THREAD

**Issue by digitaldias** [esphome/feature-requests#1724]
**Describe the problem you have/What new integration you would like**
I would like the ability to connect an LED, or use the built-in LED on my D1_Minis to shine their status to me, so that I can, at a glance, see that everything is ok or not. I propose: 
- LED is on permanently: Normal Operation, all is OK
- 3 blinks (1 per second), followed by 3 seconds of silence, repeat: No WIFI Connection
- Rapid blinks: Some other error state, i.e. device unavailable, or no response from pin - that kind of trouble

**Please describe your use case for this integration and alternatives you've tried:**
It would be nice to see at a glance if that LED is trying to tell me something or not

**Additional context**
Could for example call this `led_health` and configure it something like this: 
```yaml
led_health:
  led_pin: D4
  led_on: LOW
```
> The d1 mini turns the LED on when the D4 pin is LOW. Turns it OFF when the D4 pin is HIGH

**Comment by jesserockz** [comment]
Closing as this exists and `effects` can be created for custom states
https://esphome.io/components/light/status_led.html
