### ISSUE TITLE
Make Option to rotate the camera image in ESP32-Camera

### ISSUE THREAD

**Issue by rreinhardd** [esphome/feature-requests#174]
**Describe the problem you have/What new integration you would like**
This is a Feature Request for ESP32-Camera Component: Option to Rotate the Camera Image.

**Please describe your use case for this integration and alternatives you've tried:**
I have set up the AI-Thinker Cam Board and it works perfect. But when i want to install the ESP-Board in a 3D printed case vertically, the image is 90° rotated. The funtions "vertical_flip" and "horizontal_mirror" do not solve the issue, since they both "rotate" the image 180°. Ideal would be a option: "rotate: xx" - Possible options beeing "90", "180" and "270" degrees.

**Additional context**

**Comment by OttoWinter** [comment]
See also https://github.com/esphome/feature-requests/issues/168

This is not possible unless the camera module itself supports it (and from a brief look in the datasheet that is not the case)
