### ISSUE TITLE
Will it support esp now protocol?

### ISSUE THREAD

**Issue by ChristianSwift** [esphome/feature-requests#1745]
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

espressif already release a protocal called [esp now](https://www.espressif.com/en/products/software/esp-now/overview), it can transmit data between two or more esp chips fast and efficiency, i hope esphome could make it.

**Comment by SeByDocKy** [comment]
I saw somewhere an attempt to integrate ESPnow into ESPhome but .... seems in stand by seems several weeks.

**Comment by nagyrobi** [comment]
Duplicate of https://github.com/esphome/feature-requests/issues/275
