### ISSUE TITLE
Add Timer support

### ISSUE THREAD

**Issue by Pro-Control** [esphome/feature-requests#1757]
**Describe the problem you have/What new integration you would like**
Timer Platform like in HA 

**Please describe your use case for this integration and alternatives you've tried:**
I use binary_sensor template with delay simulate timer after  
and don't find any solution for timer before  

**Additional context**
 has after like  turn off my light after sunrise  in 30min
 and before like turn on my light before sunset in 1h

**Comment by glmnet** [comment]
I know is not you're asking but using a script is really very straightforward to do this, sliding and reentrant timers. 

https://esphome.io/guides/automations.html#timers-and-timeouts
