### ISSUE TITLE
QR Code processing

### ISSUE THREAD

**Issue by apeeters** [esphome/feature-requests#176]
**Describe the problem you have/What new integration you would like**
Add support for processing QR Codes in Esphome.

**Please describe your use case for this integration and alternatives you've tried:**
Currently esphome can pass the raw camera feed and process the qr code in Home Assistant. This causes a lot of network traffic. It would be nice to have esphome determine the QR code itself.

**Additional context**
This code might help for the implementation https://github.com/donny681/ESP32_CAMERA_QR

**Comment by OttoWinter** [comment]
This is currently not the goal of the ESP32 camera platform in esphome. The goal for esphome is only to publish raw images to another system (like HA) to process the data.

I don't want to open the can of worms that image processing is. While it's definitely cool what can be done, for that to work esphome would need a central image processing component.

> This causes a lot of network traffic

I don't think it's really that much. The JPGs that are sent are a couple of kb each, plus for QR code reading you don't need large framerates/frame sizes/compression levels.
