### ISSUE TITLE
"Alarm Control Panel" core component

### ISSUE THREAD

**Issue by KC-inDomus** [esphome/feature-requests#1773]
**Describe the problem you have/What new integration you would like**
Having an Alarm Control Panel core component

**Please describe your use case for this integration and alternatives you've tried:**
As in Home Assistant an [Alarm Control Panel](https://www.home-assistant.io/integrations/alarm_control_panel/) is available, could be very useful having something like that on esphome, letting users to define alarm control panel logics on the firmware and exporting functions as alarm_control_panel.* entity on the HUB.

**Additional context**
-

**Comment by rarroyo6** [comment]
I vote for this.

**Comment by KC-inDomus** [comment]
still interested ☺️

**Comment by KC-inDomus** [comment]
no one elses? ;)
