### ISSUE TITLE
Web Server Component - allow custom order of elements

### ISSUE THREAD

**Issue by MagMeister** [esphome/feature-requests#1774]
In web server V1, the order in which elements are displayed in the web interface are determined by type (sensor, switch, ...) and the order in which they appear in the configuration file.

Since web server V2 the order is alphabetical by name.

It would be useful if it were possible to define an order for each element, in the style of a "z-index" and in second, the sorting could then be done alphabetically.

**Comment by dmachadol** [comment]
Any update?

**Comment by jaggzh** [comment]
Yeah this is annoying.  Perhaps:
1. Sort type: Defaulting to "alpha by name" for v2 backwards compatibility?
2. Sort type: "index", uses an item's "sort_index: #" value (default 0).  No errors -- components with the same index # receive the same rank and, thus, an arbitrary order.

For optional grouping, higher up hierarchy components could possibly also allow sort_index, where the sort would bring their children together.  If not specified, perhaps a default of -1 would be useful, where they do not receive a sort.  OR we have a "sorted: true/false" on them.

I'm a bit new to esphome config so I'm not sure how compatible this all is with the config philosophy.

**Comment by bilbs84** [comment]
For certain, I think this would be a fantastic idea.  If only for testing and development.  I usually interface with all my devices through HA, but when setting up a new device, getting it's calibrations right, etc, I do use the web server component, and it can be quite annoying when you have sensors that should be grouped, be at opposite ends of the list.

I hope something like this does get implemented in a future release.

**Comment by smarthomedesign** [comment]
hello all, i guess this idea wan not implemented ?

**Comment by MagMeister** [comment]
This has been addressed by the [entity sorting](https://esphome.io/components/web_server#config-webserver-sorting) and grouping in web server V3.
