### ISSUE TITLE
Add Waveshare 2.13 inch B72 epaper display support

### ISSUE THREAD

**Issue by Tzaphkiel** [esphome/feature-requests#1779]
**Describe the problem you have/What new integration you would like**

I have a **Waveshare 2.13inch e-Paper HAT** display that does not work with *Home Assistant* and *ESPHome*.
My arduino code tests with this display show that the **B72** version of the display should be used.

**Please describe your use case for this integration and alternatives you've tried:**

Using the e-Paper disaply with HA and ESPHome does not allow me to display properly the content.
The text appears with some of the models available but the screen is not completely blanked or clean thereafter.
Looking at the ESPHome waveshare_epaper components code, there are different models available but not the one that I found to be working with my Arduino code: **B72**.

**Additional context**

Code to integrate:
* https://github.com/ZinggJM/GxEPD2/blob/master/src/epd/GxEPD2_213_B72.h
* https://github.com/ZinggJM/GxEPD2/blob/master/src/epd/GxEPD2_213_B72.cpp

![BB71FE2F-7574-4513-AE94-52F36233E0CF](https://user-images.githubusercontent.com/644489/175765703-39cbc854-6ed3-425b-b687-0d8f68e93190.jpeg)
![24168856-D877-411D-B2E5-9D5359DBA958](https://user-images.githubusercontent.com/644489/175765706-d1f5e1be-6a4a-4870-ad93-a2cb0bccb171.jpeg)

I am willing (and probably mostly able) to integrate it. I do not feel confortable delivering it to the full project.
I will see if I can start and submit a 'draft' PR to the project at some point.

**Comment by Tzaphkiel** [comment]
Thank you !

**Comment by acfnews** [comment]
> I am willing (and probably mostly able) to integrate it. I do not feel confortable delivering it to the full project. I will see if I can start and submit a 'draft' PR to the project at some point.

Hi Tzaphkiel,

Can you help me push me in a direction for implementing another display? 
I am a bit overwhelmed, and not sure where to start.
My opened ticket: [new](https://github.com/esphome/feature-requests/issues/2696)

**Comment by Tzaphkiel** [comment]
Hi @acfnews, I suggest going the same route I did and prove this display works with one of the drivers available gxepd2 repo above. 

I did that by using an arduino or esp standalone with the arduino ide and getting it to work first; not through esphome. 

You then can report about it in your ticket to help the devs or follow the integration done in this pull req!
