### ISSUE TITLE
Update espressif32 from 3.5.0 to 5.0.0 to fix C3 and S3 boards

### ISSUE THREAD

**Issue by bruvv** [esphome/feature-requests#1791]
**Describe the problem you have/What new integration you would like**
The current espressif32 is very old (5 months) and therefor there are issues with C3 and S3 esp32 boards.
Currently v5.0.0 is just released: https://registry.platformio.org/platforms/platformio/espressif32/versions

**Please describe your use case for this integration and alternatives you've tried:**
I tried updating myself but I failed

**Additional context**

**Comment by ma-lalonde** [comment]
Now at 5.1.1 but still. Supporting to add several Ethernet PHYs compatibility

**Comment by hapklaar** [comment]
Can't you choose the version to use in the yaml?

https://esphome.io/components/esp32.html

**Comment by p2baron** [comment]
> Can't you choose the version to use in the yaml?
> 
> https://esphome.io/components/esp32.html

You can only choose between recommend, latest and dev.
Dev currently gives you version 5.2.0

**Comment by bruvv** [comment]
@p2baron you can it is in the URL:
```
esp32:
  board: nodemcu-32s
  framework:
    type: arduino
    version: 2.0.0
```
