### ISSUE TITLE
ESPHome to print the esp_reset_reason on startup

### ISSUE THREAD

**Issue by crgarcia12** [esphome/feature-requests#1817]
**Describe the problem you have/What new integration you would like**

ESPHome should populate in the logs the esp_reset_reason()
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/misc_system_api.html#_CPPv416esp_reset_reasonv

For example:
```
// Pseudo-code
main()
{
      esp_reset_reason_t reset_reason = esp_reset_reason();
      debug_log("ESP Reset reason: " + reset_reason);
      ...
```

**Please describe your use case for this integration and alternatives you've tried:**

My ESPHome ESP32 is resetting by itself, I suspect a problem with the powersupply, but I cannot be 100% sure

**Additional context**

**Comment by nagyrobi** [comment]
Please contact us on Discord dev channel to discuss this, and also make a PR against the main esphome repo with your suggestion to be reviewed.
