### ISSUE TITLE
Display User created Folders in Dashboard

### ISSUE THREAD

**Issue by benquan** [esphome/feature-requests#1821]
**Describe the problem you have/What new integration you would like**

User created folders do not display on the dashboard. They should appear on the dashboard to allow users to navigate in these files and allow editing files within.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by lcavalli** [comment]
Duplicate of #867?

**Comment by nagyrobi** [comment]
Yes, thank you.
