### ISSUE TITLE
use ESP-Button for Support of Double and Single Click

### ISSUE THREAD

**Issue by franz-ms-muc** [esphome/feature-requests#1823]
**Describe the problem you have/What new integration you would like**

https://github.com/espressif/esp-iot-solution/tree/master/components/button
this is a very cool Button Class. 
Support LONG Press, Click, Double Click, and so on. 

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by nagyrobi** [comment]
See https://esphome.io/components/binary_sensor/index.html?highlight=click#binary-sensor-automation
