### ISSUE TITLE
M5Stamp C3

### ISSUE THREAD

**Issue by boklubre** [esphome/feature-requests#1827]
Hello,

I wanted to try out a few things with an M5Stamp C3.
Unfortunately, it was not possible to run "Prepare for Adoption" via the WEB installer because the M5Stamp C3 is not recognised.

I then tried to compile a script for the ESP32-C3 for manual flashing. Unfortunately, it always aborts the compilation.

Are there any plans to support the ESP32-C3 and especially the M5Stamp C3?

Cheers

Boris

**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by nagyrobi** [comment]
Please head on to our Discord server with support questions. This is only for new features.
