### ISSUE TITLE
add Xiaomi MJ_HT_V1 as compatible with xiaomi_ble sensor platform in explanation

### ISSUE THREAD

**Issue by thatso** [esphome/feature-requests#1831]
**Describe the problem you have/What new integration you would like**

Xiaomi MJ_HT_V1 seems to be another name for the LYWSDCGQ temperature and humidity sensor.

**Please describe your use case for this integration and alternatives you've tried:**

Reading the [ESPHome xiaomi_ble sensor platform](https://esphome.io/components/sensor/xiaomi_ble.html) explanation, I wondered why the popular MJ_HT_V1 temperature and humidity sensor was not mentioned but instead LYWSDCGQ. Turns out that HA's own Xiaomi BLE integration names the MJ_HT_V1 as "LYWSDCGQ by Xiaomi" on the device info page.
This fact should be added to the ESPHome page to make it clear that these are identical devices by another name.

**Additional context**

**Comment by nagyrobi** [comment]
Please submit a PR with your suggestion.
