### ISSUE TITLE
Add battery sensor for Airthings Wave Plus (if possible)

### ISSUE THREAD

**Issue by magenbrot** [esphome/feature-requests#1832]
**Describe the problem you have/What new integration you would like**

I'm missing a battery sensor for the airthings_wave_plus 

**Please describe your use case for this integration and alternatives you've tried:**

Is it possible to add a battery sensor for the airthings_wave_plus? I can see the battery level in the mobile app, so maybe it's not a big thing?

**Additional context**

**Comment by MadMonkey87** [comment]
seems to be possible, see https://esphome.io/components/sensor/airthings_ble#battery-level-reporting

**Comment by kpfleming** [comment]
This has been available for a few months now.
