### ISSUE TITLE
"Simple Mode" aka Config generator

### ISSUE THREAD

**Issue by Aaroneisele55** [esphome/feature-requests#1833]
Describe the problem you have/What new integration you would like
For me as newbie in ESPhome, it is sometimes difficult to write the config.yaml (besides what's possible with "esphome wizard filename.yaml") for e.g Sensors of DIsplays. The Solution to this could be some sort of UI for making the config (Input Fields for WI-FI, Name, ... and Then some kind of "Select Features" Dialog where you can (with a search field) search for and add components like MQTT, sensors or GPIO Switches
Please describe your use case for this integration and alternatives you've tried:
It would make config very much easier for new users

**Comment by apbodrov** [comment]
Hello! I'am currently working on that feature in my repo.
There is a first version demo  https://esphome-yaml-constructor.vercel.app/
Repo https://github.com/apbodrov/esphome-yaml-constructor
