### ISSUE TITLE
database update interval configuration option in xiaomi_lywsd03mmc  component

### ISSUE THREAD

**Issue by yaydogan** [esphome/feature-requests#1835]
**Describe the problem you have/What new integration you would like**

I am using ESP32 + Xiaomi lywsd03mmc temperature/humidity sensors with customer firmware. By default, sensors update the temperature and humidity every 10 secs. This will create a large amount of data from these sensors (I have 5+ around the house) over time. 

I have changed the firmware setting to update temperature/humidity every minute to reduce the amount of data but the disadvantage is the LCD display on the sensors also update at 1 min interval. 

What I would like to do is the sensors update the temperature/humidity readings every 10 secs so that it is near real time on LCD display but ESPHome sends the sensor values to database at a different interval (e.g. 5 mins). There is no configuration option in xiaomi_lywsd03mmc  component for database update interval. Can it be added?

Thanks!

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by nagyrobi** [comment]
Add a throttle filter to the sensor:
```
filters:
  - throttle: 300s
```
See https://esphome.io/components/sensor/index.html#throttle

Please head on to our Discord server for such support questions.
