### ISSUE TITLE
BLE Tracker Proxy MAC based sensor

### ISSUE THREAD

**Issue by atheon25** [esphome/feature-requests#1880]
**Currently BLE Tracker proxy creates additional sensors if same BLE are configured to more than one devices. Make sensor to be MAC based and enable to possibility add same configuration BLE proxy to extend range and cover weak signals**

**I have several RuuviTag around my house. Few of those tags are in place where signal are weak for all places inside of house. I use Atom BLE-Tracker-proxy to relay entites to Home Assistant. Problem here are signal are not reliable to any single points, but it is reachable from several proxy device.**

**Earlier I use my frend BLE-sensor code to relay entities to Mqtt. His system handled sensor based to MAC and report sensor value to single entities thru several BLE-sensor mqtt bridge [ble-sensor](https://github.com/Wenlin88/ble-sensors).**

**Comment by nagyrobi** [comment]
This already works like you'd like to. But please clarify:
- What's an _Atom BLE-Tracker-proxy_?
- How do you configure your RuuviTags? In ESPHome, or directly in Home Assistant?

**Comment by nagyrobi** [comment]
Did you see there's a HA custom component for RuuviTags?
https://github.com/ruuvi-friends/ruuvi-hass.io

**Comment by atheon25** [comment]
Yes I saw that, but i'm notsure how it works with BLE-tracker-proxy.
Those BLE-tracker proxy are crucial because many of those RuuviTag is far from Home assistant device.

**Comment by nagyrobi** [comment]
Can't help unless you provide answers

**Comment by atheon25** [comment]
[Atom BLE-tracker-proxy](https://esphome.github.io/bluetooth-proxies/)

**Comment by nagyrobi** [comment]
Not clear what are you referring to as _Atom_.

But anyway, you shouldn't configure the tags in ESPHome at all. To use the benefits of the new proxy functionality, you have to configure them in Home Assistant directly.

**Comment by atheon25** [comment]
Atom I mean M5Stack Atom.
So you mean in ESPHome I should have only ruuvi_ble configured and ruuvi-frend confiquration my configure.yaml

Let me try that....

**Comment by nagyrobi** [comment]
No. Delete entirely the ruuvi_ble from ESPHome node proxy.

**Comment by atheon25** [comment]
OK it work but only partially.
ie. RuuviTag humidity in gauge card give me Entity is non-numeric: sensor.storage_humidity

am I still do something wrong?
I reprogram ESP32 with proxy software from ESP home bluetooth-proxy and didn't add anything.
I also add ruuvi-friends type of configurations to configuration.yaml
Now I see all entities in list but not get those working in any standard or custom card proberly.

**Comment by nagyrobi** [comment]
You have to raise that as issue to the custom component author.
