### ISSUE TITLE
Sprinkler - Add "divider" option as an alternative to "repeat".

### ISSUE THREAD

**Issue by Zebble** [esphome/feature-requests#1891]
The "repeat" function will run the cycle the number of times provided by the repeat value.  It would be great to also have a "divider" option that can repeat the cycle by the "divider" number of times, within the existing valve times.

For example:

Valve 1:  600 seconds
Valve 2:  300 seconds
Valve 3:  100 seconds

(total of 1000 seconds)

Using a repeat value of 2, the cycle would run twice for a total of 2000 seconds.

If a divider value of 2 was provided, the total cycle time would stay at 1000 seconds.  The cycle would repeat 2 times and each valve would run for 1/2 the time.

Why is this a good idea?  It allows for a "soak" time for each valve.  It's often better to run each valve several times with breaks in between to allow the soil to absorb and avoid runoff.

I'm mimicking this behavior by grabbing a divider value from an HA interface and then running code on the ESPHome device that divides all the valve runtimes by the divider and sets the multiplier to the divider value.

**Comment by nagyrobi** [comment]
@kbx81
