### ISSUE TITLE
Sprinkler - Standby switch

### ISSUE THREAD

**Issue by Zebble** [esphome/feature-requests#1894]
Would be great to have a standby switch for the sprinkler component.

This would just be used to put the system into standby mode and prevent any cycles from being executed by any upstream automation, etc.

This could be used during winter or if the system needs to be worked on or paused for an extended period.

The start_single_valve action would probably make sense to be the only function that would ignore the standby setting.

**Comment by nagyrobi** [comment]
@kbx81
