### ISSUE TITLE
Add support for ESP32 based Lilygo T-Ethernet-COM board

### ISSUE THREAD

**Issue by unmesh59** [esphome/feature-requests#1904]
**Describe the problem you have/What new integration you would like**

I'd like to run ESPHome on the LilyGO T-Internet-POE board which has wired Ethernet and an embedded USB-to-serial converter that is wired to its USB-C port

https://github.com/Xinyuan-LilyGO/T-Internet-COM

Thanks

**Please describe your use case for this integration and alternatives you've tried:**

I would like to use it as a better Bluetooth Proxy than my current NodeMCU that uses WiFi backhaul and drops Bluetooth advertisements

**Additional context**

Please let me know if one of the existing supported platforms can be used as a base supplemented with additional configuration

**Comment by intermittech** [comment]
What is exactly the question or feature request here? Just configure the board, the documents are all there and the WiKi documentation of ESPhome shows you with configuration examples with what you need, so you can look it in the schematics and fill it in?

Ok, less snarky, it should be:

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 0 (or 1)
  power_pin: GPIO4 (or GPIO5)

p.s. As a friendly note maybe look for a board that also has an external antenna connector with which you can also improve range.

**Comment by nagyrobi** [comment]
Thanks
