### ISSUE TITLE
Feature Request for docs: add a cookbook for light effects

### ISSUE THREAD

**Issue by AalianKhan** [esphome/feature-requests#192]
**Describe the problem you have/What new integration you would like**

I would love to see the community grow and create their own sketches. Another way for the community to contribute and collaborate is to add a light effect cookbook section for the light component.

**Please describe your use case for this integration and alternatives you've tried:**

more people helping each other
**Additional context**

**Comment by OttoWinter** [comment]
Sure, such a cookbook entry can definitely be created. Someone just needs to do it.

I don't see why this is a feature request? Someone just needs to create a page with one (or more) example light effects. Then contributors can add more light effects.
