### ISSUE TITLE
Add support for the Person Sensor by Useful Sensors (SEN-21231)

### ISSUE THREAD

**Issue by kucau0901** [esphome/feature-requests#1925]
**Describe the problem you have/What new integration you would like**
Please add support for the Person Sensor by Useful Sensors (SEN-21231) so that we can have good presence detention using ML sensor

**Please describe your use case for this integration and alternatives you've tried:**
 i've been using IR and Microwave sensor for presence detection but it is not that reliable. using this sensor with built in ML can elevate presence sensor to the next level. And the cost of the sensor is relatively affordable, USD 10 

**Additional context**
 module info : https://github.com/usefulsensors/person_sensor_docs

**Comment by shreyaskarnik** [comment]
I have a work-in-progress implementation here: https://github.com/shreyaskarnik/esphome-components. Connected to the default sda and scl pins for esp32.
