### ISSUE TITLE
SFA30 Support

### ISSUE THREAD

**Issue by iLeopod** [esphome/feature-requests#1926]
**Add Support for Sensirion SFA30 sensor**

https://github.com/Sensirion/arduino-i2c-sfa3x
https://sensirion.com/products/catalog/SFA30/

**Comment by ghsensdev** [comment]
Does anyone plan to implement this component?
Does anyone have this sensor?

I plan to buy one and implement the component for it.

**Comment by ghsensdev** [comment]
Hello,

I bought this sensor, and implement a component for it.

I have a pull request that needs a code review.

Can someone help me what I have to do next?

**Comment by nagyrobi** [comment]
Thank you for your effort. Now it's time to sit back and wait for it to be reviewed.

**Comment by ghsensdev** [comment]
Should I choose a reviewer or one of them will notice the pull request some time?

**Comment by nagyrobi** [comment]
No need to choose a reviewer. It may take quite a long time as they are overwhelmed.

**Comment by ghsensdev** [comment]
It has been merged to dev, thanks. @jesserockz, in the next release will it be available?

**Comment by iLeopod** [comment]
[12:54:43][D][sensor:094]: 'Formaldehyde': Sending state 21.60000 ppb with 1 decimals of accuracy
[12:54:43][D][sensor:094]: 'Humidity': Sending state 65.71000 % with 2 decimals of accuracy
[12:54:43][D][sensor:094]: 'Temperature': Sending state 19.36500 °C with 2 decimals of accuracy`

Test works great so far:)
