### ISSUE TITLE
Allow ability to "queue" home assistant service calls.

### ISSUE THREAD

**Issue by geiseri** [esphome/feature-requests#1927]
**Describe the problem you have/What new integration you would like**

I have a situation where a device is in deep sleep.  I have a touch-based wakeup that allows the screen to display almost instantly.   Then I can select an option that calls a HA service to consume a product from grocy.  The issue is that my kid will tap to wake it up, but then hit the selection and run off.  The service call never gets to HA, and then after a 30sec timeout it goes back to sleep.

**Please describe your use case for this integration and alternatives you've tried:**

Right now, I put a "please wait" screen that blocks the selection option.  Sadly, the result is that my kid's impatience causes them to not even bother with selection.  I was going to try to "queue" it manually, but the lambda for it is starting to look like a crime against my future self.

**Additional context**

This is a battery-operated device in my pantry, so I want to have it offline as much as possible.

**Comment by nagyrobi** [comment]
Please ask for solution in our Discord channel. Your request can likely be done.
