### ISSUE TITLE
airthings_wave_plus support for Illuminance and battery

### ISSUE THREAD

**Issue by leroyloren** [esphome/feature-requests#1935]
**Describe the problem you have/What new integration you would like**

Please add support for the illuminance sensor and battery that the device supports.

**Please describe your use case for this integration and alternatives you've tried:**

I would like the integration to support the display of light intensity and battery status

**Additional context**

**Comment by MadMonkey87** [comment]
Just had the same problem. The battery can acually be shown, see https://esphome.io/components/sensor/airthings_ble#battery-level-reporting
The illuminance currently don't work but from the code there is already something there, I'll try to get it up and running
