### ISSUE TITLE
Blueprints or Templates

### ISSUE THREAD

**Issue by jman203** [esphome/feature-requests#1946]
**Describe the problem you have/What new integration you would like**

I currently have several devices that use the same yaml config with variables/substitutions that update the names for the devices. I envision a system similar to the Blueprint feature for Home Assistant automations where if I needed to make a change to the yaml, I could edit the Blueprint and then update each device instead of editing each yaml file.

I also think these Blueprints could be shared within the community for device specific Blueprint and people could enter device specific variables to quickly get a device up and running quickly. This could help make ESPHome more user friendly for beginners.

**Please describe your use case for this integration and alternatives you've tried:**

Currently I have several Sonoff S31's with ESPHome. I could edit the Blueprint and then all my S31's could be updated with the new configuration without editing each yaml file.

**Additional context**

I understand this would be a huge undertaking to build this feature. However, I think it would be worth the effort to make ESPHome more user friendly and easier to share projects within the community.

**Comment by nagyrobi** [comment]
ESPHome has a different concept for that, see [Packages](https://esphome.io/guides/configuration-types.html#packages).
