### ISSUE TITLE
Capacitive Soil Sensor Integration

### ISSUE THREAD

**Issue by NathanWilcox** [esphome/feature-requests#195]
**Describe the problem you have/What new integration you would like**

Please can you look into integrating a Soil Capacitance Moisture Sensor such as:
[https://www.banggood.com/5pcs-Capacitive-Soil-Moisture-Sensor-Not-Easy-To-Corrode-Wide-Voltage-Module-For-Arduino-p-1326816.html?rmmds=myorder&cur_warehouse=UK](url)

**Please describe your use case for this integration and alternatives you've tried:**

I have looked at similar requests for soil moisture sensors but they are not the same as these capacitance sensors. I have also looked for voltage to moisture conversion as stated in other posts but I cannot locate such information on the docs website.

**Additional context**

**Comment by OttoWinter** [comment]
Nah this is also an analog sensor. From the page:

> A miniature PC such as the Raspberry Pi only needs an external ADC (analog to digital signal) conversion module to work.

See the AVOUT pin for getting the data.
