### ISSUE TITLE
Write to Tuya MCU data points like Tasmota and Tuya iOT servers can

### ISSUE THREAD

**Issue by jazzmonger** [esphome/feature-requests#1956]
**Describe the problem you have/What new integration you would like**
Add support to Tuya MCU to write to datapoints just like the Tuya iOT servers and Tasmota TuyaMCU can

OR Just like Tasmota can.  Tragically, I've had to reflash away from ESPHome to Tasmota, because Tasmota supports this function.  Not that I don't think Tasmota is useful, but mostly for lights and switches, not more complex devices like a Wood Pellet Stove.  ESPHome is my GO TO Software for all things iOT.  Or at least it used to be.

DP NUMBERS AND THEIR FUNCTION ON MY STOVE:
1 - Power on (Heat). <--- writable now
4 - Mode P1/P2/P3P4  <--- NOT writable but needs to be
101 - ECO1/ECO2 <--- NOT writable but needs to be
104 - Error Code <- READ ONLY
106 - Set Temp <--- NOT writable but needs to be
107 - Current Temp <- READ ONLY
108 - Pipe Temp <- READ ONLY
109 - Protect Temp <- READ ONLY

-----------------
TuyaSend Command[~](https://tasmota.github.io/docs/TuyaMCU/#tuyasend-command)
Command TuyaSend is used to send commands to dpId's. It is required for dpId's that shouldn't be mapped to a fnId.
With this command it is possible to control every function of the dpId that is controllable, providing you know its data type and data length. With them provided, the rest of the protocol command is calculated.
Command's value consists of two comma separated parameters: dpId and data.
TuyaSend<x> dpId,data**
----------------

**Please describe your use case for this integration and alternatives you've tried:**
I have a newly reflashed TYWE01 Tuya module on my misbehaving wood pellet stove (the oem vendor app has serious bugs) and the set temp dp  controls the stove. It's the only way to set a desired temp on the stove. But there is no way to do this as dps are read only... climate controls don't work because there is no way to set the target temp inside the MCU of the stove. The only function that is bidirectional is the ON/OFF Switch which is dp 1.  If you can do it for dp 1, why not the rest of them????

**Additional context**
The same issue exists with ECO Mode (0 & 1) and the P1-P4 (0-3) power levels. I can read those values set via the front panel of the stove thru Tuya MCU in ESPHome, but there is no way to set them like the vendor app can up to the tuya data points in the Tuya servers and then back to the stove. Tuya MCU is unidirectional only, and limited by design.

the hesterysis of the stove is 3 degrees below set temp and 1 degree above. So I physically have to touch the buttons on the stove to control anything but on/off.

**Comment by jazzmonger** [comment]
Relevant Tasmota TuyaMCU docs:
https://tasmota.github.io/docs/TuyaMCU/

**Comment by ssieb** [comment]
It would be more helpful if you pasted the output from esphome where it dumps the datapoints and their types.
You can use either https://esphome.io/components/number/tuya.html for a number or https://esphome.io/components/select/tuya.html for an enum.  You can also directly write to datapoints if you need to.
https://esphome.io/api/classesphome_1_1tuya_1_1_tuya.html

I just looked at the linked issue and you did paste the info there.  So the modes are enums and the temp is a number.  However, you probably want to use https://esphome.io/components/climate/tuya.html anyway, since that covers most of it.

**Comment by jazzmonger** [comment]
If the vendor app is not written correctly as is in your example, tuya climate grabs the wrong dps because the vendor wrote two sets of dps for each attribute, then this is the is the only way to have a useable method to get or push data to the correct data point.
