### ISSUE TITLE
Add support for chipset CBU BK7231N and other tuya devices

### ISSUE THREAD

**Issue by BenPru** [esphome/feature-requests#1958]
**Describe the problem you have/What new integration you would like**
Add support for chipset CBU BK7231N and other tuya devices.
Use esphome on tuya devices with chip BK7231N/BK7231T

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by ssieb** [comment]
This is in progress: https://github.com/esphome/esphome/pull/3509

**Comment by BenPru** [comment]
Duplicate
