### ISSUE TITLE
MH-Z19 C02 Sensor

### ISSUE THREAD

**Issue by shawnhaywood** [esphome/feature-requests#1969]
**Describe the problem you have/What new integration you would like**

Not really a problem or feature request - I'm attaching a screenprint of the MH-Z19 sensor Home Assistant status screen.  I'm trying to verify the last time HA received a reading from the sensor.  I believe the 12 hours reflected on the screenprint is how long the sensor has been connected, but not the time since last update. Is this correct?  A review of the ESPHome log shows ESPHome is connecting to the device and retrieving the temp and co2.  

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

![Screenshot 2022-11-17 184411](https://user-images.githubusercontent.com/93692595/202604977-8f1047ea-e947-4c7e-9472-e95c4416f67d.png)

**Comment by nagyrobi** [comment]
Please ask in our Discord channel for faster response.
