### ISSUE TITLE
Current ssd1306_i2c display page in a sensor 

### ISSUE THREAD

**Issue by marrobHD** [esphome/feature-requests#199]
**Describe the problem you have/What new integration you would like**
I want to have a binary sensor button counter. I have set that with each push of a button the next display page is displayed. When the button is pressed for the 4th time, the counter should be reset to 0 and page 1 set. If you press the button twice in succession, a page should be selected for example 2. This page number should then be sent to Homeassistant. Then pages 4-5 should be changed in an interval of 5 seconds. After 15 seconds again pages 1-3 should be selectable

**Please describe your use case for this integration and alternatives you've tried:**
That is my code but it wont compile: https://hastebin.com/kiyadilite.pl

**Additional context**
Please add Sensor for the selected display page. Thanks for helping me

**Comment by OttoWinter** [comment]
All this can already be done with the existing automations. For keeping track of the page that is selected, use a global variable (you can then expose that via a template sensor to HA).

The display pages actually do not have any numbers associated with them, hence you need to track that with a global var yourself.
