### ISSUE TITLE
Snips.ai audio server

### ISSUE THREAD

**Issue by escoand** [esphome/feature-requests#2]
I tinkered a bit with [snips.ai](https://snips.ai) and found on the way https://github.com/Romkabouter/Matrix-Voice-ESP32-MQTT-Audio-Streamer and remembered it again today because of https://www.heise.de/newsticker/meldung/Gesichtserkennung-mit-ESP32-WLAN-Kameraboards-ab-15-Euro-4269519.html (despite this one additional uses a camera).

Do you see any chance to implement something like this in esphome as well?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Did you work on this @escoand ? Would be great, maybe I can help (esphome beginner though)

**Comment by escoand** [comment]
@h0jeZvgoxFepBQ2C no, your contributions are welcome ;-)

**Comment by rradar** [comment]
snips is dead - closing this

**Comment by ashald** [comment]
While Snips is dead - the Hermes protocol, as well as Rhasppy, seem to be pretty popular for voice-based automations.
The https://github.com/Romkabouter/Matrix-Voice-ESP32-MQTT-Audio-Streamer referenced in the top message is Hermes implementation that streams audio over MQTT - it'd be great to track this feature request.

Not sure I'll be able to contribute it, but I'm interested in making it work with ESPHome so might give it a try...
