### ISSUE TITLE
esphome add

### ISSUE THREAD

**Issue by outsiderz** [esphome/feature-requests#200]
how can add esphome to espressif SDK???

**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by nickrout** [comment]
esphome works with platformio not the espressif SDK.

**Comment by OttoWinter** [comment]
Try again please, please fill out the template and explain your question in more details. For example, there are many espressif SDKs. And as @nickrout said, I think you do not understand the way esphome operates.
