### ISSUE TITLE
Text Control that is not just sensor but editable

### ISSUE THREAD

**Issue by pedjas** [esphome/feature-requests#2002]
**Describe the problem you have/What new integration you would like**

There is need for control that allows user to enter free text as an value. Then that value could be used anywhere in code like statuses of every other control. It should produce edit box In web interface so user can type in value.

**Please describe your use case for this integration and alternatives you've tried:**

Users are pretty much limited to use hard coded or calculated string values. There is no option for them to enter some string value that needs to be typed in in runtime, like IP or URL to external web service or so. It is pretty limiting.

**Additional context**

**Comment by nagyrobi** [comment]
There is work in progress for that: https://github.com/esphome/esphome/pull/3638
