### ISSUE TITLE
Add ADC 2 support on ESP32 boards

### ISSUE THREAD

**Issue by skaterdude** [esphome/feature-requests#2016]
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

I've been configuring a variant of a Heltec WiFi Kit 32 board, which is an ESP32 VARIANT in the code.  When I try to use GPIO13 (ADC2:4), which on the schematic is tied to the VBAT voltage divider (to read the current state of the battery), I get an error from the ADC validation logic that ADC is not supported on this pin.  
"ESP32 doesn't support ADC on this pin."
It appears that none of the ADC 2 pins are included in the configuration.  ADC 2 is supported in the Espressif files, so it appears that this is just not carried into the platform code.

**Additional context**

While Heltec appears to have discontinued this board, variants are widely available.  Also, ADC 2 is a chip function, not specific to this board design.  It's listed on the ESP32-DevKitC board layout as well.

**Comment by ssieb** [comment]
You can't use ADC2 when you're using wifi.
