### ISSUE TITLE
Support for BP1658

### ISSUE THREAD

**Issue by BBart19** [esphome/feature-requests#2023]
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

Hello , I would like to ask for support for BP1658 , This is a led controller that has clk and sda pins and is found in tuya bulbs . 
![IMG_8654~2](https://user-images.githubusercontent.com/107633721/208567638-ae859044-1a1d-4384-8799-7d154969d209.jpg)

**Comment by GrumpyMeow** [comment]
It’s supported: https://esphome.io/components/output/bp1658cj.html
Request can thus be closed, right?
