### ISSUE TITLE
Integrated Comments/Notes for Sensors in UI

### ISSUE THREAD

**Issue by 0x90ChuckTessela** [esphome/feature-requests#2061]
**Describe the problem you have/What new integration you would like**

Looking for the ability to have displays for individual sensors show some commentary or notes/documentation.  It would be beneficial to have the UI itself provide a simple string description of sensor/component/entity that is visible when mouse-over the item, and very beneficial when viewing the sensor data in the modal view (such as activity graphs/history).

**Please describe your use case for this integration and alternatives you've tried:**

Many sensors are self-descriptive.  But there are some sensors that aren't always so obvious, and sometimes users (myself included) forget something important about a reported state or value on the display.  It would be nice to have a collapsible/mouse over description or notes that are accessible from the UI/Front end.

This would also be useful for configuration elements and parameterized sliders, etc.

**Additional context**

I've included a couple mock-ups here to help illustrate the intent:

![image](https://user-images.githubusercontent.com/107971785/212402232-bdbc91ab-7d06-4eea-949e-a17deaa04b3a.png)

![image](https://user-images.githubusercontent.com/107971785/212402795-cc3ded1f-ad61-459a-b7c5-ed751cc27221.png)

Ideally it would be collapsible/expandable on the front end, and a summary could be provided on mouse-over from the main view.

**Comment by nagyrobi** [comment]
This is more of a Home Assistant feature request, rather than ESPHome...
