### ISSUE TITLE
Add DNS text sensor entries to the wifi_info text sensor

### ISSUE THREAD

**Issue by tazzytazzy** [esphome/feature-requests#2064]
**Describe the problem you have/What new integration you would like**
To the WiFi info text sensor, is it possible to add DNS entries? This would be in the path: esphome/components/wifi_info

**Please describe your use case for this integration and alternatives you've tried:**
I'm still playing around with local DNS/DHCP on my home network and would be nice to quickly be able to check what DNS entries are currently being used.

**Additional context**
I think this might just be a few lines of code to get to the existing data. Thanks.

**Comment by jesserockz** [comment]
While I see no reason not to implement the text sensor, you know the dns addresses are printed in the logs right?
