### ISSUE TITLE
HASS number entity for PID Climate KP and KI

### ISSUE THREAD

**Issue by en-ver** [esphome/feature-requests#2068]
It would be great to have the ability to change the PID controller KP and KI values without rebuilding the ESP firmware.

The ability to change them instantly would give the following advantages:
- finetune the parameters and see the results instantly
- change the parameters with HASS automation on the heating system conditions change

**Comment by nagyrobi** [comment]
You can do that at runtime by setting up a template numbers and use [automations](https://esphome.io/components/climate/pid.html#climate-pid-set-control-parameters-action).
