### ISSUE TITLE
Set max/min brightness for a Light Effect Pulse

### ISSUE THREAD

**Issue by lordratner** [esphome/feature-requests#2086]
**Describe the problem you have/What new integration you would like**
 The Light effect "pulse" does not allow setting the maximum or minimum brightness

**Please describe your use case for this integration and alternatives you've tried:**
Anytime you want to pulse an LED without blinding everyone in the room, or have the pulse go to a dim-but-not-off level

**Additional context**
Thanks!

**Comment by hiteshkher** [comment]
also I want this type setting, but I can't find

**Comment by max246** [comment]
Feel free to test the branch :)
