### ISSUE TITLE
ThermostatClimate should allow acessing Custom Presets map

### ISSUE THREAD

**Issue by 0x3333** [esphome/feature-requests#2106]
**Describe the problem you have/What new integration you would like**
ThermostatClimate has a protected member called `custom_preset_config_`, which holds the custom preset configs.

I need access to this variable so I can get a preset target temperature. 

**Please describe your use case for this integration and alternatives you've tried:**
I created a descending class and created a method, but it is not great, because I need to replicate all the code for the component.

**Additional context**

**Comment by nagyrobi** [comment]
Please ask in our DEV channel on Discord.
