### ISSUE TITLE
reed switch support for doorstate sensor

### ISSUE THREAD

**Issue by thostie2002** [esphome/feature-requests#219]
**Describe the problem you have/What new integration you would like**

reedswitch support
**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by OttoWinter** [comment]
Already supported. Reed switches are simple binary signals and thus `binary_sensor.gpio` will do fine (optionally also enable pullup via INPUT_PULLUP as seen in docs.)

**Comment by thostie2002** [comment]
Hello, can you send me the link of the example doc?

GRT 

Thorsten Lanting
