### ISSUE TITLE
Compile against custom fork of esp-idf

### ISSUE THREAD

**Issue by tracestep** [esphome/feature-requests#2194]
**Describe the problem you have/What new integration you would like**

I've hit a bug in the `esp-idf` library (which is also manifests itself on ESPHOme with the Arduino framework, by the way). There are a few patches available, but I don't know if it would be possible to specify a custom fork of esp-idf for ESPHome to use instead of the official one.

`i2c_master_cmd_begin(port_, cmd, 20 / portTICK_PERIOD_MS)` call in `i2c_bus_esp_idf.cpp` from the `i2c` component blocks for a full second if the device does not respond, which wreaks havoc with other tasks and components used.
See [https://github.com/espressif/esp-idf/issues/4999](https://github.com/espressif/esp-idf/issues/4999)

**Please describe your use case for this integration and alternatives you've tried:**

 If it is not already possible to use a custom fork of esp-idf (I could not find it on the documentation or in a web search), I think it would be useful to implement, much like `external-components` work.

**Additional context**

The bug is fixed / worked around on a few patches, but still not fixed on `esp-idf` itself.

**Comment by tracestep** [comment]
I am actually using the esp-idf framwork itself on ESPHome, I just tested with the Arduino to see if the issue manifested itself there as well.

**Comment by ssieb** [comment]
Then you can specify whatever version of esp-idf you want to use:
https://esphome.io/components/esp32.html#esp-idf-framework
See the `source:` option.  I'm not sure of the exact syntax for that though.

**Comment by tracestep** [comment]
Oops, guess I missed that option (I must have glanced only on the example). Thanks! Closing the issue.
