### ISSUE TITLE
Add support for LD2410 disable bluetooth

### ISSUE THREAD

**Issue by twocolors** [esphome/feature-requests#2210]
**Describe the problem you have/What new integration you would like**
Add support for LD2410 disable bluetooth

**Please describe your use case for this integration and alternatives you've tried:**

![photo_2023-04-21_16-27-47](https://user-images.githubusercontent.com/207796/233648125-e9c9479c-40cc-4363-add5-d740b13f46fd.jpg)

**Additional context**

@sebcaps

**Comment by sebcaps** [comment]
Request handled by  https://github.com/esphome/esphome/pull/4434.
Need patience to be merged in official release, but can already be used , with esphome dev branch and
 `external_components:
    source: github://regevbr/esphome@ld2410
    components: [ld2410]
 `

**Comment by twocolors** [comment]
oh, thx

**Comment by ilvacca** [comment]
Hi guys. I would like to disable bluetooth on my LD2410 but I don't know how to use the commands you listed in the first comment. Can you explain me? Thank you very much.
