### ISSUE TITLE
RC522 new action ON_TAG_REMOVED

### ISSUE THREAD

**Issue by headbanger212** [esphome/feature-requests#2217]
**Describe the problem you have/What new integration you would like**

It would be nice to have an **on_tag_removed** action for RC522 RFID-readers as it is already implemented for PN532:

This automation will be triggered when the PN532 module responds with no tag. This will only be triggered if the tag goes away for one cycle of update_interval.
[link](https://esphome.io/components/binary_sensor/pn532.html)

**Please describe your use case for this integration and alternatives you've tried:**

I'm building a mechanism similar to a "Tonie Box", that triggers music as long as the tag is on the reader.
I want to use the on_tag action, so I don't have to set up each tag as binary sensor in the configuration of the board, but i can't recognize if a tag is removed unless I define the binary sensor.

**Additional context**

Thank you very much for your great work!

**Comment by wetneb** [comment]
I believe this was fixed by https://github.com/esphome/esphome/pull/4742 already, so this issue should be closed.
