### ISSUE TITLE
Re-add the ability to PROPERLY edit configuration files in the HomeAssistant addon.

### ISSUE THREAD

**Issue by gaussey** [esphome/feature-requests#2233]
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

How hard can this be?

**Comment by ssieb** [comment]
You modified the title to have "properly", but you didn't give any explanation of what that means to you.

**Comment by gaussey** [comment]
Being able to mark, cut, copy and paste text which is normal for an editor. It doesn’t work on Firefox or iOS browsers.

**Comment by ssieb** [comment]
I assume you're referring to mobile then.

**Comment by ssieb** [comment]
I see you've already opened an issue for this.  What is the point of making a feature request?
https://github.com/esphome/issues/issues/3833
