### ISSUE TITLE
ESPHome external access

### ISSUE THREAD

**Issue by PablexXXXX** [esphome/feature-requests#2238]
**Describe the problem you have/What new integration you would like**
 It would be amazing to be able to especify an URL of an external home assistance instance.

**Please describe your use case for this integration and alternatives you've tried:**

This would alow the nodes to be anywhere in the world and still be able to control it from one central HA server.

**Additional context**

We already have encryption and with the Captive Portal we have everything we need to make our nodes PORTABLES.

**Comment by randybb** [comment]
ESPHome acts as a server, HA is a client, so if it can connect to it (public address, or via VPN), it can be anywhere on the world.

**Comment by snechiporenko** [comment]
Use VRN component [WireGuard](https://github.com/esphome/esphome/pull/4256) for do this! And [Add-on](https://github.com/hassio-addons/addon-wireguard) as server.
