### ISSUE TITLE
Support Deep Sleep for battery powered sensors

### ISSUE THREAD

**Issue by maans2001** [esphome/feature-requests#226]
**Describe the problem you have/What new integration you would like**

I have a Tuya Door Sensor that has no brand on it but I checked with the Tasmota GitHub and it seems that some pepole have the same device and they have manged to add it to tasmota 
But here is the issue the have not yet been able to overcome 
tasmota is not built for battery-powred devices so it has problems when the device goes to deep sleep mode ...

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

here's the link to the issue in tasmota for you to understand

https://github.com/arendst/Sonoff-Tasmota/issues/5389

**Comment by OttoWinter** [comment]
Please see the documentation - deep_sleep isn't too hard to find from the main page.
