### ISSUE TITLE
Servo transition_length not templatable

### ISSUE THREAD

**Issue by wtv1211** [esphome/feature-requests#2273]
**Describe the problem you have/What new integration you would like**

It would be awesome if i could set a number in Home Assistant for the servo transition_length.

**Please describe your use case for this integration and alternatives you've tried:**

transition_length is not templatable if i try to write anything other than time period.

**Additional context**

For example i could make it quiter at night.

**Comment by ssieb** [comment]
From a lambda, you can do `id(my_servo).set_transition_length(<value in ms>);`

**Comment by wtv1211** [comment]
`Thank you, i've got it working.`
