### ISSUE TITLE
M5Stack Integration Missing

### ISSUE THREAD

**Issue by reinig** [esphome/feature-requests#2280]
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

Hi,
I am missing the M5Stack integration as it was available in Version 2022.11.4 via "Pick Specific Device" 

Reinhard

**Comment by randybb** [comment]
There was never such option. Only option is to pick a platformio device profile, that is in most cases totally useless and just a copy of the default profile "esp32dev". You can compare them - [esp32dev ](https://github.com/platformio/platform-espressif32/blob/master/boards/esp32dev.json) and [M5Stack Core2](https://github.com/platformio/platform-espressif32/blob/master/boards/m5stack-core2.json). PSRAM is detected automatically, esphome uses only 4 MB of flash so only benefits are [aliases ](https://github.com/esphome/esphome/blob/dev/esphome/components/esp32/boards.py) for GPIOs.
If you still want to do that, then "_+ NEW DEVICE_ > _CONTINUE_ > type name and click on _NEXT_ > remove checkbox from _Use recommended settings_ and click on _ESP32_ > select _M5Stack Core2_".
