### ISSUE TITLE
Integrate developments in libretiny fork of esphome that allow using esphome on BK7231 and RTL8710B chips

### ISSUE THREAD

**Issue by abelbour** [esphome/feature-requests#2327]
**Describe the problem you have/What new integration you would like**
Integrate developments in libretiny fork of esphome that allow using esphome on BK7231 and RTL8710B chips

**Please describe your use case for this integration and alternatives you've tried:**
Newer smart bulbs by Tuya use these MCUs

**Additional context**

https://github.com/kuba2k2/libretiny
https://github.com/kuba2k2/libretiny-esphome

**Comment by gb0101010101** [comment]
+1 please merge LibreTiny.
So many devices are switching to the Beken chips it would be great to support them in the main ESPHome development.

**Comment by RickDickinson** [comment]
Yes. Please merge this into the main release

**Comment by paravoid** [comment]
I believe 2023.09 fully integrated LibreTiny and this can be resolved :) I flashed a BK7231T the other day using nothing but stock ESPHome.
