### ISSUE TITLE
Disable individual LEDs in FastLED

### ISSUE THREAD

**Issue by poldim** [esphome/feature-requests#233]
**Describe the problem you have/What new integration you would like**
Need to permanently disable an array of individual LEDs in a string for various reasons.  This is is a great example: https://youtu.be/q1G4UurGZfQ?t=378

**Please describe your use case for this integration and alternatives you've tried:**
Using Rob's code is great but I'm trying to move things over to ESPHome and am not aware of a way to override LEDs to always being off.

**Additional context**
In Rob's code he calls these annoying LEDs and sets them to black on every color write.

**Comment by OttoWinter** [comment]
See light partitions

**Comment by poldim** [comment]
Perfect, thanks! I did not come across this while searching!
