### ISSUE TITLE
WS2815 - Add support for this newer addressable LED IC

### ISSUE THREAD

**Issue by poldim** [esphome/feature-requests#234]
**Describe the problem you have/What new integration you would like**

WS2815 appears to be a 12v brother of the 5v WS2812/3.  I have ordered some WS2815 strips but have not received them.
Spec sheet: http://www.witop-tech.com/wp-content/uploads/2017/06/WS2815-12v-addressable-led-chip-specification-.pdf

**Please describe your use case for this integration and alternatives you've tried:**

Once I get the strips I will try running them with the WS2812/3 to see if there are any issues.

**Additional context**

**Comment by OttoWinter** [comment]
From [this page](https://forum.arduino.cc/index.php?topic=576510.0) (german) it sounds like it's the same protocol as the WS2812.

**Comment by poldim** [comment]
I'll let you know once they get here from China.  I just ordered them so
they should be here in about a month.

**Comment by yanikdude** [comment]
Im interested in WS2815 connected to ESP8266 using ESPHome. 

Can the current libraries / configs can cater for RGBW and not just RGB.

**Comment by OttoWinter** [comment]
@yanikdude Please see neopixelbus integration.

Closing issue as pretty likely WS2815 already works. If not, reopen issue
