### ISSUE TITLE
Add support for new LilyGo T-Display-S3 AMOLED

### ISSUE THREAD

**Issue by julianrinaldi** [esphome/feature-requests#2345]
**Describe the problem you have/What new integration you would like**

I would like support for the new LilyGo T-Display-S3 AMOLED display added to ESPHome.

https://www.lilygo.cc/products/t-display-s3-amoled?variant=42859368677557

**Please describe your use case for this integration and alternatives you've tried:**

It's probably the nicest small screen released for ESP32, with a higher resolution (240x536), dpi, refresh rate and brighter screen. I'm sure it will be very popular for ESPHome users.

**Additional context**

Here are some links that might be useful:
https://github.com/Xinyuan-LilyGO/T-Display-S3-AMOLED
https://github.com/VolosR/TDisplayAmoled/tree/main/AmoledT-Display/HelloWorldAmoled

**Comment by cosmicDustOfLightLength** [comment]
I have board file works for me very good, might be useful: 
[lilygo-t-amoled.txt](https://github.com/esphome/feature-requests/files/12568146/lilygo-t-amoled.txt)

**Comment by bluechris** [comment]
> I have board file works for me very good, might be useful: [lilygo-t-amoled.txt](https://github.com/esphome/feature-requests/files/12568146/lilygo-t-amoled.txt)

I just got the board and i cannot in the life of me make the screen to light up no matter what i try. 
Your code is not ESPHome or something i dont understand correctly.

Either way, does anyone managed to make it work?

**Comment by clydebarrow** [comment]
![PXL_20231213_192743187 MP](https://github.com/esphome/feature-requests/assets/2366188/99544654-045a-43da-8efd-9718f0d302f0)

**Comment by bluechris** [comment]
Dear Clydebarrow can you share the code of what you did?

**Comment by clydebarrow** [comment]
There's some discussion (see link below)  that will help. I'm on the road so can only provide limited help right now, but if you clone my fork and check out the amoled branch you should be able to build from that. There is also a  PR for the touchscreen in esphome, #5941 IIRC.

The AMOLED driver is not in PR yet, needs the quad_spi PR merged first.

https://github.com/landonr/lilygo-tdisplays3-esphome/issues/25

See also the Display Features thread on Discord.
