### ISSUE TITLE
Allow disabling `update_interval`  on the display component.

### ISSUE THREAD

**Issue by rarroyo6** [esphome/feature-requests#2354]
**Describe the problem you have/What new integration you would like**

The `update_interval` on the LCD display component should be optionally disabled by setting a time of 0s.
**Please describe your use case for this integration and alternatives you've tried:**

As it currently stands, the display gets updated every `update_interval` which defaults to 1s. Sometimes the display is only used for displaying sensor data, which might only update occasionally.
It might be more beneficial to be able to disable the automatic updates, then do an initial update at start-up, and force additional updates by issuing a `component.update` only when the data changes.
**Additional context**

**Comment by ssieb** [comment]
`update_interval: never` as described in the [docs](https://esphome.io/guides/configuration-types#time).
