### ISSUE TITLE
WS2812FX Integration (maybe as its own component?)

### ISSUE THREAD

**Issue by TECHNOFAB11** [esphome/feature-requests#236]
**Describe the problem you have/What new integration you would like**

A custom component (would be easiest i think) with the WS2812FX library

**Please describe your use case for this integration and alternatives you've tried:**

to have all of the 55+ effects, i already tried "McLighting" & "WLED"

**Additional context**

https://github.com/kitesurfer1404/WS2812FX#download-install-and-example
Like seen here, its a replacement for neopixel. Should work the same, so theoretically copying the neopixel component and modifying it to use WS2812FX should be possible? 
The only thing is, the "effects" part of the light component needs to be reworked, or the WS2812FX component would have its own "effects" part, where people can define the effects they want to use :)

**Comment by OttoWinter** [comment]
No, ESPHome uses its own addressable LED base. This has a number of advantages:

- Platform independent
- ESPHome-adapted syntax for lambdas etc
- Allows things like partitions
- Gamma correction, color correction etc.

Besides, ESPHome supports most of the WS2812FX effects already - in WS2812FX they just tend to be spread into multiple effects, ESPHome has parameters for effects.

All these libraries use similar syntaxes for writing effects, all it needs is people contributing new effects to ESPHome.
