### ISSUE TITLE
allow to customize web ui / embed js file 

### ISSUE THREAD

**Issue by chaudhryfaisal** [esphome/feature-requests#237]
**Describe the problem you have/What new integration you would like**

would like to use esphome web ui in completely offline mode where router is not connected to internet or just in AP mode and currently css and js are downloaded from internet which breaks web ui.

**Please describe your use case for this integration and alternatives you've tried:**

when opening web ui in AP mode button toggle does not work. Most likely due to missing js file

**Additional context**

will it be possible to embed minimal js file to make button toggle work or possible to customize / override html/index file?

**Comment by OttoWinter** [comment]
The locations of the CSS/JS files can already be customized, see docs.

Embedding them into the device is not really planned at the moment - especially since the files can also be self-hosted on another device on the network with much more storage space.
