### ISSUE TITLE
long press for binary sensors

### ISSUE THREAD

**Issue by mvturnho** [esphome/feature-requests#240]
**Describe the problem you have/What new integration you would like**

Add something like` on_long_press` to automation to act on long presses for binary sensors

**Please describe your use case for this integration and alternatives you've tried:**

I would like to use a binary sensor to toggle a light and dim the light using the long_press.

**Additional context**

I think implementing in automations is the better choice but maybe it needs changes to the binary_sensor base class as well.

**Comment by OttoWinter** [comment]
That already exists, `on_click` takes timing options (which essentially allows you to accept long clicks). Plus you can use on_multi_click for more complicated click patterns.
