### ISSUE TITLE
Advertise Available Events for Device

### ISSUE THREAD

**Issue by albarlow** [esphome/feature-requests#2422]
**Describe the problem you have/What new integration you would like**

I would like to be able to advertise possible events for a specific device to Home Assistant.

**Please describe your use case for this integration and alternatives you've tried:**

I would like to be able to fire an event for 'Button 1 Single Clicked' 'Button 1 Double Clicked', 'Button 1 Long Clicked' et.c

**Additional context**

I don't know if this is possible to do generically.  I've seen it done with static devices e.g. Shelly devices advertise events such as the above so wondered if it could be incorporated to ESPHome to make it easier to set up Automations based on the device without having to play with YAML in the automation.

**Comment by nagyrobi** [comment]
Closing as duplicate in favor of https://github.com/esphome/feature-requests/issues/2433, because there it's described a bit more understandable.
