### ISSUE TITLE
Compile Cache

### ISSUE THREAD

**Issue by admin-lm** [esphome/feature-requests#2434]
**Describe the problem you have/What new integration you would like**
I have the problem that on an ESPHome-Update I need to compile all sources for all devices multiple times,
I suggest some cache to not compile eg. logger.cpp one time per device

**Please describe your use case for this integration and alternatives you've tried:**
The Update All Button in HA doesn't help, as it timeouts after a few ESPs.
An HA script is my current workaround

**Additional context**
None

**Comment by ssieb** [comment]
There are already existing requests for this.
e.g. https://github.com/esphome/feature-requests/issues/975 and https://github.com/esphome/feature-requests/issues/2171
