### ISSUE TITLE
Support for manual selection of dark/light appearance in WebGUI

### ISSUE THREAD

**Issue by KC-inDomus** [esphome/feature-requests#2450]
**Describe the problem you have/What new integration you would like**
A manual switch to choose which webgui accearance to be used.

**Please describe your use case for this integration and alternatives you've tried:**
-

**Additional context**
-

**Comment by randybb** [comment]
Nope, we don't want that https://github.com/esphome/dashboard/pull/497#issuecomment-1599340913 - it has to follow your browser settings
