### ISSUE TITLE
Climate Component - Add AUX_HEAT Supported Feature

### ISSUE THREAD

**Issue by Daniel-dev22** [esphome/feature-requests#2455]
**Describe the problem you have/What new integration you would like**

Add the ability to pass AUX_HEAT as a supported climate feature and add it as a mode so that home assistant can show this option in the UI.

By adding it as a mode and not just passing that it supports the feature that would give users the ability to execute the action to enable AUX_HEAT on our climate devices.

https://developers.home-assistant.io/docs/core/entity/climate/#supported-features

**Please describe your use case for this integration and alternatives you've tried:**

My climate device supports emergency heat but currently I have to use custom presets in order to set emergency heat if I needed it.

**Additional context**

**Comment by kroimon** [comment]
Auxiliary heating support in climate has been deprecated in Home Assistant:
- home-assistant/architecture#932

This feature will therefore not be added to ESPHome and has been removed from the linked pull request.
Possible alternatives are indicated in the architecture discussion.
