### ISSUE TITLE
Dashboard Editor right-click paste button missing

### ISSUE THREAD

**Issue by NonaSuomy** [esphome/feature-requests#2457]
**Describe the problem you have/What new integration you would like**

Add a clickable button to paste in the right-click menu of the editor.

**Please describe your use case for this integration and alternatives you've tried:**

You can see in the image Paste is not available.
![image](https://github.com/esphome/feature-requests/assets/1906575/34a9e370-cdeb-48e6-b8e5-98d63dba6f35)

**Additional context**

**Comment by NonaSuomy** [comment]
Tested Chromium, Chrome, Firefox, Opera, Safari / Linux, Windows, MacOS all the same.

**Comment by tiimsvk** [comment]
I would have more reservations when editing the text.
On mobile, it is not possible to mark more text at once, select, copy and paste.

**Comment by NonaSuomy** [comment]
I was nudged in the right direction by balloob on discord he said "you can't access the clipboard when not browsing over HTTPS, it's a browser limitation"

I then looked at the site settings and sure enough

![image](https://github.com/esphome/feature-requests/assets/1906575/5f13a626-1b54-4e81-ae64-08e5552a2042)
Seems you can write (cut, copy) to the clipboard without HTTPS, just not read (paste) from the clipboard without HTTPS 😅 

So I added the site to the `Insecure origins treated as secure` list in `chrome://flags/`
![image](https://github.com/esphome/feature-requests/assets/1906575/237c1c8f-1f59-4da5-b9fb-22dc1fa41937)

Boom it was there now after the browser restarted:

![image](https://github.com/esphome/feature-requests/assets/1906575/e2d08668-f020-46d1-bc79-9300a50f6862)

![image](https://github.com/esphome/feature-requests/assets/1906575/6d2ba927-7aa0-4653-b5b4-f7b7957d4065)

Thank you!

**Comment by tiimsvk** [comment]
How to enable in firefox?

**Comment by NonaSuomy** [comment]
There currently isn't a way for firefox however you could probably use some scripting skills to inject a right click option that presses the ctrl+v keyboard shortcut for you.
