### ISSUE TITLE
addressable leds ws2812b ws2811

### ISSUE THREAD

**Issue by thostie2002** [esphome/feature-requests#249]
**Describe the problem you have/What new integration you would like**
hello, i want a intergration for digital ledstrips like the ws2813b and the ws2811

**Please describe your use case for this integration and alternatives you've tried:**
i've tried the rgblight component but that needs 3 diverent digital pins

**Additional context**

**Comment by OttoWinter** [comment]
Please read the docs, that already exists. It isn't that hard to find.

**Comment by thostie2002** [comment]
i found it ;) it is the fast led light  


you can close the request:)
