### ISSUE TITLE
Support for power monitor INA228/229

### ISSUE THREAD

**Issue by taHC81** [esphome/feature-requests#2549]
**Describe the problem you have/What new integration you would like**

Would it be possible to add INA228 (I2C) and INA229 (SPI) power monitoring chips? There're already some INAs supported, but these 2 are often used for battery management.

**Please describe your use case for this integration and alternatives you've tried:**

Battery voltage/current/power/SoC monitoring.

**Additional context**

**Comment by taHC81** [comment]
https://www.ti.com/document-viewer/ina228/datasheet

**Comment by latonita** [comment]
@taHC81 I can take a look into this - I have no device, so I will need your help to test/debug

**Comment by taHC81** [comment]
> @taHC81 I can take a look into this - I have no device, so I will need your help to test/debug

With a pleasure, I have 3 devices ;)

**Comment by latonita** [comment]
@taHC81  try this one https://github.com/latonita/esphome-ina228
if it works at all

**Comment by taHC81** [comment]
Tried that, had to comment out TAG read part in a component setup (https://github.com/taHC81/esphome-ina228/blob/f05410bf26457f0036598b09aa1ad7a122a0b3a5/components/ina228/ina228.cpp#L59), then  it started working. Unfortunately, waiting for a bigger shunt (75mV / 400A), so can't provide some real numbers.

https://pastebin.com/B3pvi3eV

```
[08:48:22][D][sensor:094]: 'INA228 Shunt Voltage': Sending state 0.24000 V with 2 decimals of accuracy
[08:48:22][D][sensor:094]: 'INA228 Bus Voltage': Sending state 0.00000 V with 2 decimals of accuracy
[08:48:22][D][sensor:094]: 'INA228 Current': Sending state 0.00000 A with 3 decimals of accuracy
[08:48:22][D][sensor:094]: 'INA228 Power': Sending state 0.00000 W with 2 decimals of accuracy
[08:48:24][D][sensor:094]: 'INA228 Shunt Voltage': Sending state 0.24000 V with 2 decimals of accuracy
[08:48:24][D][sensor:094]: 'INA228 Bus Voltage': Sending state 0.05000 V with 2 decimals of accuracy
[08:48:24][D][sensor:094]: 'INA228 Current': Sending state 0.00078 A with 3 decimals of accuracy
[08:48:24][D][sensor:094]: 'INA228 Power': Sending state 0.00000 W with 2 decimals of accuracy
[08:48:26][D][sensor:094]: 'INA228 Shunt Voltage': Sending state 0.24000 V with 2 decimals of accuracy
[08:48:26][D][sensor:094]: 'INA228 Bus Voltage': Sending state 0.05000 V with 2 decimals of accuracy
[08:48:26][D][sensor:094]: 'INA228 Current': Sending state 0.00078 A with 3 decimals of accuracy
[08:48:26][D][sensor:094]: 'INA228 Power': Sending state 0.00000 W with 2 decimals of accuracy
[08:48:28][D][sensor:094]: 'INA228 Shunt Voltage': Sending state 0.24000 V with 2 decimals of accuracy
```

**Comment by latonita** [comment]
good, i actually supposed this might fail with some of the clones and forgot to make it just an informational/warning message

please check whether data is good - i hope byte order is okay

btw, do you own SPI versions of this device? then I can split this driver to base/i2c/spi

**Comment by taHC81** [comment]
No, just I2C INA228, not INA229. But they should be completely same (registers) except the interface.

Die temp is not measured and energy/charge are "bit" off as well :)
![Capture](https://github.com/esphome/feature-requests/assets/36913630/7b9d8510-616a-4179-bb49-3f41bd1df6ba)

**Comment by latonita** [comment]
what are the 'expected' values, approximately?

**Comment by latonita** [comment]
@taHC81 can you please send me output of these lines

  ESP_LOGI(TAG, "New Rshunt=%f ohm, max current=%.3f", r_shunt, max_current);
  ESP_LOGI(TAG, "New CURRENT_LSB=%f, SHUNT_CAL=%u", this->current_lsb_, this->shunt_cal_);

**Comment by taHC81** [comment]
Not reported at all, I set debug level VERBOSE. Maybe you can make updates on your repo...

**Comment by taHC81** [comment]
> @taHC81 i updated the code, added debug output. please enable DEBUG level logging and put output to the pastebin. thanks make sure you compile new version, sometimes it caches old one.
> 
> ```
> logger:
>   level: DEBUG
> ```

Here it is - https://pastebin.com/E4rkNWKF

**Comment by latonita** [comment]
try one more time please + share logs.
thanks

**Comment by taHC81** [comment]
Charge and energy look better, voltage still zero when I connect 3.3V

```
[13:41:39][D][ina228:031]: read_s20_4_ 0x04, ret= 0, raw 0x00A00000
[13:41:39][D][ina228:116]: read_volt_shunt_ is TRUE, 0x00000000
[13:41:39][D][sensor:094]: 'INA228 Shunt Voltage': Sending state 0.00000 V with 2 decimals of accuracy
[13:41:39][D][ina228:031]: read_s20_4_ 0x05, ret= 0, raw 0x00100000
[13:41:39][D][ina228:125]: read_voltage_ is TRUE, 0x00000000
[13:41:39][D][sensor:094]: 'INA228 Bus Voltage': Sending state 0.00000 V with 2 decimals of accuracy
[13:41:39][D][ina228:031]: read_s20_4_ 0x05, ret= 0, raw 0x00100000
[13:41:39][D][ina228:143]: read_voltage_ is TRUE, 0x00000000
[13:41:39][D][sensor:094]: 'INA228 Current': Sending state 0.00000 A with 3 decimals of accuracy
[13:41:39][D][ina228:152]: read_power_1 ret= 0, 0x00000000
[13:41:39][D][ina228:155]: read_power_2 ret= 0, 0x00000000
[13:41:39][D][sensor:094]: 'INA228 Power': Sending state 0.00000 W with 2 decimals of accuracy
[13:41:39][D][ina228:164]: read_energy_1 ret= 0, 0xFFFFA00000
[13:41:39][D][ina228:167]: read_energy_2 ret= 0, 0xA0FFFF
[13:41:39][D][sensor:094]: 'INA228 Energy': Sending state 206079.98438 J with 2 decimals of accuracy
[13:41:39][D][ina228:176]: read_charge_1 is TRUE, 0xFFFFA00000
[13:41:39][D][ina228:181]: read_charge_2 is TRUE, 0xA0FFFF
[13:41:39][D][sensor:094]: 'INA228 Charge': Sending state 4024.99951 C with 2 decimals of accuracy
```

**Comment by latonita** [comment]
please share full log when it works for few minutes. thanks.

**Comment by latonita** [comment]
one more try plz :)

**Comment by taHC81** [comment]
> one more try plz :)

Unfortunately, still the same. https://pastebin.com/ZNrRwfgi

**Comment by latonita** [comment]
maybe initialization is not enough, i will check other libs how do they initialize the device

**Comment by taHC81** [comment]
Looks better now! Shunt will arrive tomorrow, so I'll provide another data.
![Capture](https://github.com/esphome/feature-requests/assets/36913630/4c26d3d0-890e-4b9f-84ea-6ee1959f34f8)

**Comment by latonita** [comment]
@taHC81 another minor update 
- charge shall be reading properly
- number of digits after decimal point increased

**Comment by taHC81** [comment]
Even better, Anton! Thanks a lot! After I get the shunt, will do some preliminary tests.
![Capture](https://github.com/esphome/feature-requests/assets/36913630/67a999e6-f916-4880-b242-6ffbc24b5409)

**Comment by taHC81** [comment]
**1A current +-**
```
[ina228:029]: read_s20_4_ 0x07, ret= 0, raw 0x00D00CFD
[ina228:140]: read_voltage_ is TRUE, 0xFFEFD0CD
[sensor:094]: 'INA228 Current': Sending state -101.15233 A with 5 decimals of accuracy
```

**1A current -+**
```
[ina228:029]: read_s20_4_ 0x07, ret= 0, raw 0x0060EF02
[ina228:140]: read_voltage_ is TRUE, 0x00002EF6
[sensor:094]: 'INA228 Current': Sending state 1.14651 A with 5 decimals of accuracy
```

Going to tweak shunt value to calibrate it.

**Comment by taHC81** [comment]
After calibration:

```
[ina228:029]: read_s20_4_ 0x07, ret= 0, raw 0x00308F02
[ina228:140]: read_voltage_ is TRUE, 0x000028F3
[sensor:094]: 'INA228 Current': Sending state 0.99974 A with 5 decimals of accuracy

[ina228:029]: read_s20_4_ 0x07, ret= 0, raw 0x00606FFD
[ina228:140]: read_voltage_ is TRUE, 0xFFEFD6F6
[sensor:094]: 'INA228 Current': Sending state -101.00193 A with 5 decimals of accuracy
```

**Comment by latonita** [comment]
hi. some updates posted.
- shunt voltage is shown in mV
- adc_range can be selected. option 0 or 1.
- current readings - its important to add some load between ground and Rshunt, and know whats approximate current shall be there.
just as it is here: 
![image](https://github.com/esphome/feature-requests/assets/3993466/a573772e-94ed-4967-8015-584d7d8a9acc)


I would be happy to see full logs +if possible, your manual multimeter readings of Vbus, Vshunt, Rshunt and current 

thanks!

**Comment by taHC81** [comment]
Hello, here's the log - https://pastebin.com/ydERZ675

Please note the adc_range: 0 returns correct data, while I'd expect it from "1". I have 2x 10R filter resistors and 100nF cap.

10V, 99mA, 0.99W reported by a bench power supply. Charge and Energy are cleared only on a power cycle.

**Comment by latonita** [comment]
1) so you say in adc_range 0 data is good, but in adc_range 1 it is wrong. maybe 4 times smaller/bigger?
2) I added some code with debug output to check whether wring to registers works okay
3) looks like some defaults values contradict datasheets... need to double check new logs
with your electrical values i expect v shunt to be 0.00113 ohm* 99ma = 0.11187 mV
which is exactly 4 times bigger than the reading

try and i need full log again plz.  and i will need to recheck all the nanos and millis :)

**Comment by taHC81** [comment]
Thanks, now with adc_range = 1 - https://pastebin.com/L63Y12N3

Maybe with adc_range =1 we just get higher precision...

**Comment by taHC81** [comment]
Strange behavior - on a first power on it measure half current and power, after restart (re-upload same code) starts measuring correctly.

https://pastebin.com/1nmGVV5i

**Comment by latonita** [comment]
@taHC81 thanks for your tests 

not clear about todays results - as for yesterdays - unfortunately old software got cached.

would you please somehow reset caches and build from scratch.
i would be happy to see logs for adc_range = 0 and adc_range = 1.
i hope this time its getting closer and closer to what we all need )))

**Comment by latonita** [comment]
one more thing. i see you are connecting to devices via network
is it possible to get connected via serial?  its missing setup() part of logs which are written before network is initialized
for adc 0 and adc 1
thanks

**Comment by taHC81** [comment]
I'm playing also with some other ESP32's, and C3 has integrated USB interface, it drops connection during restart... Here it is, logger via serial port.

adc: 0 - https://pastebin.com/e3U7LB2B
adc: 1 - https://pastebin.com/MKm264kE

**Comment by latonita** [comment]
thanks! i found an issue with device reset. you may try new one.
meanwhile i will start reworking this component to split into i2c and spi + i think its easy to add support for ina238/239 and ina237

**Comment by latonita** [comment]
please check updated version. supporting ina228, ina238, ina237
note, that it has a new name

```
external_components:
  source: github://latonita/esphome-ina228
  components: [ina2xx_base, ina2xx_i2c]
```

I would appreciate full log from serial.
as well as your real electrical params and readings, thanks

**Comment by latonita** [comment]
> Hello, some strange numbers this time - https://pastebin.com/nLj6vwgt , still same 10V/0.1A/1W.

Ouch, stupid copy-paste-typo. fixed, please check and send logs
thanks

**Comment by latonita** [comment]
also here is documentation i prepared. I would be happy if you can take a look. maybe some mistakes, unclear things, etc.
https://deploy-preview-3571--esphome.netlify.app/components/sensor/ina2xx

**Comment by taHC81** [comment]
> > Hello, some strange numbers this time - https://pastebin.com/nLj6vwgt , still same 10V/0.1A/1W.
> 
> Ouch, stupid copy-paste-typo. fixed, please check and send logs thanks

Yep, now it's ok. https://pastebin.com/HxM5ijH9

**Comment by taHC81** [comment]
> also here is documentation i prepared. I would be happy if you can take a look. maybe some mistakes, unclear things, etc. https://deploy-preview-3571--esphome.netlify.app/components/sensor/ina2xx

Looks good, no obvious errors. Would you consider to add more human-friendly sensors like power/energy in mAh/Ah/Wh/kWh?

**Comment by latonita** [comment]
> > also here is documentation i prepared. I would be happy if you can take a look. maybe some mistakes, unclear things, etc. https://deploy-preview-3571--esphome.netlify.app/components/sensor/ina2xx
> 
> Looks good, no obvious errors. Would you consider to add more human-friendly sensors like power/energy in mAh/Ah/Wh/kWh?

Good idea. I have added Ah and Wh. 
energy and charge in Ah and Wh now, as its closer to real life humans :)
two new sensors are energy_joules and charge_coulombs.
docs updates as well

**Comment by taHC81** [comment]
Probably you have to forgot to push the changes, still see the Joules and Couloumbs. I did the esphome cleanup...

```
[13:49:32][D][ina2xx:052]: Initiating new data collection
[13:49:32][D][ina2xx:501]: read_unsigned_ reg=0x04, ret=OK, len=3, val=0x5900
[13:49:32][D][ina2xx:341]: read_shunt_voltage_mv_ ret=OK, shunt_cal=4440, reading_lsb=1424.000000
[13:49:32][D][sensor:094]: 'INA228 Shunt Voltage': Sending state 0.11125 mV with 5 decimals of accuracy
[13:49:32][D][ina2xx:501]: read_unsigned_ reg=0x05, ret=OK, len=3, val=0xC6A30
[13:49:32][D][ina2xx:362]: read_bus_voltage_ ret=OK, reading_lsb=50851.000000
[13:49:32][D][sensor:094]: 'INA228 Bus Voltage': Sending state 9.93184 V with 5 decimals of accuracy
[13:49:32][D][ina2xx:510]: read_unsigned_16_ 0x06, ret= OK, val=0x0BB5
[13:49:32][D][ina2xx:382]: read_die_temp_c_ ret=OK, reading_lsb=2997.000000
[13:49:32][D][sensor:094]: 'INA228 DIE Temperature': Sending state 23.41406 °C with 5 decimals of accuracy
[13:49:32][D][ina2xx:501]: read_unsigned_ reg=0x07, ret=OK, len=3, val=0x5340
[13:49:32][D][ina2xx:398]: read_current_a_ ret=OK. current_lsb=0.000076. reading_lsb=1332.000000
[13:49:32][D][sensor:094]: 'INA228 Current': Sending state 0.10162 A with 8 decimals of accuracy
[13:49:32][D][ina2xx:501]: read_unsigned_ reg=0x08, ret=OK, len=3, val=0x1004
[13:49:32][D][ina2xx:412]: read_power_w_ ret=OK, reading_lsb=4100
[13:49:32][D][sensor:094]: 'INA228 Power': Sending state 1.00098 W with 6 decimals of accuracy
[13:49:32][D][ina2xx:510]: read_unsigned_16_ 0x0B, ret= OK, val=0x0003
[13:49:32][D][ina2xx:468]: read_diagnostics_and_act_ ret=OK, 0x0003
[13:49:32][D][ina2xx:501]: read_unsigned_ reg=0x09, ret=OK, len=5, val=0x4B
[13:49:32][D][ina2xx:432]: read_energy_j_ ret=OK, reading_lsb=0x4B, current_lsb=0.000076, overflow_cnt=0
[13:49:32][D][sensor:094]: 'INA228 Energy': Sending state 0.29297 J with 8 decimals of accuracy
[13:49:32][D][ina2xx:501]: read_unsigned_ reg=0x0A, ret=OK, len=5, val=0x1AA
[13:49:32][D][ina2xx:454]: read_charge_c_ ret=1, curr_charge=426.000000 + 39-bit overflow_cnt=0
[13:49:32][D][sensor:094]: 'INA228 Charge': Sending state 0.03250 C with 8 decimals of accuracy
```

**Comment by latonita** [comment]
@taHC81 my bad, i pushed it to main PR only, but not into latonita ina228 repository

**Comment by latonita** [comment]
@taHC81 can you please test negative current.

**Comment by taHC81** [comment]
> @taHC81 can you please test negative current.
> 
> Basically Charge/discharge cycle
> 
> P. S. Vbus shall stay almost positive as per datasheet

Yeah, Vbus is the voltage across the battery terminals. I need to manage some test load. Will run test most probably in upcoming days.

**Comment by taHC81** [comment]
https://pastebin.com/ujj7pnXz

Here's how it looks like when I've connected charger and current flowed in an opposite direction. Crazy numbers :)

**Comment by latonita** [comment]
@taHC81 what are expected negative values?

**Comment by taHC81** [comment]
Load (from a battery) is 0.286A, when I turn on power supply, it draws 0.317A, it can be translated to a charging with 0.031A. Maybe a bit more, as the Vbus is a bit higher (15.58V vs. 15.85V).

Let me discharge that battery a bit, to have a bigger difference.

**Comment by latonita** [comment]
@taHC81  i pushed the fix. please try

**Comment by taHC81** [comment]
No funny numbers anymore, but I just realized it shows positive power & current when I connect the load, and it should be opposite - load = minus power, charging = plus power. My smart battery is acting strangely, it doesn't accept any charge at the moment, will try with non-smart battpack on Monday. Sunday = family.

https://pastebin.com/Mp8WA0yR

**Comment by latonita** [comment]
@taHC81 good to hear.
as for +- .... don't shoot the messenger. i'm just getting data from the device :) 
you might have `on_value` triggers in particular sensor to switch polarity if you need 
have a nice sunday. meanwhile i'll remove debug logs and make PR ready for review

**Comment by taHC81** [comment]
Had some spare time, so did a try. Counters reset works fine, energy/charge working fine, but charge overflows, see the video and logs - https://pastebin.com/sW96Ww8s

https://www.youtube.com/watch?v=W_YwNdLt76I

**Comment by latonita** [comment]
@taHC81 try get new ver, shall be proper negative charge

**Comment by taHC81** [comment]
Fixed, good! ;) But I'd recommend to swap the polarity of the current as a default.

**Comment by latonita** [comment]
@taHC81 this is just what i get from the device. i think it might be changed in particular sensor adding
```
  charge:
     name: xx
     filter:
        multiply : -1.0
```

**Comment by latonita** [comment]
and one ugly thing which is coming - is overflowing charge register. 
i know its a big number (for your settings it is 11.5 kAh) but...
funny is that device counts charge as signed value, but at the same time overflow bit doesnt say is it + overflow or -overflow. :)))
I will ask TI forum

**Comment by audito67** [comment]
Greetings.
I also have ina228 for monitoring the battery of a solar station.
At the moment I do not use any processing using HA tools; all data is displayed in its original form. There are fluctuations in the shunt voltage and shunt current in the near-zero zone, but the Ah meter increases the readings. After about an hour of operation of the device, the Ah reading is 0.00003181 Ah, while no real current flows through the shunt resistor.
 charge:
     name: xx
     filter:
        multiply : -1.0
If you use the solution you suggested, the register values will continue to increase even when the battery is low.

**Comment by taHC81** [comment]
> Greetings. I also have ina228 for monitoring the battery of a solar station. At the moment I do not use any processing using HA tools; all data is displayed in its original form. There are fluctuations in the shunt voltage and shunt current in the near-zero zone, but the Ah meter increases the readings. After about an hour of operation of the device, the Ah reading is 0.00003181 Ah, while no real current flows through the shunt resistor. charge: name: xx filter: multiply : -1.0 If you use the solution you suggested, the register values will continue to increase even when the battery is low.

It's a common noise, you have either live with that or filter out values under f.i. 0.005A and integrate energy by yourself. Even the sub-sized PV plant uses 100+ Ah batteries, so considering 1e-5 Ah values is a bit odd to me.

**Comment by audito67** [comment]
I understand perfectly well that this is an insignificant value and can be neglected, the point is that this noise accumulates in the register, which logically should not happen.
And filtering can be done using the chip, as mentioned in the datasheet.

**Comment by latonita** [comment]
I may change integration time and turn on averaging
For now it's 50us, changing to even max 4000us should not harm anyone (4 ms)
I will take a look later today

**Comment by audito67** [comment]
> Было немного свободного времени, поэтому попробовал. Сброс счетчиков работает нормально, энергия / заряд работает нормально, но переполнение заряда, см. Видео и журналы - https://pastebin.com/sW96Ww8s
> 
> https://www.youtube.com/watch?v=W_YwNdLt76I

The question is a little off topic, sorry.
How did you implement resetting data in registers on your HA?
If possible, a piece of Yaml code on a third-party resource.

**Comment by latonita** [comment]
BTW, as per datasheet energy/charge error is 1%

**Comment by taHC81** [comment]
> > Было немного свободного времени, поэтому попробовал. Сброс счетчиков работает нормально, энергия / заряд работает нормально, но переполнение заряда, см. Видео и журналы - https://pastebin.com/sW96Ww8s
> > https://www.youtube.com/watch?v=W_YwNdLt76I
> 
> The question is a little off topic, sorry. How did you implement resetting data in registers on your HA? If possible, a piece of Yaml code on a third-party resource.

```
button:
  - platform: template
    name: "Reset counters"
    on_press:
      - lambda: "id(ina228_sensor).reset_energy_counters();"
```

**Comment by audito67** [comment]
> I may change integration time and turn on averaging For now it's 50us, changing to even max 4000us should not harm anyone (4 ms) I will take a look later today

The integration time seemed to be 1052 µs, and the averaging was “1”, or am I mistaken?
By and large, whether 1ms or 4ms is not a big difference, greater accuracy is achieved (according to the datasheet) by averaging the measurements.

**Comment by latonita** [comment]
> By and large, whether 1ms or 4ms is not a big difference, greater accuracy is achieved (according to the datasheet) by averaging the measurements.

I've made 4096us and 128 samples. which all in all give us ~0.5s for a sample. good enough for australia, montenegro, esphome and hass  and home automation, i believe. and it gives 19.7 effective resolution bits 

I might make it configurable if required. the longest exposure that can be achieved is ~ 4s for the sample. which gives full 20 effective bit adc

please take a look, whether this brings value. then i might add configuration options

**Comment by taHC81** [comment]
Good one ;) will check tomorrow. Thanks for your work!

**Comment by audito67** [comment]
Greetings.
Everything is just super, it works perfectly.
I checked the accuracy of the readings with a calibrated constant voltage source, the readings fluctuated to 4 decimal places. The shunt voltage remains stable in the area of its own noise and also in the 4th decimal place.
There are no negative shunt current and voltage values.
Wonderful.

**Comment by audito67** [comment]
I checked it on esp8266, later I will check it on esp32 and with current flow.

**Comment by taHC81** [comment]
Finally had an opportunity to check, looks good now, I have approx -0.006A reading with no load, I think it's acceptable on a 300A shunt :)

Thanks for you work, I'd say it's ready to become public.
![20240201_182019](https://github.com/esphome/feature-requests/assets/36913630/d4765351-73a6-4670-b87a-50554e2b0e8c)

**Comment by audito67** [comment]
> Finally had an opportunity to check, looks good now, I have approx -0.006A reading with no load, I think it's acceptable on a 300A shunt :)
> 
> Thanks for you work, I'd say it's ready to become public. ![20240201_182019](https://private-user-images.githubusercontent.com/36913630/301782871-d4765351-73a6-4670-b87a-50554e2b0e8c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODg0NjYsIm5iZiI6MTcwNjg4ODE2NiwicGF0aCI6Ii8zNjkxMzYzMC8zMDE3ODI4NzEtZDQ3NjUzNTEtNzNhNi00NjcwLWI4N2EtNTA1NTRlMmIwZThjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE1MzYwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MzM4MmVmMGEyMWM0YWViNTdiNjhkYWM1YzJiZTU5NTc4ZmU0ZTliMzA4ZGUzYzQ3MjhkMWY5ZWU2MGVjMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._IMTBjrDxkYdiX68HWqZPA3rxHrL9O8gS00y8a1Olmc)

I confirm that this is practically the only project that allows you to use the functionality of the energy monitor on ina228 with minimal effort.

**Comment by audito67** [comment]
> I might make it configurable if required. the longest exposure that can be achieved is ~ 4s for the sample. which gives full 20 effective bit adc

In the future, do you plan to make the conversion times and averaging parameters customizable? I think the ability for the user to independently configure these parameters would not be superfluous.

**Comment by latonita** [comment]
> In the future, do you plan to make the conversion times and averaging parameters customizable?
@audito67 done.

**Comment by audito67** [comment]
Is there a desire to create a project with similar functionality (within the capabilities of the chips) for ina226?
The existing integration into esphome uses a minimum of functionality compared to the functionality in your project.

**Comment by taHC81** [comment]
> Is there a desire to create a project with similar functionality (within the capabilities of the chips) for ina226? The existing integration into esphome uses a minimum of functionality compared to the functionality in your project.

What do you expect? INA226 doesn't provide charge/energy registers. Yes, conversion time and averaging shall be added, question is, if there is a real need for this.

**Comment by audito67** [comment]
> > Is there a desire to create a project with similar functionality (within the capabilities of the chips) for ina226? The existing integration into esphome uses a minimum of functionality compared to the functionality in your project.
> 
> What do you expect? INA226 doesn't provide charge/energy registers. Yes, conversion time and averaging shall be added, question is, if there is a real need for this.

Yes, I am well aware of the capabilities of the INA226, and I designated it “within the capabilities of the chips.”
Recently I encountered an unpleasant moment when switching from the alternative firmware esp8266+ina 226 to integration from esphome. There were significant (1.7a) current readings with no current flowing through the shunt resistor. The values written to the ina226 registers are preserved and there is no way to reset them in the esphome platform.
Whether there is a need for the user to change the measurement and averaging settings is a matter of experimentation, but working with ina228 showed positive results.

**Comment by latonita** [comment]
@audito67 actually I see a bug in INA226 - it doesnt work with negative values, instead you will get huge readings.
If you still own it it would be great to test.
if it works okay - please create error report and i will link it.
https://github.com/esphome/esphome/pull/6172

**Comment by taHC81** [comment]
I've got some 226's on the way home, should come this week.

**Comment by audito67** [comment]
Good afternoon
Don't quite understand what I need to do? Perhaps because I use a translator.
I can connect a new one, not used on the alternative firmware ina226, and carry out the necessary tests, but when I add the stack code “adc_time: 1100 us” “adc_averaging: 1024” to the working code generated from the example with esphome, the error “[adc_time] is an invalid” appears option for [sensor.ina226]. Please check the indentation."
  I assume the external component does not contain these changes and probably needs a link to the external component.

**Comment by audito67** [comment]
![2024-02-05_12-08-34](https://github.com/esphome/feature-requests/assets/118008639/01e4a9c3-e31e-474d-a46a-bb7db1533cfe)

**Comment by latonita** [comment]
@audito67 
external_components:
  - source: github://pr#6172
    components: [ ina226 ]

**Comment by audito67** [comment]
Should the test be carried out on a completely new one or can it be used previously?

**Comment by audito67** [comment]
The test was carried out on the previously used ina226. The readings are displayed correctly when measuring current in both directions; there is no deviation in the current and voltage readings.
Everything is great.

**Comment by audito67** [comment]
Judging by the log, the voltage and current readings are stable in the fourth decimal place even with a measurement time of 332 µs, the number of measurements before averaging is 1024.

**Comment by audito67** [comment]
In both cases, the display is correct, both positive and negative values.
Just in case, I am attaching the logs, with the old version marked old and, accordingly, your project marked new.
[logs_ina226_run_new.txt](https://github.com/esphome/feature-requests/files/14175592/logs_ina226_run_new.txt)
[logs_ina226_logs_old.txt](https://github.com/esphome/feature-requests/files/14175594/logs_ina226_logs_old.txt)
[logs_ina226_run_old.txt](https://github.com/esphome/feature-requests/files/14175595/logs_ina226_run_old.txt)

**Comment by audito67** [comment]
I cleared the cache in HA, but the identical behavior of the device under test is confusing.

**Comment by audito67** [comment]
Good afternoon. I discovered two bugs, the first concerns the operation of ina228. The energy meter increases its readings regardless of whether the battery is charging or discharging. The second unpleasant discovery is to reboot the esp8266 and reset the data accumulated in the ina228 when the connection with the home assistant server is lost. A survey was organized on esp8266 by ina228 and BMS Jikong. The BMS survey is carried out using the syssi project.

**Comment by taHC81** [comment]
> Good afternoon. I discovered two bugs, the first concerns the operation of ina228. The energy meter increases its reading regardless of whether the battery is charging or discharging. The second unpleasant discovery is rebooting the esp8266 and resetting the data accumulated in the ina228 when the connection with the home assistant server is lost. The survey was organized on esp8266 by ina228 and BMS Jikong. The BMS survey is conducted using the syssi project. By and large, no matter what project is used, the contents of the registers should not be reset when the esp is rebooted. Otherwise, these power and energy calculations are useless.

Energy is always positive value (https://e2e.ti.com/support/amplifiers-group/amplifiers/f/amplifiers-forum/1028806/ina228-q1-current-energy-polarity), I'd suggest to calculate discharge=energy-charge.

For the loosing the cumulative data, I'd suggest to create utility meters on a HA side to cover it.

**Comment by audito67** [comment]
Thanks for the clarification, there is only one parameter that is useful for use in a solar station, this is the calculation of Ah entering/exiting the battery. I agree, energy can be calculated using HA. I don’t quite understand how using the utility meters will save data when resetting the registers in ina228? With the same success, you can use the history for this sensor, but provided that the loss of communication was short-term. If there is no data transmission for a long time, then in any case you will not receive correct data. In my opinion, I may be mistaken, you can save the data by disabling the reset functionality when you start the esp and do a reset upon request from the user or by turning off the power.

**Comment by taHC81** [comment]
Issues on an ESP side are another story. Utility meter always increase value, even if the source sensor resets to zero. See the manual - https://www.home-assistant.io/integrations/utility_meter/

**Comment by latonita** [comment]
I think what's is doable is to define two template sensors in esphome - one for charging, another for discharging, based on current sign.
And create two utility meters in hass for energy consumed from the grid and generated

BR, Anton
________________________________

**Comment by audito67** [comment]
I have two DDS238 smart meters calculate how much is consumed from the network or transferred to the load. The amount of energy received from the solar panels is calculated by the inverter, although not entirely accurately, but this suits me, since there is no sale to the network. The main purpose of using INA228 is to calculate the filled/consumed energy from batteries and, as additional information, control battery degradation.
Energy calculation is easy to implement by multiplying the battery capacity by its voltage, there is no question here. I initially thought that the INA228 counts and stores data in a register, but after studying the datasheet in detail, I realized that I was wrong.
Before using INA228, I determined the amount of energy in the battery using BMS, but depending on the version of the BMS software, the accuracy of the calculated capacity varies greatly. As a consequence, this parameter cannot be used unconditionally. INA228 allows for more accurate counting, but the issue of spontaneous, unauthorized data dumping arises. I completely agree with you that counting can be done using CA, provided that the pause between the data before and after the reset is not long. But if there is a pause in data transmission for, for example, 1 hour and at that time the battery received a charge with a current of 20-30A, then the data on this energy will be lost. In my opinion, there are two options for solving this problem: 1. this is to perform an authorized reset, without being tied to the operation of the ESP firmware. The operating algorithm requires that each time the firmware is loaded, registers are configured and data is reset. If you configure without clearing the Charge register, the data will be saved in it, provided that the supply voltage is available. 2. This is to write data locally into non-volatile memory, but this is a separate energy monitoring project and an independent device similar to Victron Smart Shunt.
I apologize for such a lengthy message, I was expressing my thoughts.

BR, Valery

**Comment by audito67** [comment]
How do you like the idea of implementing a project with eeprom? I, in turn, am ready to implement and test in hardware, there are many different eeprom memory chips, if necessary, you can order the required one. If you write once a minute, the maximum error will be a few percent, and the operating time of such memory will be 6 years, provided that you write to the same memory cells and the number of rewrite cycles is 100,000. If you periodically change the memory area for recording data, the resource will increase factor of.

**Comment by taHC81** [comment]
Maybe you can use https://esphome.io/components/number/template with restore_value . And take it easy, you're not controlling tokamak :)

**Comment by audito67** [comment]
Thank you. I just shared my ideas, nothing more. That's for sure, let others control the tokomak. :)

**Comment by latonita** [comment]
@taHC81 hi. would you dare to test latest version? :)
