### ISSUE TITLE
Board Request: Lilygo T-Internet-POE 

### ISSUE THREAD

**Issue by Lgeorge-V** [esphome/feature-requests#2566]
**Describe the problem you have/What new integration you would like**

I would like the Lilygo T-Internet-POE board to get direct support in the esphome environment. 
![T-ETH-POE](https://github.com/esphome/feature-requests/assets/132116360/3da863f5-82d2-4deb-82d5-c3af8a7c2f2a)

**Please describe your use case for this integration and alternatives you've tried:**

This ESP32 board supports both being powered by POE and using ethernet.

**Additional context**

Here is a link to the exact board I am talking about.
https://www.lilygo.cc/products/t-internet-poe

**Comment by nagyrobi** [comment]
Did you look at the docs?
https://esphome.io/components/ethernet

**Comment by Lgeorge-V** [comment]
Yes, I looked at the docs, however having this board as a board type in the config of esphome would be nice.

**Comment by nagyrobi** [comment]
Perhaps you didn't notice, but in the docs the 3rd configuration example shows the specific config for this board.
