### ISSUE TITLE
RP2040 PIO LED Strip documentation does not include other options from light. 

### ISSUE THREAD

**Issue by fodfodfod** [esphome/feature-requests#2595]
**Describe the problem you have/What new integration you would like**

The [RP2040 PIO LED Strip](https://esphome.io/components/light/rp2040_pio_led_strip#configuration-variables) documentation does not include that it supports all other options of the Light Component. The [FastLED Light](https://esphome.io/components/light/fastled#configuration-variables) makes it clear that it supports all other options from Light. 

**Please describe your use case for this integration and alternatives you've tried:**

This would make it clearer that the RP2040 LED Strip supports all components from Light. 

**Additional context**

At the bottom of the FastLED Light configuration variables it lists "All other options from [Light](https://esphome.io/components/light/#config-light)."

**Comment by ssieb** [comment]
Can you make a PR to add it?
