### ISSUE TITLE
Support SNTP with ESP-IDF version > 5.0

### ISSUE THREAD

**Issue by vinhpn96** [esphome/feature-requests#2611]
**Describe the problem you have/What new integration you would like**

Could not build sntp component with ESP-IDF version > 5.0
**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by randybb** [comment]
Sure, this is the one of the reasons why esphome is still on esp-idf 4.4 - a rework of sntp is needed. There is no need for such feature request.

**Comment by vinhpn96** [comment]
> Sure, this is the one of the reasons why esphome is still on esp-idf 4.4 - a rework of sntp is needed. There is no need for such feature request.

@randybb 
when is esphome on esp-idf > 5.0 ?

**Comment by randybb** [comment]
No time plan, but probably this year. Most of the components are working fine (most of my devices are running on esp-idf 5.1.2), some need to be rewritten. But I am not developer - they know what is the best to do.

**Comment by vinhpn96** [comment]
> No time plan, but probably this year. Most of the components are working fine (most of my devices are running on esp-idf 5.1.2), some need to be rewritten. But I am not developer - they know what is the best to do.

Thank you for letting me know
