### ISSUE TITLE
Time Based Cover needs a post-completion action

### ISSUE THREAD

**Issue by gausie** [esphome/feature-requests#2656]
**Describe the problem you have/What new integration you would like**
I want to program a time_based cover but this specific hardware requires the stop_action to be fired after the time has passed (for both opening and closing), otherwise it is locked from being controlled by the physical remote.

**Please describe your use case for this integration and alternatives you've tried:**
It would be great for a new boolean config to be added that can either carry out this specific behavior, or allow for a more generic "post_completion" action to be defined.

I currently have it implemented as a template cover, but it would be nicer to use the time_based cover that it more accurately fits.

**Additional context**

**Comment by nagyrobi** [comment]
You already have the `on_open` and the `on_closed` triggers for this. You can simply repeat what you have at `stop_action` there.
