### ISSUE TITLE
Add fan to bang bang climate control

### ISSUE THREAD

**Issue by AalianKhan** [esphome/feature-requests#266]
**Describe the problem you have/What new integration you would like**

Most HVAC systems have a fan. It will be great to have a heating+cooling+fan configuration. And if you can switch the fan modes too that will be great. Auto = whenever the heater or ac is on. Always on = always on
**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by OttoWinter** [comment]
No, bang_bang is solely for controlling a single variable to a specific range.

I don't want the integration to become convoluted with extra stuff like fans etc.

I also don't understand why an additional switch for the fan in HA would not work.
