### ISSUE TITLE
Support for WCH(Jiangsu Qin Heng) CH422G  I/O Expander

### ISSUE THREAD

**Issue by lboue** [esphome/feature-requests#2671]
**Describe the problem you have/What new integration you would like**

Support for WCH(Jiangsu Qin Heng) CH422G I/O Expander

**Please describe your use case for this integration and alternatives you've tried:**

[Waveshare ESP32-S3-Touch-LCD-4.3 board](waveshare):
As the 4.3-inch screen occupies most GPIO pins, we use a CH422G chip to expand IO for functions like reset and backlight control.

- Manufacturer WCH(Jiangsu Qin Heng)
- Mfr. Part # CH422G
- LCSC Part # C57543
- Package SOP-16
- Description 8 * 1MHz SOP-16 I/O Expanders
- Datasheet: [CH422DS1.PDF](https://www.wch-ic.com/downloads/file/315.html?time=2024-07-29%2002:02:32&code=Fxex1sTRHysGLS6ALgh7PTOOZnAACY6KTQx05vzD)
- Product page: [Digital Tube Display Driver and I/O Expansion Chip CH422](https://www.wch-ic.com/products/CH422.html)

**Additional context**

[CH422DS1.PDF](https://github.com/user-attachments/files/16404752/CH422DS1.PDF)

Remote I/O extension

* The CH422 is connected to an external microcontroller via the 2-wire serial interfaces SCL and SDA, and capacitor C3 is used for power decoupling.
* The IO7 to IO0 pins of CH422 can be used for input or output
* The IO6 and IO7 pins are used to drive LEDs of both polarities in the figure. 

![image](https://github.com/user-attachments/assets/433d4d8e-8ab9-4dca-af90-19ba55e50e45)

The communication process between MCU and CH422 is always divided into six steps. According to the operation direction of MCU, it is divided into two types: 
 write operation for output data
 read operation for input data

Read operation consists of six steps:
 * output start signal
 * output byte 1
 * response 1
 * output byte 2
 * response 2
 * output stop signal

Write operation consists of six steps:
 * output start signal,
 * output byte 1
 * response 1
 * output byte 2
 * response 2
 * output stop signal.

**Comment by lboue** [comment]
I found 2 forks from [ESP32_IO_Expander](https://github.com/esp-arduino-libs/ESP32_IO_Expander) that include drivers for CH422G I/O Expander:
 * kylix-rd: [ESP32_IO_Expander](https://github.com/kylix-rd/ESP32_IO_Expander)
 *

**Comment by lboue** [comment]
[ESP32_IO_Expander Release v0.0.3](https://github.com/esp-arduino-libs/ESP32_IO_Expander/releases/tag/v0.0.3) is out 
**v0.0.3 - 2024-05-07**
Enhancements:
- Add support for CH422G from Waveshare
- Update the example to show how to use the CH422G

**Comment by lboue** [comment]
> I found 2 forks from [ESP32_IO_Expander](https://github.com/esp-arduino-libs/ESP32_IO_Expander) that include drivers for CH422G I/O Expander:
> 
> * kylix-rd: [ESP32_IO_Expander](https://github.com/kylix-rd/ESP32_IO_Expander)
> * ktand: [ESP32_IO_Expander](https://github.com/ktand/ESP32_IO_Expander)
> 
> This could help to add support to ESPHome.

Or maybe it could be added a ESPHome componant like another [PCA9554 I/O Expander](https://esphome.io/components/pca9554.html).

**Comment by Per4merKC** [comment]
I'm interested in this also... Thanks!

**Comment by styphonthal** [comment]
Has anyone moved forward with this?

**Comment by lboue** [comment]
> Has anyone moved forward with this?

No.

**Comment by jesterret** [comment]
It would be great if anyone is interested in trying it out and giving me feedback on it ;)

**Comment by lboue** [comment]
> It would be great if anyone is interested in trying it out and giving me feedback on it ;)

I'm in the process of testing.

**Comment by lboue** [comment]
> It would be great if anyone is interested in trying it out and giving me feedback on it ;)

Working fine and tested with this config file: https://github.com/lboue/ESPHome_Waveshare_ESP32-S3_Touch_4.3/blob/main/Waveshare_ESP32-S3_Touch_4.3.yaml

**Comment by lboue** [comment]
CH422G support has been merge into dev branch:
![image](https://github.com/user-attachments/assets/73be6df0-46b6-49e4-955f-86d2a25a0b8c)

**Comment by ThermIQ** [comment]
I believe th proper bitmap for the CH422G controlregister shoulde be
`
    //
    // Bit:        |    7    |  6  |  5  |    4    |    3    |    2    |    1     |    0    |
    //             |   ---   | --- | --- |   ---   | ------- | ------- | -------- | ------- |
    // Value:      | [SLEEP] |  /  |  /  | [OD_EN] |         |[A_SCAN] |          | [IO_OE] |
    //             |   ---   | --- | --- |   ---   | ------- | ------- | -------- | ------- |
    // Default:    |    0    |  0  |  0  |   0     |    0    |    0    |    0     |    1    |
`

**Comment by cotthemh** [comment]
there is an error when you compile it with the latest version
src/main.cpp: In function 'void setup()':
src/main.cpp:5686:57: error: invalid new-expression of abstract class type 'esphome::ch422g::CH422GGPIOPin'
 5686 |   ch422g_ch422ggpiopin_id_2 = new ch422g::CH422GGPIOPin();
      |                                                         ^
In file included from src/esphome.h:18:
src/esphome/components/ch422g/ch422g.h:49:7: note:   because the following virtual functions are pure within 'esphome::ch422g::CH422GGPIOPin':
   49 | class CH422GGPIOPin : public GPIOPin {
      |       ^~~~~~~~~~~~~
In file included from src/esphome/core/hal.h:4,
                 from src/esphome/components/adc/adc_sensor.h:6:
src/esphome/core/gpio.h:61:23: note:     'virtual esphome::gpio::Flags esphome::GPIOPin::get_flags() const'
   61 |   virtual gpio::Flags get_flags() const = 0;
      |                       ^~~~~~~~~
src/main.cpp:5692:55: error: invalid new-expression of abstract class type 'esphome::ch422g::CH422GGPIOPin'
 5692 |   ch422g_ch422ggpiopin_id = new ch422g::CH422GGPIOPin();
      |                                                       ^
/config/esphome/wallthermostat.yaml:329:57: error: invalid new-expression of abstract class type 'esphome::ch422g::CH422GGPIOPin'
  329 |       - seconds: "*"

**Comment by Real-Taz** [comment]
@cotthemh 
Have you find a way around it?
I've encounter this now in version 2025.4
