### ISSUE TITLE
Milliseconds in log

### ISSUE THREAD

**Issue by g-kiss** [esphome/feature-requests#2675]
**Describe the problem you have/What new integration you would like**

It would be very useful if the log also contains milliseconds.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by ssieb** [comment]
The times in the logs are added by the receiving application, so they will be affected by wifi delays or queuing or whatever else.

**Comment by g-kiss** [comment]
I understand, thank you.
