### ISSUE TITLE
Add support for Meizi BT Hygrothermo

### ISSUE THREAD

**Issue by jamesyym** [esphome/feature-requests#273]
**Describe the problem you have/What new integration you would like**

This library doesn't seem to support Meizi BT Hygrothermo. It is an smart IR remote and temperature and humidity sensor.

**Please describe your use case for this integration and alternatives you've tried:**

Will you please add the support for this device?
Thank you very much!

**Additional context**

Here is the project of Home-assistant sensor platform for Meizi BT Hygrothermo temperature and humidity sensor.
https://github.com/373137461/Meizu_Hygrothermo

**Comment by tiandeyu** [comment]
Hi Otto,
I‘ve written an Arduino code snippet to obtain temperature/humidity data through BLE from the Meizu sensor.
It could be best if this solution can be integrated into esphome and act as a BLE sensor.

Thanks,
Natic
