### ISSUE TITLE
Add brightness restoring for light platforms

### ISSUE THREAD

**Issue by definitio** [esphome/feature-requests#277]
It would be nice to restore previous value.

**Describe the problem you have/What new integration you would like**

Brightness is always 100% after reboot for monochromatic light and custom light, maybe for other platforms too.

**Please describe your use case for this integration and alternatives you've tried:**

I described my use case in [this PR](https://github.com/esphome/feature-requests/issues/230).  I've tried to use monochromatic light with custom output and custom light. Both work good until reboot, but doesn't restore brightness.

**Additional context**

Probably I can store brightness in global variable and restore it on boot, but I don't know how to set it from custom component.

**Comment by OttoWinter** [comment]
Already exists and is happening (you can control it with `restore_mode` option).

If there's an issue with it please open a bug report (preferably with very_verbose logs with SAVE and LOAD lines)
