### ISSUE TITLE
qrcode generation using LVGL

### ISSUE THREAD

**Issue by gbouille** [esphome/feature-requests#2915]
**Describe the problem you have/What new integration you would like**

I would like to be able to use de qrcode component to be displayed with LVGL.

**Please describe your use case for this integration and alternatives you've tried:**

Actually there is a qrcode component that can be use to display qrcode. I have found no information to use it with LVGL. So if this is already possible, could you document it. Otherwise create a qrcode LVGL widget to display it.

**Additional context**

**Comment by clydebarrow** [comment]
Done.

https://github.com/esphome/esphome/pull/7623
