### ISSUE TITLE
Include the configuration YAML file into the final image

### ISSUE THREAD

**Issue by noseshimself** [esphome/feature-requests#2919]
**Describe the problem you have/What new integration you would like**

It is hard to recreate a configuration yaml file from an existing image. Backing up the files is of course a good idea but does not help if you receive a ready-to-use device from someone else.

**Please describe your use case for this integration and alternatives you've tried:**

Please add an option to include the original ESPHome configuration in the image. There is no need to include secrets.yaml but don't waste time on removing passwords if the creator decided to put them into the configuration itself. Make it easy to find the data by using a unique marker next to it.

Bonus: Add a sub command to ``esphome`` to extract a configuration from an image or even a connected device. Optionally add a way of displaying the configuration to the web server.

Alternatives I tried: Cursing, crying, threatening and bribing the original author. Nothing helped; even filling him with energy drinks did not yield the desired result.

**Additional context**

**Comment by randybb** [comment]
Already requested multiple times https://github.com/esphome/feature-requests/issues/528, https://github.com/esphome/feature-requests/issues/939 and https://github.com/esphome/feature-requests/issues/1507

So if you want, you can use the external component mentioned under previous requests. But this will not force anybody to publish his original yaml.
