### ISSUE TITLE
Add info how to play with lan8720 on WT32-ETH01 V1.4

### ISSUE THREAD

**Issue by mati294** [esphome/feature-requests#2940]
**Describe the problem you have/What new integration you would like**

Please add this working config to instruction about lan8720
**Please describe your use case for this integration and alternatives you've tried:**

This code works for: 
WT32-ETH01  V1.4
`
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

`
**Additional context**

**Comment by nagyrobi** [comment]
Is it different from what's in the doc?
