### ISSUE TITLE
Allow control to specify timeout interval before control becomes unavailable 

### ISSUE THREAD

**Issue by vamichael** [esphome/feature-requests#295]
**Describe the problem you have/What new integration you would like**
Be able to specify in the control the period a control is disconnected before it reports being unavailable.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by OttoWinter** [comment]
Please fill out the full template. The description you wrote is really lacking and I'm struggling to understand what you mean.
