### ISSUE TITLE
Possible to add Time component input so it is easy for setting up time in EspHome

### ISSUE THREAD

**Issue by paulsteigel** [esphome/feature-requests#2975]
**Describe the problem you have/What new integration you would like**

I would like to add a time input in Esphome (see attached picture) so I can dynamically adjust time for implementing required action. My current way is adding 3 sliders for hour, minute, second (see 2nd photo). It would be way too much to do so for multiple time inputs that are needed for irrigation control.
Image 1: time input component on Home assistant for setting up start and end time for doing something
![image](https://github.com/user-attachments/assets/e4d387da-9d88-4d2f-af2c-312fe07bb2e9)
(Start time and End time)
Image 2: My walkaround with using 2 sliders for hour and minute.
![image](https://github.com/user-attachments/assets/59261a54-a176-4cb1-a2c4-03aaa08baf96)
(Duration for action, hour to start, minute to start)
**Please describe your use case for this integration and alternatives you've tried:** 

Adding a time input in esphome is way complicated, I often have to do it in code or using the previous  walkaround.
**Additional context**

It would be very convenient for user like us if a feature like this is available in esphome. for example we just need to do config like below
input:
```
 - platform: esphome
  id: start_timer
  name: Pump start time
  option: full_time| hour| hour_minute
  restored: yes
....
```
Many thanks for your attention!

**Comment by ssieb** [comment]
https://esphome.io/#datetime-components
If you need help with using that, come ask on the esphome discord server.
