### ISSUE TITLE
E1.31 Request - Falcon Player / xLights Stuff

### ISSUE THREAD

**Issue by MrPaulAR** [esphome/feature-requests#3]
**Is your feature request related to a problem/use-case? Please describe.**

Use case.  Would like to be able to add E.131 receiver support.  There is code available (PixelStick) for ESP8266 I believe but would love the ease of deployment that ESPHome provides.

**Describe the solution you'd like**

**Additional context**

**Comment by MrPaulAR** [comment]
Yes,  I know it's got that as well but maybe I would like to do something more powerful with my ESPixelStick such as control a relay that powers the power to the lights.  Or maybe since this will likely be in some sort of box use a DHT11 to capture humidity & temperature to ensure nothing is too out of wack in that box.

I know how to do all this with ESPHome but without the E1.31 universe bindings the last bit is just out of reach.

**Comment by Quindor** [comment]
I definitely second this request, it would make for the perfect Home Assistant integration of Addressable LEDs.

I imagine the following scenario, during normal times you could choose from the available presets built into ESPhomelib and run those. But for special occasions when you would like to do something special, it would be awesome if you could use a "switch" in Home Assistant to put the output channel (ws2812b or whatever strip) into E1.31 mode.

Then when the special occasion passes and you just want rainbows or some other effect you'd switch it back to under ESPhomelib's control and done.

**Comment by austwhite** [comment]
This is an interesting option and I would like to see it.  I have PinkyLEDs currently (by PinkyWafer) that uses MQTT and has an E131 option, but I would like to move everything to to ESPHome eventually

**Comment by Tuckie** [comment]
It doesn't look too hard to implement, assuming there aren't any conflicts: https://github.com/forkineye/ESPAsyncE131/blob/master/examples/E131_Test/E131_Test.ino

**Comment by Kosh42** [comment]
If only. I'd love this feature.

**Comment by ayufan** [comment]
You might look at my custom components: https://github.com/ayufan/esphome-components.

I will try to upstream my changes to make it part of regular distribution.

**Comment by jchambers2012** [comment]
I believe this could now be closed?
https://esphome.io/components/light/index.html#e1-31

**Comment by MrPaulAR** [comment]
Feature appears to exist.
