### ISSUE TITLE
INA169 voltage/current sensor

### ISSUE THREAD

**Issue by pauldogg** [esphome/feature-requests#300]
**Describe the problem you have/What new integration you would like**

I would like to integrate into ESP home and retrieve readings from the ina169 chipset
**Please describe your use case for this integration and alternatives you've tried:**

Similar to the ina219, i would please like support for the ina169 which has more amperage, better suited for a solar panel
**Additional context**

There is already an adafruit library

**Comment by pilotak** [comment]
If i'm not mistaken, INA169 is analog output IC so you can measure it with ADC

```yaml
sensor:
  - platform: adc
    pin: A0
```

**Comment by OttoWinter** [comment]
@pilotak Is correct, this is an analog sensor, so you should use `adc`
