### ISSUE TITLE
Safe boot mode

### ISSUE THREAD

**Issue by Anonym-tsk** [esphome/feature-requests#302]
**Describe the problem you have/What new integration you would like**
Detect problems in runtime and boot in safe mode with only `wifi` and `ota` components enabled.

**Please describe your use case for this integration and alternatives you've tried:**
I can write bad (but valid) yaml config, flash it over the air and my device will not boot.

**Additional context**
I have a few embedded device and after bad flashing i need to disassemble device and flash it with wire. I really need possibility to boot device in safe mode and flash it over the air.

**Comment by OXOTH1K** [comment]
Great idea!

**Comment by to4ko** [comment]
Want this one too!

**Comment by OttoWinter** [comment]
Already exists and enabled by default. See ota safe mode.

**Comment by glmnet** [comment]
What would be different from current safe mode? https://esphome.io/components/ota.html

**Comment by Anonym-tsk** [comment]
@OttoWinter i'm not sure that `safe_mode` works.
Last 3 days i have one problem - I flash device over the air and... it's offline. In the evening i fix problem in config and flash it by wire. Right now one my device is offline. And yes, `safe_mode` is enabled.

**Comment by OttoWinter** [comment]
@Anonym-tsk Then you might have an issue with WiFi - see the pinned issue in the bug tracker. If wifi doesn't work of course the device will also not be able to connect to the network for ota safe mode.

**Comment by Anonym-tsk** [comment]
@OttoWinter no-no, it's not wifi problem. For example i can broke device with [Custom Sensor](https://esphome.io/components/sensor/custom.html) (it's easy), but i can do it with embedded components too.

**Comment by OttoWinter** [comment]
@Anonym-tsk Then you should create an issue with the code that causes it and the logs with it. The feature already exists, if there's a bug please open a bug report.
