### ISSUE TITLE
Add support for RuuviTag sensors

### ISSUE THREAD

**Issue by ryhanen** [esphome/feature-requests#313]
**Describe the problem you have/What new integration you would like**

I would like to use RuuviTag (https://ruuvi.com/) BLE sensors to collect environmental data. RuuviTags are affordable, accurate and long lasting battery powered sensors providing data over BLE:

*RuuviTag is an advanced open-source sensor beacon platform designed to fulfill the needs of business customers, developers, makers, students, and can even be used in your home and as part of your personal endeavours.*

**Please describe your use case for this integration and alternatives you've tried:**

I would use esphome (esp32_ble_tracker) to collect environmental data from RuuviTag sensors placed around the house and publish it to Home-assistant. There are various implementations available especially focusing on visualizing the sensor data for RuuviTags. However, I would like to use the sensors as part of my home automation system. The use case is similar to using Xiaomi MiJia sensors. 

**Additional context**

[Official RuuviTag firmware description](https://lab.ruuvi.com/ruuvitag-fw/)
[RuuviTag data format specs](https://github.com/ruuvi/ruuvi-sensor-protocols)

**Comment by salleq** [comment]
There also exists a Python library - I think some bits could be reused, at least for the data format decryption part. I'm willing to help with this since this was how I intended to use the tags myself as well, however I'm not an expert coder :) 

Link to the library below:
https://github.com/ttu/ruuvitag-sensor
