### ISSUE TITLE
Momentairy button

### ISSUE THREAD

**Issue by thostie2002** [esphome/feature-requests#317]
**Describe the problem you have/What new integration you would like**

I want a intergration for a pushbutton 
So i can start a automation by pushing that button

The button i’m thinking of is a momentairy switch, look at the link ==>. https://www.google.nl/search?q=momentary+switch&client=safari&hl=nl-nl&prmd=sivn&source=lnms&tbm=shop&sa=X&ved=2ahUKEwjOqLbg36jjAhXLUlAKHf_LDxoQ_AUoAXoECA0QAQ&biw=768&bih=922

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by rradar** [comment]
@thostie2002 you can do it already!

Give a look in the docs: https://esphome.io/components/binary_sensor/gpio.html

**Comment by glmnet** [comment]
As a @rradar many combinations are supported with filters. Your question is not precise enough. I'm closing this, but you can reopen it if you add more information why this is not supported yet.
