### ISSUE TITLE
MCP23017 PWM

### ISSUE THREAD

**Issue by alexyao2015** [esphome/feature-requests#334]
**Describe the problem you have/What new integration you would like**

I would like to be able to use a monochromatic light with an MCP23017. Currently there is no way to do software PWM with this. There is no way to get a float GPIO with this i/o expander.

**Please describe your use case for this integration and alternatives you've tried:**

I've tried to use the esp8266_pwm platform but am unable to do so.
**Additional context**

**Comment by OttoWinter** [comment]
No, the MCP23017 can not handle PWM well - any PWM for the MCP23017 would need to use a software-PWM, which would have tons of timing issues (flickering when wifi is on etc).

Please look at the other PWM modules (like PCA9685) instead.
