### ISSUE TITLE
external sensor with webhook 

### ISSUE THREAD

**Issue by lubeda** [esphome/feature-requests#342]
Create sensors with esphome that not connect to the local wlan but instead transmit theire sensor data via webhooks/nabucasa

e.g. a sensor in my work office wich motintors the plants there and is connected tothe public wlan in the office. to get the data to my home office i like to uses webhooks

without this feature i had to use esp-easy,micropython or native arduino code to program such a sensor. wich is quiet heavy. doing it all in esphome would be much more easy and will open a lo of new use cases for esphome

There is also a discussion on the forum: https://community.home-assistant.io/t/esphome-sensor-via-nabucasa-webhook/127028

**Comment by OttoWinter** [comment]
We should not add this natively - we already have enough communication methods (MQTT, api, web server). Each of them must have their own implementations to handle the communication to the respective other end. Adding a new type of communication method would be too much work.

However, the new http component added in future versions of esphome will allow you to post data to HA - you just need to create an on_value hook that sends an HTTP POST request to your HA endpoint.
