### ISSUE TITLE
Support for hmc5883l compass module

### ISSUE THREAD

**Issue by pilotak** [esphome/feature-requests#347]
**Describe the problem you have/What new integration you would like**

I noticed that MPU6050 is supported, to make complete (9DOF) it would be good to have HMC5883L supported as well

**Please describe your use case for this integration and alternatives you've tried:**

I need to build ESP32-CAM with compass support, as this will be mounted on rotor antenna so i know which direction is heading to.

**Additional context**

Here is the lib https://github.com/adafruit/Adafruit_HMC5883_Unified

**Comment by OttoWinter** [comment]
Please read the docs index page.

**Comment by pilotak** [comment]
Silly me, sorry I didn't find it
