### ISSUE TITLE
Flicker to hover with current brightness as the middle value

### ISSUE THREAD

**Issue by Joshfindit** [esphome/feature-requests#348]
**Describe the problem you have/What new integration you would like**

When flicker is called, it dims significantly, seeming to make the current brightness the *max* brightness, then the natural flicker rarely if ever lands on the brightness again.

**Please describe your use case for this integration and alternatives you've tried:**

Ideally, I would like if I was able to set the brightness to an arbitrary value, then have a flickering 'candle light' that stays around that brightness

**Additional context**

There will also be logic to consider when brightness starts at 100%. I would still prefer that 100% be the 'average' brightness. Possibly with a mapping like `101% = 99%`, `105% = 95%`, `140% = 60%`, etc

Both this and https://github.com/esphome/issues/issues/555 may end up being closed with the same code change

**Comment by OttoWinter** [comment]
Yeah that's what the flicker effect is supposed to do - I will merge this into the mentioned issue, because it's not really a feature request.
