### ISSUE TITLE
Support for Philips PCD8544 84x48 monochrome LCD, used by the Nokia 5110 display

### ISSUE THREAD

**Issue by fredrike** [esphome/feature-requests#354]
**Describe the problem you have/What new integration you would like**

The Nokia 5110 LCD display is dirt cheap and quite nice as it does not glow all the time as an OLED. It would be super nice if it could supported by esphome.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

There is already a micro python library, but I'm not sure how to integrate it into EspHome: https://github.com/mcauser/MicroPython-ESP8266-DHT-Nokia-5110

**Comment by freekode** [comment]
so hm...any plans to add integration?
