### ISSUE TITLE
APRS.FI

### ISSUE THREAD

**Issue by charudatt** [esphome/feature-requests#362]
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

Looking forward to a way to connect to APRS.FI to post Weather Information through ESPHome

**Comment by OttoWinter** [comment]
No, that's not esphome's focus - anything involving HTTP rest apis etc should be handled by a more powerful machine (and in a different programming language), for example Home Assistant.
