### ISSUE TITLE
Support Magicblue BLE Led bulb

### ISSUE THREAD

**Issue by tototek** [esphome/feature-requests#373]
Can the Magic Blue BLE LED bulb be added as a component?
Can you guide me to create the component?
I appreciate the help

**Comment by OttoWinter** [comment]
Please fill out the feature request template.

Also, there's not really a guide to BLE device creation, but you can follow the general custom component guides (like custom light) and look at the recent code changes to integrate some xiaomi ble devices into the codebase.
