### ISSUE TITLE
Support AutoConnect

### ISSUE THREAD

**Issue by awarecan** [esphome/feature-requests#376]
**Describe the problem you have/What new integration you would like**

I want to use ESPHome in a project where the device will be shipped to customer. Therefore I cannot hard code wifi information, but need introduce some sort of onboarding process, either through a mobile app or web interface. 

**Please describe your use case for this integration and alternatives you've tried:**

Ideally I am thinking connect to board using bluetooth, then I found [AutoConnect](https://github.com/Hieromon/AutoConnect) project that is using SoftAP mode + captive portal. It looks promising.

I was also looking the SmartConfig, but some people suggested that technical cannot reliable running on mix of 2.4G/5G WiFi environment. 

**Additional context**

**Comment by OttoWinter** [comment]
See https://github.com/esphome/esphome/pull/624
