### ISSUE TITLE
Add linear dimmer option

### ISSUE THREAD

**Issue by poldim** [esphome/feature-requests#379]
**Describe the problem you have/What new integration you would like**

Dimming does not dim smoothly. Setting something to 50% brightness actually results in a 50% power output but maybe 80% brightness. 

**Please describe your use case for this integration and alternatives you've tried:**

All of my lights on ESPHome. 

**Additional context**

This site, https://jared.geek.nz/2013/feb/linear-led-pwm, provides a nice description of the solution.

**Comment by OttoWinter** [comment]
See `gamma_correct`

**Comment by poldim** [comment]
@OttoWinter any chance you can explain how to use gamma correct to map 0-100% dimmer to appear correctly as 0-100 to the naked eye?  Documentation on this topic seems very light.
