### ISSUE TITLE
Support on_value, on_value_range with mqtt payload or variable instead only float...

### ISSUE THREAD

**Issue by itProfi** [esphome/feature-requests#387]
**Describe the problem you have/What new integration you would like**
I want send target temperatures for sensor automation, for examle via mqtt, and store it in eprom (for thermostat).. 

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by OttoWinter** [comment]
See mqtt_subscribe sensor or mqtt docs (on_message)
