### ISSUE TITLE
Support for MCP3008

### ISSUE THREAD

**Issue by SonnyJim** [esphome/feature-requests#394]
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

The MCP3008 ADC would be a useful sensor addition, as it would allow a wide variety of devices to be used.  For example, I'd like to use some IR sensors with ESPHome that work by outputting a 0v-5v signal.  The MCP3008 works on an SPI bus and there's libraries available for the ESP8266, so integration shouldn't be massively difficult (I may try it myself)
**Additional context**

**Comment by SenexCrenshaw** [comment]
Working on it in PR GH-1057
