### ISSUE TITLE
Support partial rc_switch_raw remote_receiver code matching

### ISSUE THREAD

**Issue by aalbul** [esphome/feature-requests#401]
**Describe the problem you have/What new integration you would like**

I am using https://esphome.io/components/remote_receiver.html component to create binary sensor based on 433 code that my Sonoff RF Bridge receives.
Unfortunately, one of my devices is sending rolling codes so it is impossible do exact matching of the code.
In my case first 8 symbols of the code is always the same for my device. I'd like to have a chance to do partial matching (startsWith) or maybe ability to use lambda for custom trigger?

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by OttoWinter** [comment]
Closing per https://github.com/esphome/esphome/pull/650
