### ISSUE TITLE
MAX7219 with common anode displays

### ISSUE THREAD

**Issue by mutlucan96** [esphome/feature-requests#408]
**Describe the problem you have/What new integration you would like**

Common anode 7 segment displays don't work with current integration.

**Please describe your use case for this integration and alternatives you've tried:**

I tried wiring as in [this](http://www.plingboot.com/2017/01/max7219-and-common-anode-displays/) article but looks like some changes on the code also needed and I'm not familiar with C.

**Additional context**

**Comment by OttoWinter** [comment]
This seems like too little of a use-case to justify writing a bunch of code for this special configuration - these displays are super cheap! I'm closing this one but if someone wants to implement this please do.
