### ISSUE TITLE
LinkIT 7697 platform support

### ISSUE THREAD

**Issue by Valcob** [esphome/feature-requests#410]
**Describe the problem you have/What new integration you would like**

I would be so nice to have along with eps8266 and esp32 another not as well known platform MT 7697 which is so alike esp32 and in some cases even better.

**Please describe your use case for this integration and alternatives you've tried:**

It would be nice to reflash all xioami lights that have this module and bring them into ESPHOME family :) 
**Additional context**

As a good point of start would be the ref to Arduino lib and how Tos:
[Arduino Documentaion](https://docs.labs.mediatek.com/resource/linkit7697-arduino/en/developer-guide/limitations-of-linkit-7697)
and a PDF about the chip itself:
[MT 7697 Datasheet](https://labs.mediatek.com/en/download/njdlGO4b)

**Comment by randybb** [comment]
It needs to be supported by PlatformIO first https://github.com/platformio/platformio-core/issues/992 (open since July 2017) and then, probably, it should not be a big problem.

**Comment by OttoWinter** [comment]
No, ESPHome will only support ESPs (it's in the name of the project even).

Supporting the WiFi stack and some peripherals on the ESP8266/ESP32s is already enough work. Adding more platforms is not a path this project should go down.
