### ISSUE TITLE
Add support for IR-FC51 module

### ISSUE THREAD

**Issue by stich86** [esphome/feature-requests#412]
**Describe the problem you have/What new integration you would like**
Add support for IR-FC51 Proximity module

**Please describe your use case for this integration and alternatives you've tried:**

Needed to check if an obstacle is in front of the sensor to start an automation on HA instance

**Additional context**

**Comment by glmnet** [comment]
You should use a [gpio binary sensor](https://esphome.io/components/binary_sensor/gpio.html) for this. Much like a door or window.
