### ISSUE TITLE
Is there an ESPHome equivalent to the ESPEasy Serial Server?

### ISSUE THREAD

**Issue by JunShine** [esphome/feature-requests#415]
**Describe the problem you have/What new integration you would like**

Is there an ESPHome equivalent to the ESPEasy Serial Server?

**Please describe your use case for this integration and alternatives you've tried:**

I want connect a CC2530 coordinator via an ESP8266。like that https://www.zigbee2mqtt.io/how_tos/how_to_esp8266_with_cc2530.html
I wondered whether it would be possible to do the same using ESPHome。How to fill in the ESPHome configuration entry？

**Additional context**

**Comment by minsuke** [comment]
You mean like ser2net component? i wish this can be applied serial devices, it will be connected with old devices which use old serial connection. Great fuction !!

**Comment by JunShine** [comment]
Yes！ser2net component！

**Comment by brandond** [comment]
ESPHome is primarily meant to work with Home Assistant, either via MQTT or API. While many of the components can be used standalone, some of the dedicated single-purpose functionality like acting as a generic serial gateway is absent. You might be able to cobble something together with lambdas and mqtt on_message triggers but it wouldn't be pretty.

If you had a specific use case that involved using a CC2530 to connect various devices to Home Assistant that might find more traction.

**Comment by JunShine** [comment]
> ESPHome is primarily meant to work with Home Assistant, either via MQTT or API. While many of the components can be used standalone, some of the dedicated single-purpose functionality like acting as a generic serial gateway is absent. You might be able to cobble something together with lambdas and mqtt on_message triggers but it wouldn't be pretty.
> 
> If you had a specific use case that involved using a CC2530 to connect various devices to Home Assistant that might find more traction.
Yes，use zigbee2mqtt (https://www.zigbee2mqtt.io/  or  https://github.com/Koenkk/zigbee2mqtt)，Allows you to use your Zigbee devices without the vendors bridge or gateway.It bridges events and allows you to control your Zigbee devices via MQTT. In this way you can integrate your Zigbee devices with whatever smart home infrastructure you are using. Currently 380 devices are supported from 84 different vendors.( here https://www.zigbee2mqtt.io/information/supported_devices.html)
Zigbee2mqtt needs to communicate with zigbee devices via CC2531/CC2530. and I found that use the serial port in esp8266 to connect cc2531/cc2530 and use it as a coordinator to send data to the mqtt gate. on  https://www.zigbee2mqtt.io/how_tos/how_to_esp8266_with_cc2530.html

**Comment by randybb** [comment]
This would be a great addition for these who run BTLE and RF433 gateways.

**Comment by OttoWinter** [comment]
The big problem with that is that most protocols ESPHome supports (MQTT, native API, HTTP) are *not* streaming protocols, so a serial stream cannot be represented in them.

Also, while in principle I don't have anything against this, this would be an integration that would soon get uber-generic. Maybe some user wants to split packets somehow (based on some terminating character), maybe someone wants a different protocol etc.

This would lend itself much better to custom code (which ESPHome does support quite well). I'd be happy to accept a cookbook contribution with the code required to create a serial server. That way, if users want to customize behavior, they have full access to the code.
