### ISSUE TITLE
Template cover SET_COVER_POSITION support

### ISSUE THREAD

**Issue by brandond** [esphome/feature-requests#42]
Do you have any plans to support [setting cover position](https://www.home-assistant.io/components/cover/#service-coverset_cover_position) for template covers? Additionally, is there a good way to tie a cover position sensor to the position of a slider in the Home Assistant UI? It seems like existing options require the sensor/slider to be pretty much separate from the cover and its open/closed state and open/stop/close buttons.

**Comment by nevalain** [comment]
I would also like to use the set_cover_position in template cover.

I am using generic MG 946R servos with blinds. I assume that I need simple set_cover_position and I could calculate the PWM (with lamda)?

**Comment by CTLS** [comment]
Would love to be able to use the tilt function with esphome.

**Comment by PierreScerri** [comment]
I also have 11 roller shutters in the house and it would be good to have some form of position/set_positon functionality.

Thank you.

**Comment by norges** [comment]
I try to use the cover component with my roller shutters at the moment and would love the possibility to have a position. Best case for me would be in percent wit a max/min value.

**Comment by blademckain** [comment]
also for me it would be the maximum to be able to indicate the percentage of opening of the cover
++

**Comment by OttoWinter** [comment]
Closed in https://github.com/esphome/esphome/pull/496
