### ISSUE TITLE
i2c support for MAX7219 7-segment display

### ISSUE THREAD

**Issue by erikmeliska** [esphome/feature-requests#420]
**Describe the problem you have/What new integration you would like**
I need to display information on i2c MAX7219 7-segment display

**Please describe your use case for this integration and alternatives you've tried:**
There is already SPI version, it would be great to add i2c support.

**Additional context**

**Comment by OttoWinter** [comment]
The MAX7219 is not an i2c device. The MAX7219 is an SPI device only. See https://www.sparkfun.com/datasheets/Components/General/COM-09622-MAX7219-MAX7221.pdf
