### ISSUE TITLE
 Add a transition option to light.addressable_set

### ISSUE THREAD

**Issue by marrobHD** [esphome/feature-requests#427]
**Describe the problem you have/What new integration you would like**

 Add a transition option to light.addressable_set.
**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

Nothing else

**Comment by OttoWinter** [comment]
No, that is not possible.

Transitions would require storing two instances of the entire LED array - one with the starting values and one with the current ones. If you want transitions you will have to handle that in a custom effect or other code.
