### ISSUE TITLE
Allow "temporary on" (aka: allow "flash" to take other properties, including effects)

### ISSUE THREAD

**Issue by Joshfindit** [esphome/feature-requests#428]
**Describe the problem you have/What new integration you would like**

I want to be able to fire a single call and have the light do an alert pattern before returning to the previous value.

Would like to be able to do something like
```json
{
	"entity_id": "light.d1_mini_v3_with_apa102s_lamp_1",
	"effect": "twinkle",
	"flash": "short",
	"brightness": "200",
	"transition": "0.01",
	"rgb_color": [255, 10, 10]
}
```

**Please describe your use case for this integration and alternatives you've tried:**

I've tried using `flash` in various ways, but none achieve this. (The `flash` *function* works exactly how I would like, but simply changing the colour for a short period isn't enough to get my attention)
A second call is not possible in this case as there's no "return to previous state" in ESPHome or hass.

Use-case: when someone new joins the wifi, flicker "indicator" LEDs throughout the house. This would have the effect of letting us know _before_ an expected guest knocks on the door.

**Additional context**

**Comment by OttoWinter** [comment]
That is the opposite of what the flash transform does (as you noted yourself, flash sets a single color temporarily)

Flashes (in ESPHome and HA terms) are temporary "transformers" that override the color of the light for a specific duration - and are internally using the same APIs as transitions.

Also, effects can internally start a flash (just like effects can use transitions), so allowing flashes of effects would not be possible.

This would require a big change of the semantics of flashes (i.e. flashes may no longer be used inside effects), so I will reject this feature request.

You have plenty of other options though - create an `automation` effect that cycles the light on/off a couple of times and then goes to another state.
