### ISSUE TITLE
[REQUEST] Nova SDS011

### ISSUE THREAD

**Issue by BoxedBrain** [esphome/feature-requests#43]
First thank you for your hard work!

I would love to see some implementation for the Nova SDS011 dust particle sensor.

Best regards
Tobse

**Comment by araneolusporcus** [comment]
I would love to see this also!
Please note that this sensor has a lifetime of around 1 year if running continous so it's important to make the sensor sleep between reads so it can have a lifetime of around 5 years. 
I'm currently using it on an esp8266 with https://luftdaten.info/en/home-en/ (also supports bmp280/dht22 etc.)

**Comment by OttoWinter** [comment]
Closed as per https://esphome.io/components/sensor/sds011.html
