### ISSUE TITLE
High impedance on output pins

### ISSUE THREAD

**Issue by missilerider** [esphome/feature-requests#431]
**Describe the problem you have/What new integration you would like**

It would be a great feature to add the hability to change an output pin to high impedance. It is useful on some circuits. In my specific case I need to apply current in both directions with four pins, with A+B set to 1 or 0 and C+D on high impedance (INPUT in Arduino), and other times A+B to high impedance and C+D to 1 or 0.

**Please describe your use case for this integration and alternatives you've tried:**

The main problem is that the ony way I know to set a pin to high impedance is change an OUTPUT to INPUT, and the ESPHome definition does not include this kind of behavior.

**Additional context**

I don't know if this request is possible regarding the ESPHome architecture; I'm a bit new to the framework and still have a lot of unknown spots. Please feel free to move of close the issue if it makes no sense.

**Comment by OttoWinter** [comment]
Yeah that is indeed not supported at the moment - but in ESPHome you have `lambda`s.

So you can just write:
```yaml
- lambda: |-
    pinMode(THE_PIN, INPUT);
```

in any action to put it in high impedance mode.
