### ISSUE TITLE
RC6 support for IR receive / transmit in Remote Transmitter

### ISSUE THREAD

**Issue by pinquin87** [esphome/feature-requests#439]
**Describe the problem you have/What new integration you would like**

I would like to have the RC6 IR protocol added to ESPHome for my Philips TV.

**Please describe your use case for this integration and alternatives you've tried:**

I use a ESP8266 via mqtt with Home Assistant to turn on and off my tv and audio system via IR. The ESP8266 is currently running on Tasmota. I'm in the progress of moving my 15 or so ESP devices to ESPHome because I like the integration in Home Assistant and the yaml config. The move is going great so far, but I've just run into the issue of the missing RC6 IR protocol in the Remote Transmitter component.

**Additional context**

**Comment by davidsat** [comment]
Hi,
When I run the in dump:all mode, it returns RC6 codes from my remote. But when I try to specifiy that as a protocol to dump, esphome won't let me compile it. Can this be fixed? I'm not sure what the state of RC6 support is. It seems to be partially supported?

**Comment by Eknem** [comment]
Hi,
I Also need rc6 support If I try to send de raw data the rc6 receiver does not seems to recognize te signal. I tried to set the carrier_frequentie to 36Hz.

**Comment by rarroyo6** [comment]
I also vote for this. I have 3 media center computers set up, using the MCE remote, and this integration would be fantastic.

**Comment by andrewjswan** [comment]
I also vote for this

**Comment by hExPY** [comment]
Vote 👍

**Comment by vanrace** [comment]
vote!

**Comment by koentelg** [comment]
vote!

**Comment by john-arvid** [comment]
vote! For now I use tasmota

**Comment by rradar** [comment]
available in esphome 2022.6 :tada: 

https://github.com/esphome/esphome/pull/3514
