### ISSUE TITLE
esphome on a separate network?

### ISSUE THREAD

**Issue by ministryofsillywalks** [esphome/feature-requests#441]
**Describe the problem you have/What new integration you would like**
Is it possible to have esphome running on a remote / separate network than home assistant and still have it report to this home assistant setup?

**Please describe your use case for this integration and alternatives you've tried:**
ha is exposed to the www and can be accessed fine however I can't find the option to direct esphome messages to a remote server, only the one on the same network.
I could forward a dydns to the esphome IP and access that via the web but I would prefer not to expose more ports.

**Additional context**

**Comment by OttoWinter** [comment]
See https://github.com/esphome/feature-requests/issues/46

For now, the only option is MQTT if you want to access it from a different network.
