### ISSUE TITLE
Display Turn ON/OFF 

### ISSUE THREAD

**Issue by arfrater** [esphome/feature-requests#449]
**Describe the problem you have/What new integration you would like**
A Switch to turn ON/OFF the display or reduce brightness at night time

**Please describe your use case for this integration and alternatives you've tried:**
under the switch platform or by time based to be able to turn off a display (I have a ssd1306) or reduce brightness at night time.

**Additional context**
If the screen is connected at night the displays are quite bright and if in a bedroom it would be good to reduce their brightness (by time) or even turn them off at night.

**Comment by OttoWinter** [comment]
Closing per https://github.com/esphome/esphome/pull/723
