### ISSUE TITLE
Send event to homeassistant 

### ISSUE THREAD

**Issue by andenmad** [esphome/feature-requests#459]
**Describe the problem you have/What new integration you would like**

it would be realy nice if we get the posibility to send event directly to homeassistant.

in a pres ore double click situation.

**Please describe your use case for this integration and alternatives you've tried:**

it will give posibillity to use native api with example node red and i can avoid mqtt on esphome devices.

**Additional context**

**Comment by OttoWinter** [comment]
This already exists. See the api page: https://esphome.io/components/api.html
