### ISSUE TITLE
Tl-w5mc1 5mm detecting inductive proximity sensor detection...‎.

### ISSUE THREAD

**Issue by smartie91** [esphome/feature-requests#462]
**Describe the problem you have/What new integration you would like**
Tl-w5mc1 5mm detecting inductive proximity sensor detection...‎.

**Please describe your use case for this integration and alternatives you've tried:**
would like to fit to door of fridge to check how long fridge door has been opened 

**Additional context**
this is my frist time using Github so hopefully i have done it right

**Comment by OttoWinter** [comment]
Already supported, see GPIO binary sensor.
