### ISSUE TITLE
Adjust/Calibrate RGB LEDs

### ISSUE THREAD

**Issue by docmattman** [esphome/feature-requests#463]
**Looking to adjust/calibrate my RGB LED.  When white is chosen, the light is too blue.  It'd be nice to be able to adjust it so that perhaps the max value for the blue pin would be capped at a certain lower limit so it allows less blue into the mix.**

**A resistor could be added to the blue pin, but it would certainly be easier to adjust a value in esphome instead if possible.**

**Comment by OttoWinter** [comment]
See `max_power` for output and `color_correct` for addressable lights.
