### ISSUE TITLE
API with Waveshare B/W 2.9inch and Home Assistant

### ISSUE THREAD

**Issue by soppilif** [esphome/feature-requests#464]
I have the two colors (b/w) waveshare 2.9nch epaper display and I managed to read through mqtt the state of dht sensors in my hassio.
I can't make it work through api though. I dont know how to call the display rendering service

`api:
  password: !secret wifi_pwd
  services:
    - service: temp_room2
      variables:
        temperature: float
      then:
        lambda: |-`

**Describe the problem you have/What new integration you would like**

How do I call the display rendering service in esphome so i can printf the temperature home assistant will send through the service?

`display:
  - platform: waveshare_epaper
  ...
  id: my_display
  lambda: |-
  ...`

**Please describe your use case for this integration and alternatives you've tried:**

Facing a lurning curve here...

**Comment by OttoWinter** [comment]
You need to write the value you receive in the service to a global float variable.

In the display lambda you can then access that variable to write it to the display.

I would also recommend you check out the homeassistant sensor platform. Then you don't need to use services and global vars.

This is not a feature request - please use discord or the HA formus for this type of question.
