### ISSUE TITLE
Consolidate ESPHome Dashboard

### ISSUE THREAD

**Issue by holdestmade** [esphome/feature-requests#465]
**Describe the problem you have/What new integration you would like**
Add dual / multiple columns in dashboard for nodes. I have quite a few now and need to scroll a lot to get to the last one

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

Current
![current](https://user-images.githubusercontent.com/13977244/68382157-0d90f480-014b-11ea-83f7-6e00854cb880.jpg)

Proposed Mock up
![proposed](https://user-images.githubusercontent.com/13977244/68382165-11247b80-014b-11ea-8cc5-e609986ec13e.jpg)

**Comment by danibjor** [comment]
It would have been nice if you could have the dashboard mirror the directory structure in your config folder. Would do wonders for organizing your stuff.

```
- config
  - living_room
    - lights.yaml
    - heater.yaml
  - down_stairs
    - heater.yaml
  - garage
    - lights.yaml
    - garage_door.yaml
  - outside
    - back
      - pool.yaml
      - lights.yaml
    - front
      - lights.yaml
```

This would also be logically grouped in the dashboard, in the same way as your folder structure.

**Comment by Fusseldieb** [comment]
Almost created a new feature request, but I think this is similar enough.

My request would be the ability to group ESPs into a folder. I have almost 50 devices, not joking. Scrolling through them and finding the right one is _hard_. Only Ctrl+F saves me.

**Comment by Fusseldieb** [comment]
Almost created a new feature request, but I think this is similar enough.

My request would be the ability to group ESPs into a folder.

Dividing the view in 3 for large screens would also help a lot, like OP proposed.

---

Messing around with the CSS, I made sort of a Mockup of both features:
![image](https://user-images.githubusercontent.com/4715129/68409540-02978d80-0166-11ea-9fde-c08d4f82e228.png)

**Comment by rradar** [comment]
I like the new device page from home assistant very much as gives a good clutter view overview over all devices.

![image](https://user-images.githubusercontent.com/34582688/68413196-aba1b080-0185-11ea-8e8f-318045674824.png)
(slightly edited, battery percentages are not reported if I'm right)

This with the esphome actions added would serve nicely in my view. And some more custom columns would the hit :medal_sports:

**Comment by Fusseldieb** [comment]
> This with the esphome actions added would serve nicely in my view. And some more custom columns would the hit 🏅

Agreed! That searchbar on top and ability to sort by Area is perfect.

**Comment by OttoWinter** [comment]
I'm ok with the general idea here - though I would prefer if someone with actual knowledge in HTML/CSS works on this, I know it would just take me ages.

I've got some thoughts on the things any design should include:

 - The advanced feature should not get into the way of a new user starting out. For example with folders, by default the user should not be concerned with it. Only if they manually go and create those.
 - Same goes for interface. A list like @rradar posted might be nice if you've got a lot of devices, but the big fat buttons in the current dashboard are better for most users.
 - Ideally, the new design would also follow the material design guidelines. I believe there are guidelines for cards on wide screens.

I would also recommend starting this out small - adding folders would be a lot of work. Simple tweaks like multiple columns would get done easier.

**Comment by holdestmade** [comment]
@OttoWinter, agreed, I would prefer just more of the existing cards for ease of use

**Comment by Misiu** [comment]
@Fusseldieb I think that if you will rename `SHOW LOGS` to `LOGS` then the options would will into one row (now `VALIDATE` is on new line). This would make the view even more compact.

@OttoWinter do You agree on 1 to max 3 columns layout? According to [spec](https://material.io/design/layout/responsive-layout-grid.html#breakpoints) there should be max 12 columns (4 columns per card), so this gives one to 3 cards per row.
I'll set up a dev instance and try to tweak this.

@Fusseldieb do You have your CSS somewhere?

**Comment by Fusseldieb** [comment]
> @Fusseldieb do You have your CSS somewhere?

I just made a quick mockup messing around with inspect element. I actually understand CSS and made some neat things in the past (and still do), but I don't have a lot of time for those things, so it'll better for someone to make this :)

I also personally liked @rradar 's design better.

**Comment by Misiu** [comment]
@Fusseldieb at first I thought the same.
But with the grid, you lose quick action buttons (UPLOAD, EDIT, etc). You can add them as 4 columns, but that won't look nice, you can add a quick action button (3 dots) that will show those options after you click on that button, but I don't think it will work nicely (you must click on dots to get those options - one extra click).
What columns should the grid have?
-Name
-Status (online, offline)
-Quick actions (upload, edit, show log, validate)

**Comment by randybb** [comment]
+ have a option to update all online, or all production devices based on tag.

**Comment by Misiu** [comment]
@randybb that's a global option (and I think it would be very useful), but I was thinking about grid option - per device option and info

**Comment by holdestmade** [comment]
Any progress on this ?
Thanks

**Comment by jonathanadams** [comment]
I am currently working on some dashboard improvements which I hope to submit a pull request for in the next week or so.
