### ISSUE TITLE
Add Support for Gree AC / Heat Pump

### ISSUE THREAD

**Issue by ddf89** [esphome/feature-requests#478]
**Describe the problem you have/What new integration you would like**

First and foremost, thanks for the wonderful system that esphome is. I would like to see support for the Gree AC protocol, similar to what is implemented in IRremoteESP8266 (https://github.com/crankyoldgit/IRremoteESP8266/blob/master/src/ir_Gree.cpp). I have used IRremoteESP8266 extensively in my projects and it works perfectly fine for Gree.

**Please describe your use case for this integration and alternatives you've tried:**
Direct implementation of the Gree protocol provides the same benefits that other direct implementations provide, no messing around with codes for users.

**Additional context**
I'm available to test if need be.

**Comment by Gooman-rus** [comment]
Hello.
Is there a way to use this library (cpp) in esphome now?

**Comment by 11protos11** [comment]
I tried, but it didn't work.  Probably did something wrong.

**Comment by vevsvevs** [comment]
I'm really interested in this too. Gree is the biggest Chinese OEM AC manufacturer with a very competitive quality/price, so their devices meet pretty commonly.

**Comment by pcktdmp** [comment]
I got a working custom climate integration for Gree based on `IRremoteESP8266`, I'm in the process of prepping a PR to make it part of esphome.

**Comment by younglip** [comment]
that's very important case for me. Please, add gree support

**Comment by vevsvevs** [comment]
@pcktdmp thank you very much! Integration works perfectly, my AC is voice-controllable again 👍 It would be nice to have swing mode/fan speed as parameters, not as constants. And also receiver support (for the remote feedback) would be really nice too, but I think it relies on the climate_ir implementation?

**Comment by pcktdmp** [comment]
@vevsvevs you are welcome, before creating a PR I'm aiming to use `climate_ir` instead of `climate` and more config options along the way doing that.

**Comment by GT32b** [comment]
Thanks @pcktdmp, was waiting for this for a long while now. Any ETA integrate to main dev?

**Comment by pcktdmp** [comment]
> Thanks @pcktdmp, was waiting for this for a long while now. Any ETA integrate to main dev?

I hope during the holidays. Unfortunately.

**Comment by nithino** [comment]
How can i add gree custom component from the above repository to esphome in homeassistant? Please help.

**Comment by martimarkov** [comment]
Hey, @pcktdmp are you working on this still or not?

**Comment by Hagakurje** [comment]
There is another way to use IRremoteESP8266 with ESPHome:

1. Create file "gree_ir.h" in "config\esphome\gree", where "config" is HA configuration folder
gree_ir.h
```
#include "esphome.h"
#include "IRremoteESP8266.h"
#include "IRsend.h"
#include "ir_Gree.h"

const uint16_t kIrLed = 14; // transmitter GPIO pin to use
IRGreeAC ac(kIrLed);

class GreeAC : public Component, public Climate
{
public:
  void setup() override
  {
    ac.begin();
    ac.on();

    ac.setMode(kGreeAuto);
    ac.setTemp(22);
    ac.setFan(kGreeFanAuto);
    ac.setSwingVertical(true, kGreeSwingAuto);
    ac.setLight(false);
  }

  climate::ClimateTraits traits()
  {
    auto traits = climate::ClimateTraits();

    traits.set_supports_current_temperature(true);
    traits.set_supports_two_point_target_temperature(false);
    traits.set_visual_min_temperature(16);
    traits.set_visual_max_temperature(30);
    traits.set_visual_temperature_step(1.f);

    traits.set_supports_auto_mode(true);
    traits.set_supports_cool_mode(true);
    traits.set_supports_heat_mode(true);
    traits.set_supports_fan_only_mode(false);
    traits.set_supports_dry_mode(false);

    traits.set_supports_fan_mode_auto(true);
    traits.set_supports_fan_mode_low(true);
    traits.set_supports_fan_mode_medium(true);
    traits.set_supports_fan_mode_high(true);

    traits.set_supports_swing_mode_off(true);
    traits.set_supports_swing_mode_both(false);
    traits.set_supports_swing_mode_vertical(true);
    traits.set_supports_swing_mode_horizontal(false);

    return traits;
  }

  void control(const ClimateCall &call) override
  {
    if (call.get_mode().has_value())
    {
      ClimateMode climateMode = *call.get_mode();
      switch (climateMode)
      {
      case CLIMATE_MODE_HEAT:
        ac.setMode(kGreeHeat);
        ac.setLight(false);
        ac.on();
        break;
      case CLIMATE_MODE_COOL:
        ac.setMode(kGreeCool);
        ac.setLight(false);
        ac.on();
        break;
      case CLIMATE_MODE_AUTO:
        ac.setMode(kGreeAuto);
        ac.setLight(false);
        ac.on();
        break;
      case CLIMATE_MODE_OFF:
        ac.setLight(true);
        ac.off();
        break;
      }

      this->mode = climateMode;
      this->publish_state();
    }

    if (call.get_target_temperature().has_value())
    {
      float temp = *call.get_target_temperature();
      ac.setTemp(temp);

      this->target_temperature = temp;
      this->publish_state();
    }

    if (call.get_fan_mode().has_value())
    {
      ClimateFanMode fanMode = *call.get_fan_mode();
      switch (fanMode)
      {
      case CLIMATE_FAN_AUTO:
        ac.setFan(kGreeFanAuto);
        break;
      case CLIMATE_FAN_LOW:
        ac.setFan(kGreeFanMin);
        break;
      case CLIMATE_FAN_MEDIUM:
        ac.setFan(kGreeFanMed);
        break;
      case CLIMATE_FAN_HIGH:
        ac.setFan(kGreeFanMax);
        break;
      }

      this->fan_mode = fanMode;
      this->publish_state();
    }

    if (call.get_swing_mode().has_value())
    {
      ClimateSwingMode swingMode = *call.get_swing_mode();
      switch (swingMode)
      {
      case CLIMATE_SWING_OFF:
        ac.setSwingVertical(false, kGreeSwingMiddle);
        break;
      case CLIMATE_SWING_VERTICAL:
        ac.setSwingVertical(true, kGreeSwingAuto);
        break;
      }

      this->swing_mode = swingMode;
      this->publish_state();
    }

    ac.send();
    delay(200);
  }
};
```

**Comment by Hagakurje** [comment]
There is another way to use IRremoteESP8266 with ESPHome:

1. Create file "gree_ir.h" in folder "config\esphome\gree\", where "config" is HA configuration folder 
gree_ir.h:
```
#include "esphome.h"
#include "IRremoteESP8266.h"
#include "IRsend.h"
#include "ir_Gree.h"

const uint16_t kIrLed = 14; // transmitter GPIO pin to use
IRGreeAC ac(kIrLed);

class GreeAC : public Component, public Climate
{
public:
  void setup() override
  {
    ac.begin();
    ac.on();

    ac.setMode(kGreeAuto);
    ac.setTemp(22);
    ac.setFan(kGreeFanAuto);
    ac.setSwingVertical(true, kGreeSwingAuto);
  }

  climate::ClimateTraits traits()
  {
    auto traits = climate::ClimateTraits();

    traits.set_supports_current_temperature(true);
    traits.set_supports_two_point_target_temperature(false);
    traits.set_visual_min_temperature(16);
    traits.set_visual_max_temperature(30);
    traits.set_visual_temperature_step(1.f);

    traits.set_supports_auto_mode(true);
    traits.set_supports_cool_mode(true);
    traits.set_supports_heat_mode(true);
    traits.set_supports_fan_only_mode(false);
    traits.set_supports_dry_mode(false);

    traits.set_supports_fan_mode_auto(true);
    traits.set_supports_fan_mode_low(true);
    traits.set_supports_fan_mode_medium(true);
    traits.set_supports_fan_mode_high(true);

    traits.set_supports_swing_mode_off(true);
    traits.set_supports_swing_mode_both(false);
    traits.set_supports_swing_mode_vertical(true);
    traits.set_supports_swing_mode_horizontal(false);

    return traits;
  }

  void control(const ClimateCall &call) override
  {
    if (call.get_mode().has_value())
    {
      ClimateMode climateMode = *call.get_mode();
      switch (climateMode)
      {
      case CLIMATE_MODE_HEAT:
        ac.setMode(kGreeHeat);
        ac.on();
        break;
      case CLIMATE_MODE_COOL:
        ac.setMode(kGreeCool);
        ac.on();
        break;
      case CLIMATE_MODE_AUTO:
        ac.setMode(kGreeAuto);
        ac.on();
        break;
      case CLIMATE_MODE_OFF:
        ac.off();
        break;
      }

      this->mode = climateMode;
      this->publish_state();
    }

    if (call.get_target_temperature().has_value())
    {
      float temp = *call.get_target_temperature();
      ac.setTemp(temp);

      this->target_temperature = temp;
      this->publish_state();
    }

    if (call.get_fan_mode().has_value())
    {
      ClimateFanMode fanMode = *call.get_fan_mode();
      switch (fanMode)
      {
      case CLIMATE_FAN_AUTO:
        ac.setFan(kGreeFanAuto);
        break;
      case CLIMATE_FAN_LOW:
        ac.setFan(kGreeFanMin);
        break;
      case CLIMATE_FAN_MEDIUM:
        ac.setFan(kGreeFanMed);
        break;
      case CLIMATE_FAN_HIGH:
        ac.setFan(kGreeFanMax);
        break;
      }

      this->fan_mode = fanMode;
      this->publish_state();
    }

    if (call.get_swing_mode().has_value())
    {
      ClimateSwingMode swingMode = *call.get_swing_mode();
      switch (swingMode)
      {
      case CLIMATE_SWING_OFF:
        ac.setSwingVertical(false, kGreeSwingMiddle);
        break;
      case CLIMATE_SWING_VERTICAL:
        ac.setSwingVertical(true, kGreeSwingAuto);
        break;
      }

      this->swing_mode = swingMode;
      this->publish_state();
    }

    ac.send();
    delay(200);
  }
};
```
2. Change transmitter pin in row "const uint16_t kIrLed = 14; // transmitter GPIO pin to use"
3. Modify yaml file:
```
...

esphome:
  name: ***
  platform: ***
  board: ***
  includes: 
    - gree/gree_ir.h
  libraries:
    - IRremoteESP8266

...
    
climate:
- platform: custom
  lambda: |-
    auto my_ac = new GreeAC();
    App.register_component(my_ac);
    return {my_ac};

  climates:
    - name: "My AC"
```
4. Enjoy :) 
![Screenshot 2021-01-04 143223](https://user-images.githubusercontent.com/12123779/103535699-df678b80-4e99-11eb-9f6d-ffe1b395cdf3.png)

**Comment by pcktdmp** [comment]
> Hey, @pcktdmp are you working on this still or not?

Unfortunately not, @Hagakurje's solution would be the best option until I or someone else finds some time and priority to pick this up again.

**Comment by Hagakurje** [comment]
updated version: https://github.com/Hagakurje/ESPHome_Gree_AC

**Comment by Luth1ng** [comment]
Is anyone still working on this ?
@Hagakurje's solution is the better way to go at the moment, but a little tricky for new users.

I can be available for testing if needed.

**Comment by yurhett** [comment]
I am trying to make changes to @Hagakurje's work to make it work better. I can be available for testing if needed.
If there are any ideas for native ESPHome support, I can assist in implementing them.

**Comment by Hagakurje** [comment]
How about [arduino-heatpumpir](https://esphome.io/components/climate/climate_ir.html#arduino-heatpumpir) with gree or greeyac  protocol?
Does it work?

**Comment by soloam** [comment]
This is a little forgotten on time! Hope we can bring it back! This is a very popular brand, it would be nice to have a native integration with ir transmitter and ir recover!

**Comment by ayubn** [comment]
> There is another way to use IRremoteESP8266 with ESPHome:
> 
> 1. Create file "gree_ir.h" in folder "config\esphome\gree", where "config" is HA configuration folder
>    gree_ir.h:
> 
> ```
> #include "esphome.h"
> #include "IRremoteESP8266.h"
> #include "IRsend.h"
> #include "ir_Gree.h"
> 
> const uint16_t kIrLed = 14; // transmitter GPIO pin to use
> IRGreeAC ac(kIrLed);
> 
> class GreeAC : public Component, public Climate
> {
> public:
>   void setup() override
>   {
>     ac.begin();
>     ac.on();
> 
>     ac.setMode(kGreeAuto);
>     ac.setTemp(22);
>     ac.setFan(kGreeFanAuto);
>     ac.setSwingVertical(true, kGreeSwingAuto);
>   }
> 
>   climate::ClimateTraits traits()
>   {
>     auto traits = climate::ClimateTraits();
> 
>     traits.set_supports_current_temperature(true);
>     traits.set_supports_two_point_target_temperature(false);
>     traits.set_visual_min_temperature(16);
>     traits.set_visual_max_temperature(30);
>     traits.set_visual_temperature_step(1.f);
> 
>     traits.set_supports_auto_mode(true);
>     traits.set_supports_cool_mode(true);
>     traits.set_supports_heat_mode(true);
>     traits.set_supports_fan_only_mode(false);
>     traits.set_supports_dry_mode(false);
> 
>     traits.set_supports_fan_mode_auto(true);
>     traits.set_supports_fan_mode_low(true);
>     traits.set_supports_fan_mode_medium(true);
>     traits.set_supports_fan_mode_high(true);
> 
>     traits.set_supports_swing_mode_off(true);
>     traits.set_supports_swing_mode_both(false);
>     traits.set_supports_swing_mode_vertical(true);
>     traits.set_supports_swing_mode_horizontal(false);
> 
>     return traits;
>   }
> 
>   void control(const ClimateCall &call) override
>   {
>     if (call.get_mode().has_value())
>     {
>       ClimateMode climateMode = *call.get_mode();
>       switch (climateMode)
>       {
>       case CLIMATE_MODE_HEAT:
>         ac.setMode(kGreeHeat);
>         ac.on();
>         break;
>       case CLIMATE_MODE_COOL:
>         ac.setMode(kGreeCool);
>         ac.on();
>         break;
>       case CLIMATE_MODE_AUTO:
>         ac.setMode(kGreeAuto);
>         ac.on();
>         break;
>       case CLIMATE_MODE_OFF:
>         ac.off();
>         break;
>       }
> 
>       this->mode = climateMode;
>       this->publish_state();
>     }
> 
>     if (call.get_target_temperature().has_value())
>     {
>       float temp = *call.get_target_temperature();
>       ac.setTemp(temp);
> 
>       this->target_temperature = temp;
>       this->publish_state();
>     }
> 
>     if (call.get_fan_mode().has_value())
>     {
>       ClimateFanMode fanMode = *call.get_fan_mode();
>       switch (fanMode)
>       {
>       case CLIMATE_FAN_AUTO:
>         ac.setFan(kGreeFanAuto);
>         break;
>       case CLIMATE_FAN_LOW:
>         ac.setFan(kGreeFanMin);
>         break;
>       case CLIMATE_FAN_MEDIUM:
>         ac.setFan(kGreeFanMed);
>         break;
>       case CLIMATE_FAN_HIGH:
>         ac.setFan(kGreeFanMax);
>         break;
>       }
> 
>       this->fan_mode = fanMode;
>       this->publish_state();
>     }
> 
>     if (call.get_swing_mode().has_value())
>     {
>       ClimateSwingMode swingMode = *call.get_swing_mode();
>       switch (swingMode)
>       {
>       case CLIMATE_SWING_OFF:
>         ac.setSwingVertical(false, kGreeSwingMiddle);
>         break;
>       case CLIMATE_SWING_VERTICAL:
>         ac.setSwingVertical(true, kGreeSwingAuto);
>         break;
>       }
> 
>       this->swing_mode = swingMode;
>       this->publish_state();
>     }
> 
>     ac.send();
>     delay(200);
>   }
> };
> ```
> 
> 2. Change transmitter pin in row "const uint16_t kIrLed = 14; // transmitter GPIO pin to use"
> 3. Modify yaml file:
> 
> ```
> ...
> 
> esphome:
>   name: ***
>   platform: ***
>   board: ***
>   includes: 
>     - gree/gree_ir.h
>   libraries:
>     - IRremoteESP8266
> 
> ...
>     
> climate:
> - platform: custom
>   lambda: |-
>     auto my_ac = new GreeAC();
>     App.register_component(my_ac);
>     return {my_ac};
> 
>   climates:
>     - name: "My AC"
> ```
> 
> 4. Enjoy :)
>    ![Screenshot 2021-01-04 143223](https://user-images.githubusercontent.com/12123779/103535699-df678b80-4e99-11eb-9f6d-ffe1b395cdf3.png)

thanks its working nice... i want to add default temperature settings how to do it
