### ISSUE TITLE
Logger Text Sensor

### ISSUE THREAD

**Issue by rradar** [esphome/feature-requests#483]
**Describe the problem you have/What new integration you would like**

A Text Sensor which updates with the logger. Maybe limited to errors/warnings to don't 'spam' the sensor.

**Please describe your use case for this integration and alternatives you've tried:**

Sometimes I see blue led's (set up as status led in esphome) flashing on some devices. It's often not clear for me what caused this because it's not logged.

A text sensor which stores the last error or warning messages with their time stamps would be the thing. So it would be also possible to travel back in time and see since when a certain error occurred for example. Perfect for debugging!

**Additional context**

**Comment by OttoWinter** [comment]
Already implemented via https://github.com/esphome/esphome/pull/729
