### ISSUE TITLE
Support for QMC5883 compass module

### ISSUE THREAD

**Issue by pilotak** [esphome/feature-requests#486]
**Describe the problem you have/What new integration you would like**

Since Ebay/Ali sending  QMC5883 but advertising it as  HMC5883 it would be nice to support these modules too as library for HMC doesn't work with QMC

**Please describe your use case for this integration and alternatives you've tried:**

I need to build ESP32-CAM with compass support, as this will be mounted on rotor antenna so i know which direction is heading to.

**Additional context**

working library https://github.com/mprograms/QMC5883LCompass

**Comment by OttoWinter** [comment]
Related https://github.com/esphome/esphome/pull/671
