### ISSUE TITLE
Support AHT10 (I2C)

### ISSUE THREAD

**Issue by Joshfindit** [esphome/feature-requests#491]
**Describe the problem you have/What new integration you would like**

Be able to read the AHT10

**Please describe your use case for this integration and alternatives you've tried:**

Debug logs show the device
```
Nov 18 12:48:41 d3miniv3breadboarder/debug [I][i2c:033]: Scanning i2c bus for active devices...
Nov 18 12:48:41 d3miniv3breadboarder/debug [I][i2c:040]: Found i2c device at address 0x38
```
I tried researching the documentation/feature requests, but could not find anything

**Additional context**

Arduino code: https://github.com/Thinary/AHT10/blob/master/src/Thinary_AHT10.cpp

**Comment by gmasse** [comment]
Hi @Joshfindit,
You can try my porting: https://github.com/gmasse/esphome/tree/aht10-temperature-humidity/esphome/components/aht10
I have an issue to get Humidity (always returning 0). I suspect the hardware is buggy.
Waiting for new components to confirm and create the PR.

**Comment by muxa** [comment]
I see the PR for this feature is merged, but this ticket is still open and `aht10` platform is not yet supported in lasted esphome. When is this expected to be released?

**Comment by AndroVet** [comment]
+1

**Comment by muxa** [comment]
@AndroVet it's in 1.15 release (currently in beta): https://github.com/esphome/esphome/releases

**Comment by AndroVet** [comment]
Could you show me please what should I do with the zip-archive I downloaded?

**Comment by AndroVet** [comment]
Could you show me please what should I do with the zip-archive I downloaded?

**Comment by AndroVet** [comment]
Help please, otherwise I really don't want to spend a more expensive BME680 sensor on air conditioning
![IMG_20200821_101558](https://user-images.githubusercontent.com/60533499/90838594-999da100-e398-11ea-83e3-ea9c61f20dda.jpg)

**Comment by AndroVet** [comment]
> @AndroVet it's in 1.15 release (currently in beta): https://github.com/esphome/esphome/releases

Could you show me please what should I do with the zip-archive I downloaded?

**Comment by sumirati** [comment]
This feature request can be closed.
