### ISSUE TITLE
Add position action and lambda to template cover

### ISSUE THREAD

**Issue by KristopherMackowiak** [esphome/feature-requests#498]
**Describe the problem you have/What new integration you would like**

I can't trigger action in ESPHome after set position in Home Assistant

**Please describe your use case for this integration and alternatives you've tried:**

...

**Additional context**

I prepared code in PK #877. I tested it on my blinds and working ok.

**Comment by glmnet** [comment]
Closed via https://github.com/esphome/esphome/pull/877
