### ISSUE TITLE
TTGO-T-Display board definition

### ISSUE THREAD

**Issue by KamilLenica** [esphome/feature-requests#499]
**Describe the problem you have/What new integration you would like**

Add definition for TTGO-T-Display ESP32 board

**Please describe your use case for this integration and alternatives you've tried:**

Please add board definition to use with wizard

**Additional context**

Board info https://github.com/Xinyuan-LilyGO/TTGO-T-Display

**Comment by OttoWinter** [comment]
For that device, just select the "generic" option as described in the setup wizard.

The board definition is not needed for this board - it has no pin aliases and has a standard WROOM-32 module.

As for the display, that is another thing - but for that create a separate feature request.

**Comment by KamilLenica** [comment]
I will try to add support myself and contribute to the project
