### ISSUE TITLE
HC-12 RF Transceiver

### ISSUE THREAD

**Issue by MattXcz** [esphome/feature-requests#505]
**Describe the problem you have/What new integration you would like**

Please add support for HC-12 module (long RF reciever / transmitter )
It use VCC, GND, RX, TX

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by OttoWinter** [comment]
Supporting these generic communication channel devices is pretty hard, so only a few of them can be supported.

The LoRA modules are very similar (and much more commonly used with ESPs), so priority is on those. See also https://github.com/esphome/feature-requests/issues/124
