### ISSUE TITLE
Allow same trigger with different parameters multiple times

### ISSUE THREAD

**Issue by dgtal1** [esphome/feature-requests#510]
**Describe the problem you have/What new integration you would like**

Allow the same trigger e.g. `on_click` to occur multiple times for a component, but with different parameters.

**Please describe your use case for this integration and alternatives you've tried:**

I'm trying to have two different actions for a `binary_switch` depending on how long a click lasts. 
E.g. 
1. normal, short click with default values -> turn on a switch (turn on a relay)
2. long click, min 5 seconds -> turn on another switch (restart)

Right now this is not possible, and I couldn't find a workaround. I've tried `on_press` with a `for` condition, but its action is never triggered when there is a `on_click` for the same `binary_switch`

**Additional context**

**Comment by brandond** [comment]
You want `on_multi_click`: https://esphome.io/components/binary_sensor/index.html#on-multi-click

You can specify as many different timing combinations as you want.

**Comment by brandond** [comment]
See an example here:
https://github.com/esphome/feature-requests/issues/472#issuecomment-559797780
