### ISSUE TITLE
TFT-LCD ST7789V of ESP32 TTGO

### ISSUE THREAD

**Issue by musk95** [esphome/feature-requests#522]
**Describe the problem you have/What new integration you would like**

I'd like to ask to add TFT-LCD ST7789V of ESP32 TTGO.

**Please describe your use case for this integration and alternatives you've tried:**

This product is,
https://sites.google.com/site/jmaathuis/arduino/lilygo-ttgo-t-display-esp32

**Additional context**

There is for Arduino, but not exist for ESPHome.
so I create component for ESPHome and code is on https://github.com/musk95/esphome
Please include this at next release if it is possible.

Thank you.

**Comment by brandond** [comment]
Can you put in a pull request?

**Comment by musk95** [comment]
I've put in a pull request of the dev.
Thanks.

**Comment by minsuke** [comment]
thank you musk95 : )
