### ISSUE TITLE
Add invert option for remote_transmitter component

### ISSUE THREAD

**Issue by martijnvdwoude** [esphome/feature-requests#525]
**Describe the problem you have/What new integration you would like**
`remote_transmitter` component is missing an `invert` option for output.

**Please describe your use case for this integration and alternatives you've tried:**
My use case required an inverted output. I was trying to replace a IR sensor board with an ESP8266 that would output the same digital output as the IR sensor. I'm not using the `remote_transmitter` component with an IR LED, but rather have it connected directly to my device, in my case an older Optoma projector.

**Additional context**
I managed to get my implementation to work by modifying the `RemoteTransmitterComponent` source and inverting all the values in `digital_write()` in there. The component however uses the pins directly instead of using an output component.

**Comment by glmnet** [comment]
I don't get it, it's supposed to work.
did you try this?
````yaml

remote_transmitter:
  carrier_duty_percent: 50%
  pin:
    number: D6
    inverted: True
````
