### ISSUE TITLE
Silent option for Logger

### ISSUE THREAD

**Issue by CyanoFresh** [esphome/feature-requests#537]
**Describe the problem you have/What new integration you would like**

I want an option for disabling logging for specific sensor. 

**Please describe your use case for this integration and alternatives you've tried:**

For example, `adc` sensor needs to be updated every 50ms and floods uart and logs with its values. 
I've added `delta` filter but logging is still here

**Additional context**

**Comment by glmnet** [comment]
This is already supported, you need to increase the level filter for the sensor, see [logger](https://esphome.io/components/logger.html#manual-tag-specific-log-levels)

you'll have something like
````yaml
logger:
  level: VERBOSE
  logs:
    adc: NONE
````
