### ISSUE TITLE
ESP32 camera Support

### ISSUE THREAD

**Issue by erazor666** [esphome/feature-requests#55]
Is there any planned implentation of these devices?
 Toying with the idea of a esphome powered doorbell among other things. Basicually a node with a switch and a camera and then some magic to notify users, maybe with presense detection via HA to notify users that are present.

**Comment by bbbenji** [comment]
Has been mentioned here: https://esphome.io/changelog/v1.11.0.html#faster-release-cycle

**Comment by OttoWinter** [comment]
Added in 1.12
