### ISSUE TITLE
AC Voltage readings with ESP8266 and zmpt101b

### ISSUE THREAD

**Issue by herreran24** [esphome/feature-requests#558]
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by herreran24** [comment]
I'm trying with the https://surtrtech.com/2019/01/21/easy-measure-of-ac-voltage-using-arduino-and-zmpt101b/ that was made for Arduino, but wasn't able to get to work on the ESP. Regards

**Comment by olddawgpowers** [comment]
Did you ever find a solution?

**Comment by herreran24** [comment]
No, I did not. I could make it to work in Arduino Nano perfectly then send the readings via serial to the ESP8266. If you need I can send you the code.

**Comment by olddawgpowers** [comment]
Thanks for the reply.  I am just looking to sense AC voltage on a rain sensor, I don't really need an accurate measurement.  Hoping maybe something like the zmpt101b would work.

**Comment by herreran24** [comment]
The zmpt101b does work, I just wasn't able to make it work on the ESP8266, but it does work on Arduino Nano and it is not as accurate as a digital tester, but it works. A work around is what I did, get a Nano and send the data from it to the ESP, only if you need to send to internet, otherwise, you don't need the ESP, with the nano and a OLED display works perfectly, for example I'm using a SSD1306.

**Comment by OttoWinter** [comment]
This bug tracker is for bugs in the ESPHome codebase, not for troubleshooting how to add a certain hardware device.

**Comment by olddawgpowers** [comment]
Sorry Otto.  I didn’t realize that.

 

John
