### ISSUE TITLE
Use LED strips in a matrix as display

### ISSUE THREAD

**Issue by escoand** [esphome/feature-requests#570]
**Describe the problem you have/What new integration you would like**
Currently it's not possible to use LED strips organized in a matrix with the ESPHome DisplayBuffer API.

**Please describe your use case for this integration and alternatives you've tried:**
This custom component creates an additional DisplayBuffer to circumvent this problem: https://github.com/escoand/matrix_led_display
Hopefully this will help other persons as well until there is a upstream solution for this.

**Additional context**

**Comment by brandond** [comment]
Oh hey, this is the next place I was going to go with my light grouping component: https://github.com/esphome/feature-requests/issues/554#issuecomment-574045082

My first task was to get grouping working so I can have virtual pixels that are made up of multiple LEDs. Adding DisplayBuffer support was next but this is perfect!

**Comment by escoand** [comment]
The main problem I see is that ESPHome currently only allows bi-color (on / off) with the DisplayBuffers. My solution is working but upstream we should have a better way.

**Comment by brandond** [comment]
https://github.com/esphome/feature-requests/issues/51 also needs color display support.

**Comment by docteurzoidberg** [comment]
fasatled component can be enhanced with the fastledmatrix library and could became a display AND light component ?

**Comment by escoand** [comment]
Was added to 1.17.0: https://github.com/esphome/esphome/pull/1272
