### ISSUE TITLE
Interface Re-Vamp / Re-Size

### ISSUE THREAD

**Issue by 3ative** [esphome/feature-requests#571]
**Describe the problem you have/What new integration you would like**

🤞 **_Request to make the ESPHome list (Main page) more compact._** 

- Prefering to use ESPHome for my devices/gadgets, the list on the main page it getting quite long and it's starting to get tedious to scroll so much to find entries. 
- Keeping the same font size but resizing the logo and cell padding seems to be all that's needed. 

**Here's a mock-up... as a suggestion:**
![ESPHOME](https://user-images.githubusercontent.com/51385971/72662680-c2644f00-39e1-11ea-83cd-83796721c976.jpg)

Thanks. 👍

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by phixion** [comment]
Yeah good idea, thats a lot of wasted space,especially when you run it in a frame

**Comment by 3ative** [comment]
@phixion Oh, Selective firmware updates good idea. You should open your own feature request for that..

**Comment by rradar** [comment]
Duplicate in my opinion: https://github.com/esphome/feature-requests/issues/465

**Comment by 3ative** [comment]
Closing due to updated interface. Thanks Everyone, it's much better now. 👍
