### ISSUE TITLE
Option to disable publishing assumed_state to HA on time based cover

### ISSUE THREAD

**Issue by pszafer** [esphome/feature-requests#578]
**Describe the problem you have/What new integration you would like**
I'd like to ask if you could add option to disable publishind assumed_state in `Time-Based Cover` to Home Assistant.
It is pretty easy to see if button is locked in frontend and time-based cover sends `assumed_state: true` so both button up/down and stop are always active.

**Please describe your use case for this integration and alternatives you've tried:**
I guess I could try somehow create public template cover with internal template cover but want to ask here first if it wouldn't better to add such option.

**Additional context**
Thank you for Esphome!

**Comment by ricreis394** [comment]
I had like to see this implemented too.
I have a few covers, and the only way to do that is by creating a template cover off esphome.

**Comment by glmnet** [comment]
I don’t understand this request

**Comment by pszafer** [comment]
I'll try to explain.
in HA if device publish in `state_attributes` option `assumed_state: true` like this:
![image](https://user-images.githubusercontent.com/690510/73518735-6cd76b80-43ff-11ea-8aa9-1d65d964d541.png)

then both buttons on cover are always ACTIVE, even if esphome sends state `closed`.
![image](https://user-images.githubusercontent.com/690510/73518788-8678b300-43ff-11ea-9ad2-a6bca355254f.png)

If you avoid `assumed_state` in `state_attributes` then it looks like this (this is fork of tasmota based time cover):
![image](https://user-images.githubusercontent.com/690510/73518825-9db7a080-43ff-11ea-98b4-6ad2aa85114e.png)

I see that it is set here: https://github.com/esphome/esphome/blob/2d0d794a9dab9f538d65744fddbe6ecbee6c50e9/esphome/components/time_based/time_based_cover.cpp#L54

I imagine something config like this:
```
cover:
  - platform: time_based
    name: "Time-Based Cover"
    public_assumed_state: true/false
```

**Comment by glmnet** [comment]
Thanks, I got it now.

We can add `assumed_state` like in https://esphome.io/components/cover/template.html but instead of defaulting to `false` default it to `true`  otherwise this would be somewhat a breaking change.

IMO this makes more sense, for this cover, however in my particular use case of this integration I don't want this.

**Comment by pszafer** [comment]
I think option `assumed_state` would be awesome. It can be made default as `true`, so it wouldn't be breaking change.

**Comment by pszafer** [comment]
@glmnet just want to ask if you are gonna implement it?
Sorry for asking, just I'm not sure if those labels represents that feature request is accepted or no.

**Comment by glmnet** [comment]
I might implement it but I can't promise anything.
The good first issue means any developer is welcomed to implement this, and it is not a complicated stuff to do in the code base.
