### ISSUE TITLE
Allow regular ping or API query for off/online determination in dashboard

### ISSUE THREAD

**Issue by cpw** [esphome/feature-requests#581]
**Describe the problem you have/What new integration you would like**

I would like to actually see my devices' state in the dashboard. Currently, all of them show offline. Some are but many are not.
![image](https://user-images.githubusercontent.com/1217211/72932763-6295dd00-3d2e-11ea-9340-339d2fb69813.png)

**Please describe your use case for this integration and alternatives you've tried:**

This is because you use mDNS to query to the .local address of the devices. That does not exist in my setup - I have a full DNS with proper VLAN segmentation of IOT devices. mDNS is not an allowed protocol and I don't want to enable it.

**Additional context**

Every device in that list is able to be reached via API and DNS names. It seems silly to me that I am able to flash and view logs, yet have the dashboard report "offline" anyway.

I hope you'll consider this. I really don't want the giant insecure bus that is mDNS propagation just to  support a dot.

(Note that Home Assistant has sat happily pinging an offline device for months now. I don't mind. It's still better than mDNS).

Addendum: I think the author of #422 was requesting a similar feature in the dashboard (though it sounds like he was having other issues as well). I can see another similar request in https://github.com/esphome/issues/issues/729 as well. I'm clearly not the only one with a partitioned network setup, where this indicator won't work.

Thanks!

**Comment by brandond** [comment]
This is covered in the FAQ at https://esphome.io/guides/faq.html

>Alternatively, you can make esphome use ICMP pings to check the status of the device with the Hass.io Addon "status_use_ping": true, option or with docker -e >ESPHOME_DASHBOARD_USE_PING=true See also https://github.com/esphome/issues/issues/641#issuecomment-534156628.
