### ISSUE TITLE
SPI example (eg. mcp23S08)

### ISSUE THREAD

**Issue by makkie2002** [esphome/feature-requests#589]
**Describe the problem you have/What new integration you would like**
The documentation on the SPI bus implementation is rather limited (https://esphome.io/api/spi_8cpp.html). I want to implement a custom sensor that is based on the SPI interface but I find it hard to use the library as a non-specialist in C++. It would be nice to start from a (nearly) working example. Moreover, the example given here: https://esphome.io/custom/spi.html does not work. It seems there are two ways to implement SPI devices: one through the SPIdevice class and one through the regular Arduino library. Which one to use?

**Please describe your use case for this integration and alternatives you've tried:**
I am trying to implement the SPI-based IO expander mcp23S08. The same component with an I2C interface is already implemented in esphome (called MCP23008). So implementing this with SPI should not be too difficult as the same registers can be used. This mcp23s08 drives the Prodino boards (4 relays, 4 isolated inputs): https://kmpelectronics.eu/products/prodino-esp32-ethernet-v1/.

**Additional context**

**Comment by Sabesto** [comment]
Check out https://github.com/esphome/esphome/pull/1324

**Comment by nagyrobi** [comment]
Ask in the Discord channel concrete questions.
