### ISSUE TITLE
Is there a better way to set it up？

### ISSUE THREAD

**Issue by my12005** [esphome/feature-requests#595]
Charge the mobile phone for two hours, I just want to use the socket to manually control the charging, and turn off the charging in two hours。
Is there a better way to set it up？

binary_sensor:
  - platform: gpio
    name: "${device_name} key3"
    internal: true
    pin: GPIO14
    filters:
      - invert:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_click:
      - min_length: 50ms
        max_length: 400ms
        then:
          - switch.toggle: switch3
      - min_length: 500ms
        max_length: 2000ms
        then:
          - if:
                condition:
                    not:
                        script.is_running: script_delayer_s0
                then:
                  - script.execute: script_delayer_s0
    on_double_click:
      - min_length: 600ms
        max_length: 2500ms
        then:
          - script.execute: delayer_is_stopping 
          - delay: 2s        
          - script.stop: script_delayer_s0       
          - text_sensor.template.publish:
                id: delayer_status
                state: "USB定时已关闭"   
          - binary_sensor.template.publish:
                id: delayer0
                state: false  
script:
  - id: script_delayer_s0
    then:
      - switch.template.publish:
            id: delayer
            state: ON      
      - binary_sensor.template.publish:
            id: delayer0
            state: true   
      - script.execute: delayer_is_starting
      - delay: 2h
      - binary_sensor.template.publish:
            id: delayer0
            state: false  
      - switch.toggle: switch0 

**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by OttoWinter** [comment]
This is a feature request tracker, not for questions like this.

Also your post is quite short, if you want to add a solution you need to add more information (for example why the current config you have is not good enough?)
