### ISSUE TITLE
WPA3

### ISSUE THREAD

**Issue by GLEIPNIRS** [esphome/feature-requests#605]
When will WPA3 be added?

https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/wifi.html

**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by rradar** [comment]
@GLEIPNIRS when is your pull request ready?

**Comment by imShara** [comment]
no movings?

**Comment by glmnet** [comment]
Is WPA3 supported by ESP32?

**Comment by imShara** [comment]
> Is WPA3 supported by ESP32?

Yep

**Comment by henkiejan1** [comment]
Is there any idea when there is support for WPA3? Tasmota ESP32 releases are all with WPA3. :)

**Comment by jetflux** [comment]
Is this a work in progress or planned? support for WPA3 ? esp8266 ? esp32? (Y/n)?
