### ISSUE TITLE
Sensor Filter: Ignore the first values after ESP boot

### ISSUE THREAD

**Issue by thEngal** [esphome/feature-requests#607]
**Describe the problem you have/What new integration you would like**
I need a filter that ignores incoming values for a specified time after ESP bootup. 

**Please describe your use case for this integration and alternatives you've tried:**
I want to add a gas sensor (MQ-135) which needs a specified time to heat up. With this filter, the heat up values wouldn’t passed forward to Home Assistant.

**Additional context**
![D342BCE3-A7C3-4B7F-BD54-322D6F2A2B6B](https://user-images.githubusercontent.com/57642131/75078670-83f11100-5506-11ea-8ae1-3fa95723e5b5.jpeg)

**Comment by marklister** [comment]
One could probably accomplish this with a simple lambda filter looking at sensor.uptime...

**Comment by CarlosGS** [comment]
I am missing this too ;(

When using `sliding_window_moving_average` and `send_first_at` to guarantee a filtered value, the first odd reading (right after rebooting) introduces a distorted sample, which is annoying.
![image](https://user-images.githubusercontent.com/1636266/89721470-3007b500-d9de-11ea-8bc4-10a1123d84e2.png)

 A parameter like `n_skip: 1` or `n_ignore: 1` would be awesome IMHO.
