### ISSUE TITLE
Is there any timeline for the next version of ESPHome?

### ISSUE THREAD

**Issue by carlos-sarmiento** [esphome/feature-requests#618]
**Describe the problem you have/What new integration you would like**
I've been chomping at the bit waiting for the next release of ESPHome (or at least a beta) in order to use some of the new integrations. 

So I wanted to ask if there is any chance of a release soon.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by glmnet** [comment]
No, there is no release cycle like HA.
Expect one to two releases year may be, but nothing pre-scheduled.
If 1.4 stops working for some reason then 1.5 may come in.

Of course you can easily run the latest version which gives you all latest stuff, if there is something broken in dev it is easy to fix.
