### ISSUE TITLE
HeatIndex for DHT sensor

### ISSUE THREAD

**Issue by josh929800** [esphome/feature-requests#62]
DO NOT DELETE ANY TEXT from this template! Otherwise the issue may be closed without a comment.
-->

**Describe the problem you have/What new integration you would like**

The dht library includes the ability to calculate the heat index based on the temperature and humidity reading. It is a simple calculation and I would like to be able to have the sensor nodes to calculate it and send it to Home Assistant. 

Here is the code: 
HeatIndex = dht.computeHeatIndex(TEMPERATURE, HUMIDITY, false);

**Please describe your use case for this integration and alternatives you've tried:**

I have NodeRed calculate this but I would like to offload this calculation back onto the sensor nodes. 

**Additional context**

Thank you for all your work!

**Comment by OttoWinter** [comment]
That is exactly what a template sensor is for (see docs).

The dht integration will not support this itself because then that would need to be added to each sensor that supports temp+humidity. See bme680 environment example for inspiration
