### ISSUE TITLE
Monochromatic Light Fade Time

### ISSUE THREAD

**Issue by Simonv92** [esphome/feature-requests#623]
**Describe the problem you have/What new integration you would like**
<I'm running Monochromatic Light without problem. I only want to change the default transition time. I can't do that using the comand "transition_time" at the end of the light component. How can I do that? Thank you very much!>

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by glmnet** [comment]
Did you try `default_transition_length`?

**Comment by Simonv92** [comment]
Hi, thank for your reply.. I'm trying but I don't know how to add the default_transition_length to the config file.. it always report me an error...

**Comment by Simonv92** [comment]
Ok, now I understand, the correct syntax is default_transition_length: time s
Thank you again :)
