### ISSUE TITLE
BLE custom Sensor

### ISSUE THREAD

**Issue by Luisiado** [esphome/feature-requests#626]
**Describe the problem you have/What new integration you would like**

 I would like to create generic BLE sensors beeing recognised by esp_tracker. 

**Please describe your use case for this integration and alternatives you've tried:**

I have been looking for information two days and I understood the protocol. First of all I tried to emulate a xiaomy caracterised sensor but I dind´t get it work. Then I tried to create a custom component but I am quite stack with this issue because the component and the tracker are involved on it and its difficult to understand how to connect the parameters

**Additional context**

  Ideal application would be a sensor component which can automatically understand sensor lectures based in GATT, thus, a well defined sensor will automatically works with esphome and HA --
Meanwhile I am trying to develop a simple sensor here: https://community.home-assistant.io/t/how-to-create-a-custom-ble-sensor/174619/4  .

**Comment by nagyrobi** [comment]
See https://esphome.io/components/esp32_ble_tracker.html and https://esphome.io/components/sensor/xiaomi_ble.html
