### ISSUE TITLE
Support for Duco ventilation units via ModBus or generic Modbus devices

### ISSUE THREAD

**Issue by dewi-ny-je** [esphome/feature-requests#629]
I would like a component which can communicate with Duco IQ units via Modbus (and external UART-RS-2485dongle) to request periodically values from the selected registers.

The Duco units provide sensor readings and accept control values via Modbus. The registers and the options are clearly described in https://www.duco.eu/Wes/CDN/1/Attachments/L8000003-informatieblad-ModBus-(nl)_636319262041164478.pdf (Dutch language only).

I used the UART-RS485 converter "Grove - RS485" and a USB-serial dongle under Windows to check the proper working of the system and to collect logs. As software I used http://en.radzio.dxp.pl/modbus-master-simulator/ and https://www.se.com/us/en/faqs/FA180037/

I verified that the CRC corresponds to the Modbus specifications (CRC-16-IBM).

Some TX and RX packets:
in my case: device = 1

read input register 11, got result 10
**tx** 0x01 0x04 0x00 0x0B 0x00 0x01 0x40 0x08 
**rx**>0x01 0x04 0x02 0x00 0x0A 0x39 0x37

read input register 23, got result 468
**tx** 0x01 0x04 0x00 0x17 0x00 0x01 0x81 0xCE
**rx** 0x01 0x04 0x02 0x01 0xD4 0xB8 0xFF

read holding register 24, got result 50
**tx** 0x01 0x03 0x00 0x18 0x00 0x01 0x04 0x0D 
**rx** 0x01 0x03 0x02 0x00 0x32 0x39 0x91

The TX packets look like
_device command 16bit_register how_many_registers_to_read CRC_

The RX packets look like
_device command how_many_data_bytes 16bit_value CRC_

It follows closely the [specifications ](https://en.wikipedia.org/wiki/Modbus#Function_code_4_(read_input_registers)_and_function_code_3_(read_holding_registers)) of Modbus.

Requesting a non-existent register throws an error in the software I used, the resulting packet does not match the expected format.

**What I also did**: since I am not good at programming, especially in C++, I checked pzemac and pzem004t to see whether I could just modify them (script-kiddie style).

[pzemac ](https://github.com/esphome/esphome/blob/8ff742d9ab61f2c6cb04df09bc0e792d0ba478a6/esphome/components/pzemac/pzemac.cpp) expects packets of 20 bytes with all the data in one go so it's very different from the Duco, which must be queried register by register.

[pzem004t](https://github.com/esphome/esphome/blob/8ff742d9ab61f2c6cb04df09bc0e792d0ba478a6/esphome/components/pzem004t/pzem004t.cpp) expects packets of 7 bytes, which corresponds to Duco, but there is only 1 byte CRC at the end, which doesn't match. Also, the first byte appears to indicate the type of value, that's also different.

I'm not sure I can do much more unless I get a template which I can fill in with my registers.

The best would be to provide a new Modbus component, where the user can specify device number and registers for read-only sensors (input registers) and read-write settings (holding registers).

This would provide the best long-term solution, but since I cannot do it, would it be possible at least to provide a Duco component? For example, while it changes depending on each installation, in my case I only need input registers 10-12, 20-24 and holding registers 10, 15, 16, 19-21, 24-27, 29.

**Comment by nagyrobi** [comment]
For Modbus, Pzem, Pzemac check the docs
