### ISSUE TITLE
Can it support smartconfig, including (airkiss, smartconfig) and other protocols

### ISSUE THREAD

**Issue by yulei745** [esphome/feature-requests#630]
**Describe the problem you have/What new integration you would like**

China's WeChat supports one-click network configuration, using the smartconfig airkiss protocol. Now it seems that esphome does not support one-click network configuration, and can only be configured in the configuration file.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by nickrout** [comment]
What advantages do you see in this? Most of us don't mind typing in the details of our ssid.

**Comment by yulei745** [comment]
If you have used WeChat, you know why you should use this function. Http://wx.ai-thinker.com/api/old/wifi/config, this connection can be directly connected to esp8266 in WeChat. The connection The protocol used is smartconfig.

**Comment by NdK73** [comment]
It's really useful if you have to give away the devices, so that your wifi credentials are not hardcoded in 'em.

**Comment by brandond** [comment]
Otto has been pretty adamant in the past that configuration be done at build time. Maybe at some point in the future he'll change his mind, but at the moment it seems pretty unlikely.

**Comment by nagyrobi** [comment]
See https://esphome.io/components/esp32_improv.html
