### ISSUE TITLE
Add documentation for light.color_temperature

### ISSUE THREAD

**Issue by myoung34** [esphome/feature-requests#640]
**Describe the problem you have/What new integration you would like**

Add documentation for `color_temperature` on light component

**Please describe your use case for this integration and alternatives you've tried:**

I needed to set color temperature and it doesnt exist in docs. I find it on discord when i mentioned a log line when HASS updates it and causes `[21:32:09][D][light:278]:   Color Temperature: 313.0 mireds`

**Additional context**

**Comment by oxan** [comment]
This was fixed in esphome/esphome-docs#690.

**Comment by sumirati** [comment]
This can be closed
