### ISSUE TITLE
Continuous wifi scanning

### ISSUE THREAD

**Issue by melwinek** [esphome/feature-requests#647]
**Describe the problem you have/What new integration you would like**

When esp is connected to ap, and ap appears with stronger signal then it could switch.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by nagyrobi** [comment]
See https://github.com/esphome/esphome/pull/3600 and https://esphome.io/components/wifi.html#connecting-to-multiple-networks
