### ISSUE TITLE
ESP32 internal hall and temperature sensor

### ISSUE THREAD

**Issue by redskinhu** [esphome/feature-requests#654]
**Describe the problem you have/What new integration you would like**

Is it possible to create integration for the ESP32 internal hall and temperature sensor?

**Please describe your use case for this integration and alternatives you've tried:**

N/A

**Additional context**

I found sample here:
https://gist.github.com/xxlukas42/7e7e18604f61529b8398f7fcc5785251

Thanks

**Comment by glmnet** [comment]
[Hall sensor](https://esphome.io/components/sensor/esp32_hall.html)

Temperature might be of the chip which is useless for ambient temperature measuring.
Seems to be pretty useless for chip monitoring too https://www.esp32.com/viewtopic.php?t=4632

You can follow the guide on custom sensor and use and read the value quite easily.
