### ISSUE TITLE
Make a nonSmart Device -> Smart

### ISSUE THREAD

**Issue by Titanius** [esphome/feature-requests#666]
**Describe the problem you have/What new integration you would like**
Make a Baby Audio Player Smart

**Please describe your use case for this integration and alternatives you've tried:**
Hello, I would like to control a nonSmart-Device (Baby Musik Player) via HomeAssistant with an ESP. Tactile Push Button Switch are installed to operate the Baby Musik Player. I would like to use these contacts to control them with HomeAssistant (ESPHome). Means to operate it, two contacts are closed briefly for the corresponding function. example Play, Pause, Stop (Play pin to GND) (Stop Pin to GND)...
On the Baby Musik Player, are at the push of a button a bridge from GND to 6 different contacts.
And the On/Off Tactile Push Button Switch. The supply voltage of the Baby Musik Player is 5 V. What do I need to realize this?

**Additional context**

**Comment by glmnet** [comment]
This is a feature request forum for ESPHome

Seems like don’t know how to electronically mimic a touch sensor is touched. 
Post this question at the right place e.g some electronics forum. 
I believe I’ve read something about this on the esphome subforum of home assistant. They wanted to control a washing machine
