### ISSUE TITLE
Sort Nodes in Dashboard by Name and not Filename

### ISSUE THREAD

**Issue by holdestmade** [esphome/feature-requests#680]
**Describe the problem you have/What new integration you would like**
Sort Nodes in Dashboard option by name and not by filename

**Please describe your use case for this integration and alternatives you've tried:**
Sort Nodes in Dashboard by name and not by filename as my filenames are names of the plugs and the node names are the node use title.

**Additional context**

**Comment by jonathanadams** [comment]
See pull request esphome/esphome#1025.

I plan on implementing further updates and filtering/sorting will be one of them.

**Comment by rradar** [comment]
https://github.com/esphome/esphome/pull/1025 is **merged** 

:lock:
