### ISSUE TITLE
Deepsleep time templatable

### ISSUE THREAD

**Issue by mbt45** [esphome/feature-requests#683]
**Describe the problem you have/What new integration you would like**
Hello. 
Is it possible to make the deepsleep component templateable?
Being able to template the time of deepsleep would allow flexible deepsleep.

**Please describe your use case for this integration and alternatives you've tried:**
Exemples: 
- Long deepsleep at night and short deepsleep during the day. 
- It would also allow for longer than 3h deepsleep.
- changeable deepsleep times within hassio
- etc...

**Additional context**

**Comment by nuttytree** [comment]
@mbt45 would #339 meet your needs?
