### ISSUE TITLE
MAC address - tect sensor

### ISSUE THREAD

**Issue by theone11** [esphome/feature-requests#694]
**Describe the problem you have/What new integration you would like**
Ability to read the device MAC address
It can be part of the:
```
text_sensor:
  - platform: wifi_info
```

**Please describe your use case for this integration and alternatives you've tried:**
Sometime I need to know the MAC address of the device - for example, when assigning a static IP for the device via the router

**Additional context**
According to the "ESP8266WiFi.h" there exists a method "macAddress()" for reading the MAC address.

**Comment by sergeolkhovik** [comment]
Nice idea!
