### ISSUE TITLE
 ESP32 restore_from_flash

### ISSUE THREAD

**Issue by kostavelikov** [esphome/feature-requests#695]
**Describe the problem you have/What new integration you would like**
I noticed that there is "esp8266_restore_from_flash" option for the ESP8266. There is nothing like that for the ESP32. There should be, as the ESP32 has 512 bytes of usable space for that.

**Please describe your use case for this integration and alternatives you've tried:**
I need to use esp32 instead of esp8266 because it has more GPIOs and more computing power. Occasionally, I need to store some variable values on it.

**Additional context**
It can be done:
https://randomnerdtutorials.com/esp32-flash-memory/

**Comment by glmnet** [comment]
Esp32 is storing data on flash by default
