### ISSUE TITLE
Wiegand readers support

### ISSUE THREAD

**Issue by Gio-dot** [esphome/feature-requests#703]
**Describe the problem you have/What new integration you would like**

I think it will be very useful to add support for Wiegand reader devices. They can be used to integrate secure access control to Home assistant; to open a door or to enable/disable an alarm system using a simple rfid tag.
![image](https://user-images.githubusercontent.com/55327160/80354185-b0af0500-8876-11ea-801f-52103d28fc03.png)

**Please describe your use case for this integration and alternatives you've tried:**

I used these readers with arduino using monkeyboard library https://github.com/monkeyboard/Wiegand-Protocol-Library-for-Arduino. They works very well and i wish to have these readers working in ESPHome to use in Home assistant. There are a lot of very nice readers types on the market at very low prices (with/without keyboard, ip68, small, very small etc.). I also tried Esprfid (https://github.com/esprfid/esp-rfid) firmware but his development seems to be very slow and there are unresolved issues. 

![image](https://user-images.githubusercontent.com/55327160/80349891-37141880-8870-11ea-9f55-add703f879db.png)
![image](https://user-images.githubusercontent.com/55327160/80349948-4d21d900-8870-11ea-9ddd-a24846cec504.png)
![image](https://user-images.githubusercontent.com/55327160/80350006-632f9980-8870-11ea-89a1-9375f900f3bd.png)
![image](https://user-images.githubusercontent.com/55327160/80350117-89edd000-8870-11ea-9c4d-9ae41539d081.png)

**Additional context**

**Comment by randybb** [comment]
https://github.com/esphome/feature-requests/issues/211
