### ISSUE TITLE
Add assumed_state option for time-based cover

### ISSUE THREAD

**Issue by theone11** [esphome/feature-requests#707]
**Describe the problem you have/What new integration you would like**
When using a timed-based cover HA uses default assumed_state true and open/close button are always on. 

**Please describe your use case for this integration and alternatives you've tried:**
In order to change assumed_state to false I need to add customization in HA for every ESPHome time based cover component.
If in the future I change the cover name in ESPHome device I need to change the name also in HA customizations.

**Additional context**
Option assumed_state already exists for template cover. Can this be adopted for timed based cover?
https://esphome.io/components/cover/template.html

**Comment by glmnet** [comment]
https://github.com/esphome/esphome/pull/979
