### ISSUE TITLE
Support WX08ZM Xiaomi Mijia Mosquito Repellent Smart Version

### ISSUE THREAD

**Issue by pplucky** [esphome/feature-requests#716]
**Describe the problem you have/What new integration you would like**

Add support for the Xiaomi Mijia Mosquito Repellent Smart Version (Model WX08ZM)

**Please describe your use case for this integration and alternatives you've tried:**

Knowing the battery left, tablet remaining and working status would allow not to use Xiaomi Mi Home while being nearby.
Having it running in an ESP32 with BT would be great

**Additional context**

Some payload investigation already done [here](https://github.com/custom-components/sensor.mitemp_bt/issues/70#issuecomment-621681348).

Working prototype [here](https://github.com/ahpohl/esphome/tree/xiaomi_wx08zm).

**Comment by ahpohl** [comment]
@pplucky Thanks for opening a separate feature request for the WX08ZM. The state property really calls for a binary sensor to publish the on/off state properly. I need a good example how to publish some float values like battery and mosquito tablet alongside with the state. I think binary sensor has also support for float values, but I'll have to read up on this.  Meanwhile you can test the code as is in [ahpohl/esphome:xiaomi_complete](https://github.com/ahpohl/esphome/tree/xiaomi_complete)

**Comment by pplucky** [comment]
> The state property really calls for a binary sensor to publish the on/off state properly

Yep, that's true. Let me know if you need any testing there.

> Meanwhile you can test the code as is in [ahpohl/esphome:xiaomi_complete](https://github.com/ahpohl/esphome/tree/xiaomi_complete)

Looking good:
<img width="234" alt="image" src="https://user-images.githubusercontent.com/16407309/80926051-8b495c00-8d8c-11ea-8838-b52bacba10c2.png">
1 LYWSD03MMC,2 WX08ZM and 1 LYWSDCGQ

**Comment by ahpohl** [comment]
Great its still working! Yesterday I worked on the documentation and updated the pull requests. Its nearly finished.

**Comment by Magalex2x14** [comment]
HA has a separate sensor entity class for this. All I had to do was to convert the state of the sensor to a Boolean type. The device_class for this entity I select from the dictionary, based on the type of device. However, in the case of my custom component, there is one thin point related to the delay in changing the state of an entity in HA due to the periodic nature of the work of my platform (details [here](https://github.com/custom-components/sensor.mitemp_bt/issues/76), if interested).

**Comment by sermayoral** [comment]
I have a question. Can this device be turned on/off using BLE?

**Comment by Magalex2x14** [comment]
If this can be done from the MiHome application, then it can. The only thing that it is usually done through the BLE connection, which it is not implemented in ESPHome, if I remember correctly (correct me if I am mistaken).

**Comment by ahpohl** [comment]
@pplucky I updated the WX08ZM to a hybrid `sensor` and `binary_sensor` component. Now the power status in HA looks much nicer (on/off rather than 0/1) and the color of the symbol changes as well. You can pull the updated code from [ahpohl/eshome:xiaomi_wx08zm](https://github.com/ahpohl/esphome/tree/xiaomi_wx08zm) until is has been merged with ahpohl/eshome:dev.

In order to compile, you need to have both `sensor` and `binary_sensor` in your config:
```
sensor:

binary_sensor:
  - platform: xiaomi_wx08zm
    name: "WX08ZM Mosquito Repellent"
    mac_address: "74:a3:4a:b5:07:34"
    tablet:
      name: "WX08ZM Tablet Resource"
    battery_level:
      name: "WX08ZM Battery Level"
```

**Comment by pplucky** [comment]
> @pplucky I updated the WX08ZM to a hybrid `sensor` and `binary_sensor` component. Now the power status in HA looks much nicer (on/off rather than 0/1) and the color of the symbol changes as well. You can pull the updated code from [ahpohl/eshome:xiaomi_wx08zm](https://github.com/ahpohl/esphome/tree/xiaomi_wx08zm) until is has been merged with ahpohl/eshome:dev.
> 
> In order to compile, you need to have both `sensor` and `binary_sensor` in your config:
> 
> ```
> sensor:
> 
> binary_sensor:
>   - platform: xiaomi_wx08zm
>     name: "WX08ZM Mosquito Repellent"
>     mac_address: "74:a3:4a:b5:07:34"
>     tablet:
>       name: "WX08ZM Tablet Resource"
>     battery_level:
>       name: "WX08ZM Battery Level"
> ```

Looking good:
<img width="386" alt="image" src="https://user-images.githubusercontent.com/16407309/82071077-7abead00-96cd-11ea-80ad-68f7975e6fda.png">

As expected, the binary sensor doesn't update immediately once device is turned on/off, but it is quite acceptable I think.

**Comment by ahpohl** [comment]
@pplucky Thank you very much for testing the hybrid binary_sensor / sensor code.

I merged the changes with [ahpohl/eshome:dev](https://github.com/ahpohl/esphome) and updated the documentation. The preview is [here](https://deploy-preview-576--esphome.netlify.app/).

**Comment by pattyland** [comment]
I guess this issue can be closed: https://esphome.io/components/sensor/xiaomi_ble.html#wx08zm
