### ISSUE TITLE
Native support for buzzer

### ISSUE THREAD

**Issue by MarcoFranchi** [esphome/feature-requests#717]
**Describe the problem you have/What new integration you would like**
using PWR to manage Buzzer in not easy, new output component for passive Buzzer it could be a good idea

**Please describe your use case for this integration and alternatives you've tried:**
Support for passive buzzer with parameters like Duration, Tone and Volume
or better like this : https://www.letscontrolit.com/wiki/index.php?title=Buzzer_(RTTTL)

**Comment by randybb** [comment]
Something like this https://github.com/esphome/esphome/pull/817. And yes, it is not documented :D

**Comment by rradar** [comment]
@randybb if I'm right esphome/esphome#817 was never merged but the stale bot ate it :robot:

**Comment by randybb** [comment]
@OttoWinter Is alive and I believe he will fix it soon :)

**Comment by muxa** [comment]
@MarcoFranchi I believe the feature you were after was implemented. Please close this ticket.

**Comment by OttoWinter** [comment]
For reference: implemented here: https://esphome.io/components/rtttl.html
