### ISSUE TITLE
Set default colour or effect for neopixel light?

### ISSUE THREAD

**Issue by MrPasty** [esphome/feature-requests#74]
Is there any way we can specify what colour the light will default to when it is turned on? at the moment mine seems to turn on to a yellowish colour but i would like it to be a specific colour or effect?  I expect this can be done with an automation in HA but i would like to just be able to toggle the on off state and it be the correct colour.

Great project - keep up the good work.

Thanks

**Comment by markcarline** [comment]
If this one is delivered and it "remembers" the light / colour state then guess it would do, yes?....

https://github.com/esphome/feature-requests/issues/73

**Comment by OttoWinter** [comment]
If your colors are a bit off you can set a color correction (see docs).

Otherwise I would agree https://github.com/esphome/feature-requests/issues/73 is the real issue here. Else this should be solved in HA or esphome custom code.
