### ISSUE TITLE
Add icon field for binary sensor

### ISSUE THREAD

**Issue by SeByDocKy** [esphome/feature-requests#759]
**Describe the problem you have/What new integration you would like**

Simply, it would be great to add the _icon_ field  for binary sensor 

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by randybb** [comment]
It will not help have it just on ESPHome site. You have to ask HA first for such option - https://www.home-assistant.io/integrations/binary_sensor/
