### ISSUE TITLE
Add support for Adafruit SSD1331 OLED color display

### ISSUE THREAD

**Issue by hapklaar** [esphome/feature-requests#760]
**Describe the problem you have/What new integration you would like**
Please add support for the cheap Adafruit SSD1331 96x64 OLED color display.

**Please describe your use case for this integration and alternatives you've tried:**
Trying to create a CO2 sensor module that shows the current CO2 level and temperature from a MH-Z19B sensor on a display with a bargraph with color based on that level (400-600 green, 600-1000 yellow, 1000+ red). Have it working in txt only on a SSD1306, but now would like to move on to a color display in the same family and finish the module for use with Home Assistant.

**Additional context**
This is an SPI controlled display. Library is available from Adafruit (Adafruit_SSD1331.h)

**Comment by kbx81** [comment]
I've recently picked up a couple of their SSD1351 displays -- hopefully the SSD1331 is similar enough that it can be part of the same component. I may take a stab at implementing this in the not-too-distant future, unless someone beats me to it. 😄

**Comment by kbx81** [comment]
Unfortunately this display isn't quite as similar to the SSD1351 as it probably should be to roll into a single component. Next time I order some hardware, I just might add one of these to the order so I can properly build and test it.

**Comment by hapklaar** [comment]
I see you finished the SSD1351 integration, great! Let me know if it would help if I send you one of these SSD1331's.

**Comment by kbx81** [comment]
I have one of these on order, but it seems everybody is out of stock and they are not due to ship until late October. 😞

If you would like this added sooner and are willing to send one, I won't turn it down! 😄

**Comment by hapklaar** [comment]
October really? You're not ordering from Ali I guess :)

If you PM me your address, I'll see to that you get one delivered!

**Comment by kbx81** [comment]
@hapklaar I received the display -- thank you! 🎉
It's been implemented and PR'd. Just needs approval and merging. 😄

**Comment by hapklaar** [comment]
@kbx81 That's great news, you're fast!

Will have a go at it as soon as it's available. Thanks again! :)

**Comment by emeyedeejay** [comment]
Hi! Is there any update on this at all? Also keen to get my SSD1331 screen integrated into ESPHome.

Thanks!

**Comment by kbx81** [comment]
It was merged into `dev` a while ago. It'll be in the next release, or if you need it now, you can run `dev`. 😄

**Comment by emeyedeejay** [comment]
Thanks!

I found the updated documents and am now running dev. Still can't get it working though :D

**Comment by emeyedeejay** [comment]
Now working 🙌

![2020-12-16_19h38_38](https://user-images.githubusercontent.com/8543879/102385403-7b5a5180-3fd6-11eb-8793-9452fb745dd0.png)
