### ISSUE TITLE
Follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by felixsanz** [esphome/feature-requests#768]
**Describe the problem you have/What new integration you would like**

Please store relevant files inside `${XDG_DATA_HOME}/esphome` (which is usually `~/.local/share/esphome`) instead of `~/.esphome`.

This removes clutter of the home directory.

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by OttoWinter** [comment]
ESPHome does not store anything in `~/.esphome`.

It only creates that directory in the same directory where the config file you're trying to compile is.
