### ISSUE TITLE
EspHome Native API: explicit HA IP address

### ISSUE THREAD

**Issue by mspinolo** [esphome/feature-requests#769]
**Disclaimer:: I am not a network expert hence my statements could be wrong

Hi,

logging my network activity with Wireshark I see Esphome flashed ESP8266/ESP32 send a decent amount of broadcasting messages querying for home assistant IP address.

This leads to a load of the network and IoT devices has usually a limited wifi bandwidth: a huge number of devices could reduce it.

I was wondering if it could be possible (and meaningful) to add to native API component an parameter to make explicit which is HA instance IP address in order to avoid broadcasting.**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

![grab 2020-06-10 alle 20 49 29](https://user-images.githubusercontent.com/43354538/84306523-e32d6c80-ab5b-11ea-8a76-9b8c5bbfa978.png)

here an example captured by wireshark of mDNS burst coming from a Sonoff S20 flashed with EspHome 1.14.3

here some statistics where the high burst (more than 80 packets/1sec) are all mDNS traffic between HomeAssistant and Esphome devices (which I have quite a few)
![grab 2020-06-10 alle 21 27 35](https://user-images.githubusercontent.com/43354538/84309971-3524c100-ab61-11ea-85f1-0c440acc948a.png)

below 1h of acquisition
![grab 2020-06-10 alle 21 27 59](https://user-images.githubusercontent.com/43354538/84310007-4372dd00-ab61-11ea-8b57-89e21ab5f21b.png)

**Comment by mspinolo** [comment]
I was wondering if similar result could be obtained disabling mDNS on ESPHome devices like it was (I think) before 1.11.0 --> is there an option for this?

**Comment by mddeff** [comment]
Would love to be able to manually specify a HA server in the config (either Hostname or IP).  Honestly I'm surprised ESPHome *requires* mdns/same subnet configurations.  (If I'm missing something, please feel free to enlighten)

**Comment by glmnet** [comment]
It’s not simple. 

Esphome is actually a server. I.e. hass connects to ESPHome. 


There is an old fr about reverting this, which solves other issues too.

**Comment by mspinolo** [comment]
Hi, 

So being ESPHOME a server why it is sending mDNS packets around?

**Comment by glmnet** [comment]
Will be part of https://github.com/esphome/feature-requests/issues/46
