### ISSUE TITLE
Add support for BL0940 power metering IC used in BlitzWolf® BW-SHP10

### ISSUE THREAD

**Issue by ClausRN** [esphome/feature-requests#770]
**Describe the problem you have/What new integration you would like**

I would like support for this power metering chip
http://www.belling.com.cn/media/file_object/bel_product/BL0940/datasheet/BL0940_V1.1_en.pdf

**Please describe your use case for this integration and alternatives you've tried:**

It is used in the BlitzWolf® BW-SHP10 smart plug
https://templates.blakadder.com/blitzwolf_SHP10P

**Additional context**

**Comment by Proxx** [comment]
The guys of tasmota are also making progress on this IC
https://github.com/arendst/Tasmota/issues/8175

**Comment by geerdkakes** [comment]
Has someone already started working on this? 

I could not order the older BW-SHP6 anymore. The BW-SHP10 I just received could be flashed with Tuya-Convert. Relay is on GPIO05.

**Comment by klaasnicolaas** [comment]
I would like to take up this issue, even now a few of those SHP10 plugs and it is a shame that it does not work with ESPHome yet.

However, I am still a beginner so don't expect much from it 😅
