### ISSUE TITLE
IR Remote for ESP Home

### ISSUE THREAD

**Issue by Chaosflori25** [esphome/feature-requests#790]
**Describe the problem you have/What new integration you would like**
It would be great to control a TV, a DVD player, and so much more with an IR Led via ESP Home. The IR codes could be collected in a spreadsheet or figured out via a separate sketch. I have no idea how hard it is to implement, but there is already an Arduino library for it available(irsend.h).

**Please describe your use case for this integration and alternatives you've tried:**
I'd like to control my Tv and DVD Player with it as well as my Amp. I tried the writing an arduino sketch that worked out quite ok, but I can't get OTA to work and would like to use ESP Home for centralizing all of my esp's

**Additional context**

**Comment by glmnet** [comment]
https://esphome.io/components/remote_transmitter.html
