### ISSUE TITLE
IOS app (Hamburger menu) back feature request

### ISSUE THREAD

**Issue by passie** [esphome/feature-requests#794]
**Describe the problem you have/What new integration you would like**

Using ESPHome in combination with the Home-assistant add-on and the IOS app. I would like to use the hamburger menu to go back or select a different menu item. 

![hamburger](https://user-images.githubusercontent.com/1913849/86637839-914ef980-bfd6-11ea-87f5-60e88de63850.png)

for example HACS (a popular add-on) does have this menu icon and i'm able to go to a different menu item. 
![hacs](https://user-images.githubusercontent.com/1913849/86639732-aed19280-bfd9-11ea-89e2-1b79e41c23b0.jpeg)

ESPHome is missing this menu icon.
![esphome](https://user-images.githubusercontent.com/1913849/86639623-7d58c700-bfd9-11ea-82f6-eaf8bc5556b1.jpeg)

**Please describe your use case for this integration and alternatives you've tried:**

Currently i'm unable to use ESPHome in the IOS app and go back to different menu item's if needed.

**Additional context**

**Comment by jonathanadams** [comment]
Does swiping from the left not bring up the menu in the HA app?

**Comment by passie** [comment]
Omg, you are right. Sorry

**Comment by passie** [comment]
Not a issue, since it's possible to swipe from the left.
