### ISSUE TITLE
ADD SSD1306 64x32 

### ISSUE THREAD

**Issue by anton-semeniak** [esphome/feature-requests#798]
**Describe the problem you have/What new integration you would like**

Can you please add resolution 64x32 for SSD1306 OLED display?
**Please describe your use case for this integration and alternatives you've tried:**

There is new model of 0.49 inch OLED display from Aliexpress
https://www.aliexpress.com/item/32618313295.html

**Additional context**

**Comment by nagyrobi** [comment]
Done: https://esphome.io/components/display/ssd1306.html?highlight=ssd1306
