### ISSUE TITLE
Find already installed esphome switches

### ISSUE THREAD

**Issue by jrhodk** [esphome/feature-requests#802]
**Describe the problem you have/What new integration you would like**

I have Hassos/ESPhome installed after change of platform but no backup to restore, and the 2 Sonoff ESPhome relays which is found by hassos, doesnt appear in the ESPhome dashboard

**Please describe your use case for this integration and alternatives you've tried:**

What do i do? Do i create them again or can i write something into configuration.yaml to make ESPhome see them?

**Additional context**

If there are no way to make the ESPhome dashboard find older ESPhome gadgets, it would be really nice with a button on the dashboard which could activate a search for relays etc..

**Comment by OttoWinter** [comment]
The dashboard lists .yaml files (and has an indicator for each file if a device with the same name is on the network).

If you don't have a configuration backup for those .yaml files, you need to recreate those. For example by using the setup wizard and then editing them to match the old config.
