### ISSUE TITLE
Support for i2c multiplexer tca9548a

### ISSUE THREAD

**Issue by guestisp** [esphome/feature-requests#807]
tca9548a is an i2c multiplexer, allowing to create 8 i2c busses from a single bus

Really useful when you can't change the remote i2c address and you have to connect multiple devices with the same address

Implementation seems pretty simple, to talk to one bus,you just have to send a byte with the bus number and following communicatons are routed automatically

**Comment by mkuziel** [comment]
What are the limitaitons? Basically it looks as simple issue, any experience person can comment on it?

**Comment by Primo83** [comment]
It would be fine to connect for example a lot of bme280 to one central esp32 (not only 4)

**Comment by andreashergert1984** [comment]
We need somebody for QA...

**Comment by Casino** [comment]
Any news for that feature?

**Comment by andreashergert1984** [comment]
Actually i am waiting for the merge. as there is imho no open point left.
correct if there is something to be done.

**Comment by andreashergert1984** [comment]
FR is tagged for merge in next Release: https://github.com/esphome/esphome/milestone/38
