### ISSUE TITLE
Follow on HA new automation / script improvements

### ISSUE THREAD

**Issue by glmnet** [esphome/feature-requests#809]
**Describe the problem you have/What new integration you would like**

I was reading [HA RC blog post](https://rc.home-assistant.io/blog/2020/07/14/release-113/) and they are coming with some improvements on the automation / script syntax and features. I believe we should follow this.

Basically they are adding a script mode

Mode | Description
-- | --
single | Do not start a new run, if running already.
restart | Start a new run, after stopping the previous run.
queued | Start a new run after all previous runs complete.
parallel | Start a new, independent, run in parallel with previous runs.

**Please describe your use case for this integration and alternatives you've tried:**

Right now scripts on ESPHome are parallel, and requires some thinking which these new features helps come with desired result easily, e.g. see the cool down options, or what we usually do:

```
  - script.stop: my_script
  - script.execute: my_script
```

to make sure we do a restart, now can take advantage of these new functions.

Also an interesting `max:` parameter is available for scripts which are parallel / queued.

**Additional context**

As ESPHome is highly aligned to HA project, learning one of the two will allow sb to easily understand how code runs.

**Comment by OttoWinter** [comment]
Oh that idea sounds great. The terms sound easy to understand and cover all use cases I can think of.

Thanks for bringing this up!
