### ISSUE TITLE
Support for the MICS5524 Detection Module

### ISSUE THREAD

**Issue by uglynerds** [esphome/feature-requests#814]
**Describe the problem you have/What new integration you would like**
Is there a way to support this module in ESPHome.

**Please describe your use case for this integration and alternatives you've tried:**
The MICS-5524 detection module can measure several gasses like Carbonoxide, Methan and Gas
There is a Adafruit library and example available see https://learn.adafruit.com/adafruit-mics5524-gas-sensor-breakout/usage
**Additional context**

**Comment by glmnet** [comment]
Modules which output a voltage are supported by any analog input sensor like: https://esphome.io/components/sensor/adc.html if you are using a built in esp pin or this https://esphome.io/components/sensor/ads1115.html will give you way better results.
