### ISSUE TITLE
Utilise FASTLED - setMaxPowerInVoltsAndMilliamps

### ISSUE THREAD

**Issue by highground88** [esphome/feature-requests#82]
**Describe the problem you have/What new integration you would like**
Currently unable to reduce power consumption via software

**Please describe your use case for this integration and alternatives you've tried:**
By allowing this field, power control can be provided in order to not underpower LED strip / or stress power supply. Could be very helpful for those who do not have sufficient power supplies or wich to restrict consumption due to high number of LED's.
example: 
`FastLED.setMaxPowerInVoltsAndMilliamps(5, 4000);` //cusomizable power management

More info: `[power_mgt.h](https://github.com/FastLED/FastLED/blob/master/power_mgt.h)`

**Additional context**

**Comment by OttoWinter** [comment]
No that is already possible, see `color_correct` here: https://esphome.io/components/light/fastled_clockless

The functions you're referring to just convert the values in the described units to maximum brightness for each channel, so in effect it does exactly the same thing as `color_correct`.

Of course we can also write a small formula to come up with the appropriate color correct numbers into the docs - contributions welcome.
