### ISSUE TITLE
IR Remote Climate fujitsu_general

### ISSUE THREAD

**Issue by Enzokot** [esphome/feature-requests#820]
**Describe the problem you have/What new integration you would like**

Please add support receiver for platform fujitsu_general in IR Remote Climate
**Please describe your use case for this integration and alternatives you've tried:**

 Not supported in current version
**Additional context**

**Comment by glmnet** [comment]
This is already available `dev` version of ESPHome see here in https://next.esphome.io/components/climate/ir_climate.html 

It will be available in next major version, if you want to use this right now check FAQ about running different versions of ESPHome

**Comment by Enzokot** [comment]
@glmnet feature request for this
![image](https://user-images.githubusercontent.com/43236573/88475278-0eff8880-cf37-11ea-8645-15bb08180e4f.png)

**Comment by Enzokot** [comment]
Add in PR [#1577](https://github.com/esphome/esphome/pull/1577)

**Comment by glmnet** [comment]
Yes I'll be updating the missing "yes" there in the docs
