### ISSUE TITLE
Add Output Component for SM16716

### ISSUE THREAD

**Issue by dison4linux** [esphome/feature-requests#83]
**Describe the problem you have/What new integration you would like**
Currently the SM16716 chip is only supported as a whole light (fastled_spi).  It would be helpful if the SM16716 was supported as an output component similar to MY9231/91 so that RGBW lights that use PWM output for White and the SM16716 for RGB can be supported (such as the Merkury 75W color bulb).

**Please describe your use case for this integration and alternatives you've tried:**
I'm sure a custom output component could be used but I'm not proficient in C++

**Additional context**

**Comment by OttoWinter** [comment]
Done!
