### ISSUE TITLE
Images read-in dynamically, when ESPHome is active and executing

### ISSUE THREAD

**Issue by htvekov** [esphome/feature-requests#860]
**Describe the problem you have/What new integration you would like**

With the emerging color display possibilities in ESPHome, I would find it really useful if image(s) somehow could be updated (read-in) dynamically and changed wile ESPHome is up running.

**Please describe your use case for this integration and alternatives you've tried:**

Displaying media player (Sonos) metadata image using ESPHome.
Source_list (radio stations) is rarely changed, so static images could be stored upon compiling.
But displaying meta data images for playlist content needs a dynamic approach.

**Additional context**

Home Assistant's Sonos integration exposes current entity_picture attribute with path and token
Example:
`entity_picture: /api/media_player_proxy/media_player.kokken?token=579b581bfd713df28d767400f841136fb6933cde9689e7af7b43b2cf92695ce5&cache=10e8d9cd802b5417`

**Comment by nagyrobi** [comment]
https://github.com/esphome/feature-requests/issues/1463
