### ISSUE TITLE
Request Support for RCWL-0516

### ISSUE THREAD

**Issue by Justahobby01** [esphome/feature-requests#865]
**Describe the problem you have/What new integration you would like**
 RCWL-0516 Microwave Radar Motion Detector.

**Please describe your use case for this integration and alternatives you've tried:**
 An alternative to PIR sensors.

**Additional context**
 https://circuits4you.com/2018/10/23/rcwl-0516-radar-sensor-interface-arduino

**Comment by thedexboy** [comment]
I believe you can just use a binary_sensor with gpio as platform for the sensor?

**Comment by Justahobby01** [comment]
Yes, you are right. It looks like it just needs the invert filter. Thanks.
