### ISSUE TITLE
Version string in configuration, available via the API

### ISSUE THREAD

**Issue by wsw70** [esphome/feature-requests#869]
**Describe the problem you have/What new integration you would like**

Some of my devices are connected, and some not. The ones that are not connected are in a "will use later" state.
When looking at them via the web interface, I do see the online and offline ones, but I do not know which configuration was **actually** flashed to them.

It would be great to have the possibility to
- add a version entry to the configuration file
- have this version displayed on the web interface OR alternatively - have it published via the API in a way that can be queried by Home Assistant (as a sensor for instance)

**Please describe your use case for this integration and alternatives you've tried:**

The use case is that I am never sure which configuration is flashed on the devices:

- the ones that were off when pushing a global change OTA have the older one
- the ones that have a specific configuration are not distinguishable (especially in case of multi-layer configurations)

**Additional context**

Specifically for Home Assistant, the ability to have that config string as a sensor would make it very easy to visualize this in a dashboard

**Comment by glmnet** [comment]
I believe you can achieve that quickly with a template text sensor?
