### ISSUE TITLE
Add support for Xiaomi BLE Temperature and Humidity sensor (LYWSD03MMC) on ESP32

### ISSUE THREAD

**Issue by vladacr** [esphome/feature-requests#872]
**Describe the problem you have/What new integration you would like**

Please add support for the LYWSD03MMC [XIAOMI Mijia Bluetooth Smart Electric Digital Thermometer Hygrometer](https://www.banggood.com/3Pcs-XIAOMI-Mijia-Bluetooth-Smart-Electric-Digital-Thermometer-Hygrometer-2-p-1595118.html?rmmds=myorder&cur_warehouse=CN) 
**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by wizu** [comment]
@vladacr it's already supported at dev branch.
https://next.esphome.io/components/sensor/xiaomi_ble.html#lywsd03mmc

**Comment by rradar** [comment]
as mentioned support is already present in next/dev version
