### ISSUE TITLE
Support for "Xiaomi Philips" light bulbs

### ISSUE THREAD

**Issue by Leon99** [esphome/feature-requests#883]
**Describe the problem you have/What new integration you would like**
Support for "Xiaomi Philips" light bulbs. Contrary to the CWWW platform, it processes color temperature using one PWM output and intensity using another.

**Please describe your use case for this integration and alternatives you've tried:**

Used, in my case, here: https://templates.blakadder.com/mirabella_genio_I002742.html (cheapest CWWW downlight available from retailers in Australia). 

**Additional context**

**Comment by Sergey-SRG** [comment]
> **Describe the problem you have/What new integration you would like**
> Support for "Xiaomi Philips" light bulbs. Contrary to the CWWW platform, it processes color temperature using one PWM output and intensity using another.
> 
> **Please describe your use case for this integration and alternatives you've tried:**
> 
> Used, in my case, here: https://templates.blakadder.com/mirabella_genio_I002742.html (cheapest CWWW downlight available from retailers in Australia).
> 
> **Additional context**


Hey. Today, at the end, I got my hands on these lamps, wrote the code through custom light.

Keep the link: [https://github.com/Sergey-SRG/ESPHome-Xiaomi-Philips-light](https://github.com/Sergey-SRG/ESPHome-Xiaomi-Philips-light)
