### ISSUE TITLE
Support for Samsung A/Cs via IR Remote Climate

### ISSUE THREAD

**Issue by xorbital** [esphome/feature-requests#896]
**Describe the problem you have/What new integration you would like**

I would like to integrate my Samsung A/Cs into Home-Assistant, the new IR Remote Climate seems like a great fit for that.
This is the remote:
![remote](https://user-images.githubusercontent.com/53773184/93065969-a8b2fe80-f679-11ea-9451-c3cf07564cf8.jpg)

**Please describe your use case for this integration and alternatives you've tried:**

The A/Cs used to have an open port for local API access, however they only use the proprietary Smartthings cloud now.

**Additional context**

This issue is related to #444 I guess
There are some advanced commands the remote can send, like a "windfree" mode, which closes the flap, Eco Mode, Quiet Mode, Timers and a "Fast" mode. On my unit (AR12TXEAAWKNEU) some of the features of the remote (like direct/indirect, purify) aren't suported, but they are still present on the remote.
https://github.com/crankyoldgit/IRremoteESP8266/ already has support for SamsungAC codes, however the commands for this unit are a bit different.

I captured some IR codes and tried to decode it as far as I can, please let me know what I can do now :)

This is the command for Cooling, 16°C, Windfree (Fan Auto):
`02,92,0F,00,00,00,F0,01,D2,FE,7B,00,11,F0`
I got this with the code from https://github.com/ToniA/Raw-IR-decoder-for-Arduino:
What I found out so far: https://cryptpad.fr/sheet/#/2/sheet/view/REURkHbGuQdU+wQkBcwKBXmccftjIB+Tyzin34EXs-g/

**Comment by Fusseldieb** [comment]
I have the same AC and would love to control it!

Currently using a simple "switch" to send an IR command for on and another for off

**Comment by xorbital** [comment]
I'm currently trying to use IRremoteESP8266 for that: https://github.com/crankyoldgit/IRremoteESP8266/issues/1277
It might be possible to use that code for esphome than as well...

Here are the signals I've decoded so far (short codes): https://cryptpad.fr/sheet/#/2/sheet/view/REURkHbGuQdU+wQkBcwKBXmccftjIB+Tyzin34EXs-g/
I got this decoded with https://github.com/ToniA/Raw-IR-decoder-for-Arduino
However if you don't have a shitty IR decoder like me you might be able to use the examples from IRremoteESP8266 as well...

**Comment by iglu-sebastian** [comment]
https://github.com/esphome/feature-requests/issues/444 has some more info

**Comment by xorbital** [comment]
The unit is now supported in the master branch in the upstream library and will make it's way into ESPHome eventually.
