### ISSUE TITLE
Add SHARP IR remote control

### ISSUE THREAD

**Issue by SRI44760** [esphome/feature-requests#911]
**Describe the problem you have/What new integration you would like**

I would like to remote my SHARP tv and the raw not functioning 

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by napieraj** [comment]
Please describe in more detail the model of TV you are trying, how you are using the raw codes, and how it is not working.

At the very least your configuration and some logs would be helpful
