### ISSUE TITLE
Support for the SPI RF remote reciever module (nRF905)

### ISSUE THREAD

**Issue by sebasptsch** [esphome/feature-requests#917]
**Describe the problem you have/What new integration you would like**

Support for the nRF905 Transceiver module through SPI.  

**Please describe your use case for this integration and alternatives you've tried:**
Anyone buying this module will be able to plug-and-play using spi  and the remote component.

**Additional context**
Bought the module from Jaycar in Australia.
[Datasheet](https://www.jaycar.com.au/medias/sys_master/images/images/9426951372830/XC4522-dataSheetMain.pdf)
[Product Page](https://www.jaycar.com.au/arduino-compatible-rf-transceiver-module/p/XC4522)

**Comment by sebasptsch** [comment]
[Arduino Example Code](https://www.electrodragon.com/w/NRF905)

**Comment by sebasptsch** [comment]
[nRF905 Library](https://github.com/zkemble/nRF905)

**Comment by renini** [comment]
@sebasptsch may i ask why you closed this. I was actually just looking for the same, did you get this module to work with esphome?

**Comment by sebasptsch** [comment]
> @sebasptsch may i ask why you closed this. I was actually just looking for the same, did you get this module to work with esphome?

I gave up and purchased a different module on eBay which is proven to work. I figured it would be a lot of effort for not very many users trying to get that to work.

**Comment by renini** [comment]
> > @sebasptsch may i ask why you closed this. I was actually just looking for the same, did you get this module to work with esphome?
> 
> I gave up and purchased a different module on eBay which is proven to work. I figured it would be a lot of effort for not very many users trying to get that to work.

Ah oke, what did you end up buying? Im using the esp32+nrf905 and using a arduino api webinterface https://github.com/eelcohn/nRF905-API. But figured esphome would give better integration...

**Comment by sebasptsch** [comment]
I bought a standard receiver and transmitter set which work with esphome by default and integrate nicely.

**Comment by xirixiz** [comment]
What exacly did you buy @sebasptsch? I`m using https://github.com/eelcohn/nRF905-API but it's very unstable.

**Comment by sebasptsch** [comment]
> What exacly did you buy @sebasptsch? I`m using https://github.com/eelcohn/nRF905-API but it's very unstable.

I believe one of the first comments on this thread has all that information.
