### ISSUE TITLE
Manual operation software switch

### ISSUE THREAD

**Issue by abelmatser** [esphome/feature-requests#927]
**Describe the problem you have/What new integration you would like**

A software switch which can be accessed through the web interface. This switch should not be based on any hardware event, solely on a user manually changing the switch through Home Assistant or the ESP's web page.

**Please describe your use case for this integration and alternatives you've tried:**

For friends without Home Assistant, I am building a sensor with a coupled actuation output. Since this could be unwanted at some times, I would like to give them the option to disable this automation manually. They could of course just remove the power plug, but that would be a caveman solution.

**Additional context**

**Comment by napieraj** [comment]
https://esphome.io/components/switch/template.html

set `optimistic: true` unless you have another way of determining the switch state
