### ISSUE TITLE
Cover, open_duration and close_duration, variables instead of just numbers

### ISSUE THREAD

**Issue by osalval** [esphome/feature-requests#930]
**Describe the problem you have/What new integration you would like**
I want to be able to vary from Home Assistant, the number of seconds of:
"open_duration" and "close_duration" variables for a Cover type: "Time-Based Cover", using for example an "input_number"

**Please describe your use case for this integration and alternatives you've tried:**

 I have tried this only for **open_duration**, using  id: **${name}_open_duration**, like this:

`sensor:
  - platform: homeassistant
    name: "Tiempo de Subida"
    id: ${name}_open_duration
    entity_id: input_number.persiana_habita_set_uptime
`

`cover:
  - platform: time_based
    device_class: shutter
    name: "Persiana Habitación"
    id: ${name}_cover
    open_action:
      - switch.turn_on: open_cover

    open_duration: 
      seconds: ${name}_open_duration

    close_action:
      - switch.turn_on: close_cover
    close_duration: 23s

    stop_action:
      - switch.turn_off: open_cover
      - switch.turn_off: close_cover
` 

**Additional context**
I can't Validate, I get the error: Expected float

**Comment by napieraj** [comment]
those values are set on compile-time, before there is even a connection to Home Assistant -- you can update them manually using a lambda and the `.set_open_duration()` and `.set_close_duration()` arguments of the time-based cover component: https://esphome.io/api/classesphome_1_1time__based_1_1_time_based_cover.html

**Comment by ludrao** [comment]
Hi @napieraj , not sure how it is generated but https://esphome.io/components/cover/time_based.html does not seem to document these two lambdas ?

**Comment by nagyrobi** [comment]
You can use lambdas as @napieraj suggests.
