### ISSUE TITLE
Climate thermostat fan steady on

### ISSUE THREAD

**Issue by Cecchellone** [esphome/feature-requests#937]
**Describe the problem you have/What new integration you would like**

FAN_ONLY should not be considered as cooling method, and should not need a target_temperature to work.

**Please describe your use case for this integration and alternatives you've tried:**

Unable to set FAN_ONLY without setting a (colder) temperature.

**Additional context**

FAN_ONLY is not "cooling", a fan is used rather to circulate air than cooling down the house.

**Comment by kbx81** [comment]
This would be an easy change (and would simplify the code some). I wrote this into the component after a few folks mentioned using the fan for cooling. I don't feel strongly either way -- the only question I have is this: What is the difference (mechanically with an HVAC system) between setting the "fan mode" to "ON" as opposed to selecting "fan only" for the climate mode? In my situation, if I want the fan to run constantly, on my thermostat, I set the fan mode to "on" (as opposed to "auto" or "off"). Again, I'm not arguing either way, it's little more than idle curiosity. 😄

I'm planning to do work more on the thermostat component very soon so I'll aim towards fitting this in.
