### ISSUE TITLE
Store YAML source on device, make it available via Web Server interface

### ISSUE THREAD

**Issue by Johnny-Larue** [esphome/feature-requests#938]
### Describe the problem you have/What new integration you would like

I'd like a mechanism to recover the actual YAML source for the device from the device itself.

### Please describe your use case for this integration and alternatives you've tried:

In the event of the loss of the original YAML files, it would be nice to be able to recover the original YAML from the device itself, perhaps in an accordion box on the Web Server page, or in a dialogue.

At the very least, it would be great to be able to download a compressed version of the text, at the very best, simply be presented with the raw code in a PRE HTML tag, with a 'Copy' button to copy the code entire as simple text.

If possible a version of the code with the substitutions from the secrets.yaml (and any other source) clearly visible would be ideal as well. Perhaps this could be an option in the eventual component section in the YAML source.

### Additional context

Example of what I'd love to be able to do (I've attached two mock-ups for reference:

```
web_server:
  port: 80
  yaml_include: True
    reveal_secrets: True
    reveal_substitutions: True
```

![yaml_include_1](https://user-images.githubusercontent.com/28499477/95273384-f3570f00-0810-11eb-9d91-26329edfdaf8.jpg)
![yaml_include_2](https://user-images.githubusercontent.com/28499477/95273387-f3efa580-0810-11eb-9b35-828bf29b4e31.jpg)

**Comment by snickers2k** [comment]
+1 would be great. what ever the bot think is missing.. pls reopen
