### ISSUE TITLE
Rotary encoder on_clockwise/on_anticlockwise triggers

### ISSUE THREAD

**Issue by jesserockz** [esphome/feature-requests#944]
**Describe the problem you have/What new integration you would like**

It would be nice to have `on_clockwise` and `on_anticlockwise` triggers for the `rotary_encoder` sensor.

**Please describe your use case for this integration and alternatives you've tried:**

You can use `on_value` but this requires that you store the previous state and get the difference. This would make that logic internal as it the code already knows which direction it is turning in.

**Additional context**

**Comment by glmnet** [comment]
Another option would be passing another argument with the delta change, then you can test the sign of the value.
