### ISSUE TITLE
BME680 Air Quality support

### ISSUE THREAD

**Issue by TravellerNL** [esphome/feature-requests#946]
**Describe the problem you have/What new integration you would like**

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by wifwucite** [comment]
Check this out [ESPHome with Bosch BSEC library](https://github.com/trvrnrth/esphome-bsec-bme680).

**Comment by KastB** [comment]
This worked for me out of the box:
https://esphome.io/components/sensor/bme680.html
Shouldn't we close this?
