### ISSUE TITLE
upload bin file via OTA

### ISSUE THREAD

**Issue by kaiba4786** [esphome/feature-requests#954]
**Describe the problem you have/What new integration you would like**
Hi everyone!
i have esphome device (using esp8266) but i lost the yaml file.
I created a new yaml file and compiled it to get the bin file,
but i don't know how to upload it to my device via OTA (i don't want to use USB FTDI programmer because i have many devices and opening to connect battery is very complicated)

Can someone guide me to make bin file upload to my device via OTA?
I would be very grateful! 

**Please describe your use case for this integration and alternatives you've tried:**

I have tried using this script but with no success: 
python espota.py -i <ESP_IP_address> -I <Host_IP_address> -p <ESP_port> -P <Host_port> [-a password] -f <sketch.bin>  -d -r

**Additional context**

**Comment by rradar** [comment]
@kaiba4786 you can do this easily with esphome directly:

```
esphome newnode.yaml run --upload-port oldnode.local
```
