### ISSUE TITLE
Easier add for BLE-sensors and devices

### ISSUE THREAD

**Issue by oh2ftu** [esphome/feature-requests#956]
**Describe the problem you have/What new integration you would like**
Ideally only mac-address and platform would be mandatory for a sensor.
The current method to list and name each measured value from each sensor is quite much labor when one has multiple (>10) BLE-sensors.
Also, if no name would be given for eg. temperature, it would default to $macaddr_temperature or similar

**Please describe your use case for this integration and alternatives you've tried:**
I have 10 or so Xiaomi BLE-beacons with the custom firmware. I've yet to find an easy to use, BLE->MQTT bridge that would relay each sensor as it's own device.

**Additional context**

**Comment by nagyrobi** [comment]
See https://github.com/nagyrobi/home-assistant-configuration-examples/blob/main/esphome/ble-sensors-ethernet.yaml for lots of Xiaomis.
Also see https://github.com/esphome/esphome/pull/3612 for simplifying repetitive config.
