### ISSUE TITLE
Add support for Shelly temperature sensor addon

### ISSUE THREAD

**Issue by Erd86** [esphome/feature-requests#957]
**Describe the problem you have/What new integration you would like**

I would like to get an addon for shelly temperatur sensor addon. 
Link: https://shopusa.shelly.cloud/temperature-sensor-addon-for-shelly-1-1pm-wifi-smart-home-automation-1#334

With this addon you can connect DS18B20/DHT22/AM2302 1-wire sensors to shelly devices.
The module has also included an opto-insolator. 

By default, shelly supports up to three DS18B20 sensors.
Maybe this is only a software limitation and we can fix this limitation inside esphome.

**Please describe your use case for this integration and alternatives you've tried:**

I want to have a small AC powered relay module with support for temperature sensors. The sensors should be opto-insolated.

**Additional context**

The addon is already implemented in tasmota firmware. I think this can help for implementation.
Link: https://github.com/arendst/Tasmota/issues/7469

**Comment by randybb** [comment]
Duplicate of #701
