### ISSUE TITLE
Add more detailed descriptions for other esp boards

### ISSUE THREAD

**Issue by JonathanTreffler** [esphome/feature-requests#965]
**Describe the problem you have/What new integration you would like**
I would like detailed descriptions like the one of the NodeMCU ESP32 for more boards like the doit esp32 devkit v1.

**Please describe your use case for this integration and alternatives you've tried:**
The pinout image is very useful and i have not found another way to find all supported devices without actually having esphome installed and opening the new device wizard.

**Additional context**
I would absolutely like to help add these descriptions, but i don't know where to get pinout images that look like the existing ones.
Are they custom made for this site or where are they from ?

**Comment by rradar** [comment]
I think all of the device support are taken upstream from [platformio](https://platformio.org/platforms) ([esp8266](https://platformio.org/platforms/espressif8266) & [esp32](https://platformio.org/platforms/espressif32)).

A overview for a couple of boards/modules can be found here:

- [ESP8266 Pinout Reference: Which GPIO pins should you use?](https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/)
- [ESP32 Pinout Reference: Which GPIO pins should you use?](https://randomnerdtutorials.com/esp32-pinout-reference-gpios/)
