### ISSUE TITLE
Decouple api component from async_tcp

### ISSUE THREAD

**Issue by rob-deutsch** [esphome/feature-requests#970]
**Describe the problem you have/What new integration you would like**
Wi-Fi is power hungry. I would like to connect my ESPHome project to Home Assistant via an [RFM69 wireless network](https://www.sparkfun.com/products/12823).

**Please describe your use case for this integration and alternatives you've tried:**

The native API looks to only operate over TCP, which is fine, but given that it's a neat binary protocol it should be able to run over any transport.

**Additional context**

I imagine that this could be tackled by create an appropriate abstract base class for TCP, which will allow for all types of transports for the binary stream.

I think this is also a relatively low-priority request for me. I have a project in mind that would require low power usage, and this would be useful to have.

**Comment by rob-deutsch** [comment]
Noting that https://github.com/esphome/esphome/pull/809 is along the lines of what I had in mind.

**Comment by herostrat** [comment]
See: https://github.com/esphome/esphome/pull/809
If I understand correctly this should solve this request?

**Comment by nagyrobi** [comment]
Assuming PRs above solve the request.
