### ISSUE TITLE
Gurantee OTA'bility

### ISSUE THREAD

**Issue by rradar** [esphome/feature-requests#971]
**Describe the problem you have/What new integration you would like**

I always do ota updates but now managed some how (with big binaries) to brick the ota update functionality on a couple of my devices.

For some devices it's just annoying to disassemble them and do a flash them over serial. But for other devices it's **simply not possible** to do this, **for example light bulbs** or some devices which internally use the rx/tx from the esp to control rf module for example.

I actually now have a kind of bricked device and I'm not able to flash new firmware via ota (tried even various arduino_frameworks to find the smallest binary possible)

**Please describe your use case for this integration and alternatives you've tried:**

Not quite sure how achieve this. Some ideas: 

- Space in flash could be reserved for ota updates (which will shrink the available space for esphome :-1:)
- esphome could somewhat include a "emergency mode" which doesn't do more than `wifi` (maybe including `ap:`) and `ota` and therefor guarantees to be ota updatable because it will overwrite all flash content which is not part of the "emergency system"
- When running esphome (before doing the ota) the free flash space could be calculated and when it will be critical low to do a ota afterwards there could be warning and question:
 > **Do you really want to flash this ota update?** There probably won't be any space left to do other ota updates anymore. Flashing via serial will be most likely mandatory
-> `Yes - I know what I'm doing`, `No - I don't want to break things`

**Additional context**

Not yet

**Comment by nagyrobi** [comment]
OTA'bility improved by:
https://github.com/esphome/esphome/pull/2601
https://github.com/esphome/esphome/pull/2437
