### ISSUE TITLE
support setting brightness on SSD1106

### ISSUE THREAD

**Issue by tomdee** [esphome/feature-requests#99]
**Describe the problem you have/What new integration you would like**
It would be great if the brightness of displays can be controlled

**Please describe your use case for this integration and alternatives you've tried:**
Devices in bedrooms could dim at night

**Additional context**
Some of the arduino libraries support brightness. Also https://ssd1306.readthedocs.io/en/latest/

**Comment by 7h30n3** [comment]
There is already a protected method in `ssd1306_base.cpp` called `this->command(SSD1306_COMMAND_SET_CONTRAST);` 
But I don't know how to make use of it.

**Comment by OttoWinter** [comment]
Closing per https://github.com/esphome/esphome/pull/723
