### ISSUE TITLE
PMSX003 CF1 data

### ISSUE THREAD

**Issue by redstreet** [esphome/feature-requests#992]
**Describe the problem you have/What new integration you would like**
Capture "CF1" data from PMSX003 sensors.

**Please describe your use case for this integration and alternatives you've tried:**

From a recent study, the [US EPA](https://cfpub.epa.gov/si/si_public_record_report.cfm?dirEntryId=349513&Lab=CEMM) recommends applying a correction factor for PMSX003 sensors that requires the CF1 data from it. [See formula here](https://cfpub.epa.gov/si/si_public_file_download.cfm?p_download_id=540979&Lab=CEMM).

**Additional context**
This is the data that PMSx003 outputs:
```
pm1_0cf1 <-- requesting this
pm2_5cf1 <-- requesting this
pm10cf1  <-- requesting this
pm1_0    <-- currently available in ESPHome
pm2_5    <-- currently available in ESPHome
pm10     <-- currently available in ESPHome
n0_3
n0_5
n1_0
n2_5
n5_0
n10

```

Thank you for making ESPHome. It's terrific!

**Comment by nagyrobi** [comment]
Implemented in https://github.com/esphome/esphome/pull/1694 (options witth `_std`).
