### ISSUE TITLE
Support for OPT3001 calibrated I2C lux sensor

### ISSUE THREAD

**Issue by kylegordon** [esphome/feature-requests#999]
**Describe the problem you have/What new integration you would like**
Support for the I2C capable OPT3001 lux sensor - https://www.ti.com/lit/ds/symlink/opt3001.pdf

**Please describe your use case for this integration and alternatives you've tried:**
A growing number of breakout boards for the OPT3001 sensor are now available at very low cost. They are becoming a common replacement for the 'traditional' LDR and voltage divider. 

Example code is available below

* PlatformIO library https://platformio.org/lib/show/838/ClosedCube%20OPT3001
* Arduino example code 
* https://github.com/closedcube/ClosedCube_OPT3001_Arduino/blob/master/examples/opt3001demo/opt3001demo.ino
* https://github.com/closedcube/ClosedCube_OPT3001_Arduino/blob/master/src/ClosedCube_OPT3001.h
* https://github.com/closedcube/ClosedCube_OPT3001_Arduino/blob/master/src/ClosedCube_OPT3001.cpp

**Additional context**
I have tried hacking together some of the above code into a custom ESPHome I2C sensor as per the documentation, but I have zero C++ knowledge. I can't even get .begin() to work. I am happy to help and test if anyone else can munge the code together.

**Comment by OstertagM** [comment]
I have made it with an external component over git hub see:
`
  # Example configuration entry
i2c:
  - id: bus_a
    sda: D2
    scl: D1
    scan: True

external_components:
# equivalent shorthand for GitHub
  - source: github://OstertagM/ESPhome-user-component/esphome@main
    components: [ OPT3001 ]
    refresh: 0s

# Example configuration entry
sensor:
  - platform: OPT3001
    i2c_id: bus_a
    illuminance:
      name: "Living Licht"
    address: 0x45
    update_interval: 5s
      
  - platform: sht3xd
    i2c_id: bus_a
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    address: 0x44
    update_interval: 60s
  `
It was just an integration of the ClosedCube also. I hope somebody improve the code. But for me it works.
